### ISSUE TITLE
Enable analytics on countly

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1002]
We used to use fabric for crash reporting and analytics.

Since recently fabric has been acquired by google and now it's all inside of this new platform called firebase.

The new platform is now asking us:

> You can now measure your mobile and web app data with Google Analytics. It’s the same free app analytics features you’re familiar with but with cross-device reporting, rich analysis capabilities, and more.

We should evaluate this option and understand if they are actually already collecting this data and just not showing it to us or if by enabling it we are giving them extra data and we should rather use some other system for analytics.

We should also look into how we can provide opt-out mechanisms for users. For example if they disable crash reporting will this also affect collection of analytics data?

**Comment by hellais** [comment]
We should investigate:
https://developer.matomo.org/guides/ab-tests/apps
https://github.com/matomo-org/matomo-sdk-android
https://github.com/matomo-org/matomo-sdk-ios

We already have a running matomo instance at https://matomo.ooni.org/

**Comment by lorenzoPrimi** [comment]
Moving  it to Sprint 7

**Comment by hellais** [comment]
This may also be another thing to look into: https://github.com/Countly/countly-server.

It could also help us out for the push notification story.

**Comment by hellais** [comment]
As part of this I have setup a testing countly server here: https://mia-countly-test.ooni.nu/dashboard#/5e550c5b7ecb845117d5dc6a/

**Comment by lorenzoPrimi** [comment]
Please write the objectives we want to achieve with the Countly implementation
- Track crash logs
- Check out their push notification system

What else?
At the moment we have zero analytics code in the app, we dont track screens, screen time or actions, do we want it?

**Comment by lorenzoPrimi** [comment]
We will discuss on the frontend meeting what we want to track to add some simple code

**Comment by lorenzoPrimi** [comment]
Do we close this card or keep it open for when we want to implement custom tracking and advanced analytics?
