### ISSUE TITLE
Properly handle SIGTERM signal on windows

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1005]
It has been reported that the SIGTERM signal is not getting trapped on windows and therefore when you try to terminate an OONI Probe run on windows it does not shutdown cleanly as it does on macOS.

We should check to see how we can handle this properly on windows.

**Comment by bassosimone** [comment]
The first to note in this respect is the following (from [the documentation of process](https://nodejs.org/api/process.html#process_signal_events)):

> Windows does not support sending signals, but Node.js offers some emulation with process.kill(), and subprocess.kill(). Sending signal 0 can be used to test for the existence of a process. Sending SIGINT, SIGTERM, and SIGKILL cause the unconditional termination of the target process.

Under the hood, the OONI app is using `process.kill`. This is working okay also in [my test case](github.com/bassosimone/eeatko). The issue with that is that killing the process abruptly makes the results less user friendly and, specifically, the "session of tests" is incomplete.

[Research](https://stackoverflow.com/a/50020028) suggests that `windows-kill` or `wwindowskill` are potentially using the correct code to terminate a process gracefully.

However, in the only Windows enabled build environment that I have they are both broken. The former does build. The latter, which was created to fix the former, does not load at runtime claiming that I am using the wrong version of Node.js. This does not vouch well for the sustainability of using either of these packages in the long run as a graceful Windows kill solution.

**Comment by sarathms** [comment]
Did you assess this idea of [sending "Ctrl+C" to the child process](https://stackoverflow.com/questions/17648654/how-to-send-control-c-node-js-and-child-processes?noredirect=1&lq=1)?

**Comment by bassosimone** [comment]
@sarathms wrote:
> Did you assess this idea of sending "Ctrl+C" to the child process?

No, I'll take a look, thanks a bunch!

@bassosimone wrote:
> The latter, which was created to fix the former, does not load at runtime claiming that I am using the wrong version of Node.js

This is actually WAI. Electron uses a different Node than Node. Using `electron-rebuild` fixes!

**Comment by bassosimone** [comment]
@sarathms it did not work: my understanding is that we're not in a proper PTY in Windows. There is a node library (https://github.com/microsoft/node-pty) that implements PTYs for Node using different strategies on Windows, but I couldn't manage this library to respond to a graceful shutdown request so far. Yet, there must be a way to do that, clearly, since `cmd.exe` does that.

**Comment by bassosimone** [comment]
I ended up working on this (and IMHO fixing this) because it was interesting to me. Please, see the above referenced PRs for context on how I fixed it. I am going to assign effort, move to the right sprint and yadda yadda yadda such that we properly track this work.
