### ISSUE TITLE
Display measurement upload status in the UI

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1009]
We should support showing if a measurement has been uploaded successfully in the OONI Probe desktop UI, even if we don't yet support re-uploading them.

It's a matter of look at the:

`is_uploaded: true | false` field

Here is a full example:

```
{
    "fields": {
        "asn": 30722,
        "failure_msg": "",
        "id": 7651,
        "is_anomaly": false,
        "is_done": true,
        "is_failed": false,
        "is_first": true,
        "is_last": false,
        "is_upload_failed": false,
        "is_uploaded": true,
        "measurement_file_path": "[REDACTED]/.ooniprobe/msmts/middlebox-2020-02-05T174308.675025Z/msmt-http_invalid_request_line-0.json",
        "network_country_code": "IT",
        "network_name": "Vodafone Italia S.p.A.",
        "report_file_path": "",
        "runtime": 5.198821,
        "start_time": "2020-02-05T17:43:08.844353Z",
        "test_group_name": "middlebox",
        "test_keys": "{}",
        "test_name": "http_invalid_request_line",
        "type": "measurement_item",
        "upload_failure_msg": "",
        "url": "",
        "url_category_code": "",
        "url_country_code": ""
    },
    "level": "info",
    "timestamp": "2020-02-10T10:44:48.530021+01:00",
    "message": "measurement"
}
```

**Comment by hellais** [comment]
I made a mockup for this here: https://sketch.cloud/s/eDGpa/a/wPW43q

Screenshot below:
![Screenshot 2020-02-24 at 18 41 47](https://user-images.githubusercontent.com/424620/75176912-6950af00-5735-11ea-9cb9-c1c46be2cd69.png)

The icon is the material design icon `cloud_off` with applied the color `gray6` #868E96

**Comment by sarathms** [comment]
This information is available at the measurement level. We can show it after clicking one of the results. Without that, we might slow down rendering the test results screen while we iterate through all measurements.

**Comment by hellais** [comment]
We should file an issue to add support for listing in the top level view in probe-cli.

For the time being let's just put in the details view as on mobile next to the URL or test name.

See the mocks for android:
![Screenshot 2020-02-26 at 16 10 36](https://user-images.githubusercontent.com/424620/75358218-d2a9fc80-58b2-11ea-8e8e-ae02def7b11e.png)
![Screenshot 2020-02-26 at 16 12 37](https://user-images.githubusercontent.com/424620/75358231-d9387400-58b2-11ea-8635-24bf9032a1f2.png)
