### ISSUE TITLE
mobile: interrupt running experiment

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1026]
As discussed in https://github.com/ooni/probe/issues/841, we want to cancel a running experiment. On both iOS and Android, the way to go is to call the `interrupt` method of `MKAsyncTask`.

**Comment by bassosimone** [comment]
We started looking into this issue with @lorenzoPrimi. MK is broken and a new release is required to interrupt running tests. A possible implementation of this approach is:

```
diff --git a/src/libmeasurement_kit/common/libevent_reactor.hpp b/src/libmeasurement_kit/common/libevent_reactor.hpp
index c4de9fd3..5613eeca 100644
--- a/src/libmeasurement_kit/common/libevent_reactor.hpp
+++ b/src/libmeasurement_kit/common/libevent_reactor.hpp
@@ -99,6 +99,8 @@ class LibeventReactor : public Reactor, public NonCopyable, public NonMovable {
 
     // ## Event loop management
 
+    std::atomic_bool interrupted{false};
+
     event_base *get_event_base() override { return evbase.get(); }
 
     void run() override {
@@ -107,6 +109,15 @@ class LibeventReactor : public Reactor, public NonCopyable, public NonMovable {
             if (ev_status < 0) {
                 throw std::runtime_error("event_base_dispatch");
             }
+            // If we have been interrupted, enter into a special mode where we
+            // wait for background threads to complete. Then we just leave.
+            while (interrupted) {
+                while (worker.concurrency() > 0) {
+                    std::this_thread::sleep_for(std::chrono::milliseconds(50));
+                }
+                interrupted = false;
+                return;
+            }
             /*
                 Explanation: event_base_loop() returns one when there are no
                 pending events. In such case, before leaving the event loop, we
@@ -133,6 +144,7 @@ class LibeventReactor : public Reactor, public NonCopyable, public NonMovable {
         if (event_base_loopbreak(evbase.get()) != 0) {
             throw std::runtime_error("event_base_loopbreak");
         }
+        interrupted = true;
     }
 
     // ## Call later
```

This is like an hard interrupt where we stop whenever we are. As discussed with @hellais, yet, it seems we're more interested in implementing safe interruption points within the codebase. This seems to be a bit more complex in that it requires some refactoring. That is, the above code is a bug fix for the structure being correct and the code not being working as intended. Instead, the safe interruption points is another endeavour where we refactor the code a bit to enable this functionality.

With @lorenzoPrimi we're now looking into whether the Go engine is interruptible. I think it may not be, because I forgot that https://github.com/ooni/probe-engine/issues/351 has not been implemented yet. So, while the internals are interruptible, the outer API probably is not. Also for https://github.com/ooni/probe-engine/issues/351, we need to take into account the above comment concerning safe interruption points, tho.

**Comment by bassosimone** [comment]
So, the way in which I am going to implement this in probe-engine is that:

1. we can interrupt experiments with input when we process each individual input

2. we can interrupt long experiments (e.g. ndt, dash) anytime

This will be done in https://github.com/ooni/probe-engine/pull/410

**Comment by bassosimone** [comment]
The above has been implemented in probe-engine as part of https://github.com/ooni/probe-engine/pull/410. So, now we have the possibility of interrupting tests on mobile apps for Go tests.

**Comment by bassosimone** [comment]
We have confirmed with @lorenzoPrimi that we can interrupt `ndt7` using https://github.com/ooni/probe-engine/pull/410. My personal preference on the matter is that we don't change MK and only implement interruption for new tests in Go.

**Comment by lorenzoPrimi** [comment]
The branches in iOS and android will remain there as code example and the interrupt functionalities will be implemented after Go.
Furthermore we will probably implement a `isCancellable` function in go that will tell the app is showing the cancel test icon or not

**Comment by bassosimone** [comment]
Agreed! I believe I can detach myself from this issue, because there is not much more I should be doing here and my main focus should be on landing the Go engine for mobile quite soon. Thanks!
