### ISSUE TITLE
probe-cli: sprint 7 release

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1028]
Near the end of sprint 7, we should bless a new ooni/probe-cli release. I suggest that we settle that we tag a new ooni/probe-engine the first week of the sprint, if we have changes, and we tag a new ooni/probe-cli in the second week of the sprint, if we have changes. @hellais what do you think?

**Comment by hellais** [comment]
Yes this seems like a good idea!

**Comment by bassosimone** [comment]
done!
