### ISSUE TITLE
Display in the OONI Probe Desktop that the app is being stopped

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1032]
This is the probe-desktop implementation for: https://github.com/ooni/probe/issues/1006

**Comment by holantonela** [comment]
https://github.com/ooni/probe/issues/1006#issuecomment-590354947 looks good for me.

I wonder if the loading bar is necessary or if we can rely on the main icon animation as a loader for user feedback. What y'all think?

**Comment by hellais** [comment]
@sarathms mentions that there is not easy way to implement the stripped progress bar we should evaluate if there is some other solution for this.
