### ISSUE TITLE
Add OONI Probe mobile apps user-agent [iOS]

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1035]
The OONI Probe mobile apps should identify themselves with a clearly distinguishable user agent.

```
ooniprobe-android/X.Y.Z
ooniprobe-ios/X.Y.Z
```

Ref:
https://stackoverflow.com/questions/27213291/how-to-define-a-header-to-all-request-using-retrofit
https://stackoverflow.com/questions/26509107/how-to-specify-a-default-user-agent-for-okhttp-2-x-requests

**Comment by hellais** [comment]
This has been done.
