### ISSUE TITLE
Enable the thematic testing of websites via the OONI Probe apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1037]
Social media is frequently blocked around the world.

To enable thematic testing of specific types of websites (especially in response to emergent censorship events), it would be great if we could enable thematic website testing inside the OONI Probe apps.

Specifically, we could integrate the buttons from this page: https://ooni.org/get-involved/run/ 

That way, instead of requiring users to come to this page and tap on the buttons, they could find them directly inside the OONI Probe app.

We probably need to discuss this further to determine the implementation and UX details.

**Comment by hellais** [comment]
We are going to be doing this via the backend prioritization logic and not inside of the app.
