### ISSUE TITLE
Fix OONI Explorer links linked in the mobile & desktop apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1041]
The OONI Probe mobile & desktop apps link to an old version of OONI Explorer (https://explorer.ooni.io/world/) which no longer works.

We need to replace these links with the new URL of the revamped OONI Explorer: https://explorer.ooni.org/

**Comment by agrabeli** [comment]
I have fixed this in the copy in the spreadsheet.

@lorenzoPrimi @sarathms please update the apps with the latest copy.

**Comment by agrabeli** [comment]
I have also edited the copy to edit the reference to false positives to include a link to this: https://ooni.org/support/faq/#why-do-false-positives-occur

**Comment by hellais** [comment]
I think rather than fixing them in the app copy, which is going to require re-translating everything, we should rather put a 302 redirect on the OONI Explorer website.

**Comment by hellais** [comment]
I pushed a fix for this in ooni/sysadmin so now the links to https://explorer.ooni.io/world/ go to the homepage.

We should take note as an issue, once we do the next major release, about reviewing all the URLs in the translations and doing a copy review.

**Comment by hellais** [comment]
I created an issue for the next steps related to this here: https://github.com/ooni/probe/issues/1066 and assigned it to @agrabeli.
