### ISSUE TITLE
Add OONI logo in measurement pages of OONI Probe desktop app

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1042]
The measurement pages in the OONI Probe mobile app include the OONI logo.

![Screenshot_2020-03-13-15-23-42-682](https://user-images.githubusercontent.com/8290574/76629756-194c5780-653f-11ea-9424-eb8e97c891d0.jpeg)

It would be great if the OONI logo was also added in the same way in the measurement pages of the OONI Probe desktop app, so that when people share screenshots of measurement pages, it's more clear that they include OONI data.

**Comment by hellais** [comment]
I think that we either do https://github.com/ooni/probe/issues/1047 or this one.

I believe adding both is too much.

I quite like the solution that @sarathms came up with for #1047, which makes it also functional to displaying the software version.

I suggest we close this issue in favour of #1047.

**Comment by sarathms** [comment]
Closing this because we have persistent branding in the sidebar now.
