### ISSUE TITLE
Add space between icons and metadata

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1043]
![Screenshot from 2020-03-13 14-54-25](https://user-images.githubusercontent.com/8290574/76630601-9a581e80-6540-11ea-9247-936f583a7d2b.png)

I think it would look better if there's more space between the icons and these words, so that they're not squashed together (particularly since there's so much space anyway).

**Comment by hellais** [comment]
Yes I agree some additional padding should be added, but most importantly they should be vertically aligned.

**Comment by hellais** [comment]
This is not yet fully resolved:

![Screenshot 2020-04-20 at 12 39 55](https://user-images.githubusercontent.com/424620/79743063-388b9100-8304-11ea-9639-1fa44671e1c7.png)
