### ISSUE TITLE
Edit copy in Websites card of Desktop app to reflect different features

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1048]
Currently the copy of the Websites card in the OONI Probe desktop app is identical to that included in the Websites card in the OONI Probe mobile app.

However, the Websites card has different features on both platforms, as on desktop you test all URLs in one go and you don't currently have the option for custom URL testing.

Given that we use the same spreadsheet of strings for both apps, what's the best way to address this (also in terms of translation)?

Perhaps we can have separate Websites strings for mobile and desktop?

**Comment by sarathms** [comment]
A separate string was added for desktop.
