### ISSUE TITLE
Implement MVP of automatic testing for windows

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1053]

**Comment by sarathms** [comment]
Look into uninstallation flow.

**Comment by sarathms** [comment]
On Windows, the a custom Uninstall script can be written. As [per docs](https://www.electron.build/configuration/nsis#custom-nsis-script). Here are some examples: 
https://github.com/electron-userland/electron-builder/issues/4141#issue-479212515
https://github.com/electron-userland/electron-builder/issues/3585#issue-395609495

**Comment by sarathms** [comment]
The proof of conect was implemented on Windows with Electron Fiddle using the below gist. 
https://gist.github.com/sarathms/b5bf3dbaee58080086ffa7a7045dec8b

We will be implementing something similar in a cross platform manner.
