### ISSUE TITLE
Test Countly to see if we can use the push notification to send OONI Run links

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1055]
Try the integration of Countly to see if we can use the push notification to send OONI Run links (using the free tier, and if not, what are the limitations of that)

**Comment by lorenzoPrimi** [comment]
Update: we had an issue with the backend that was resolved with: https://github.com/Countly/countly-server/issues/1115
I'm now going to try all the features

**Comment by lorenzoPrimi** [comment]
Tested and working, but there is an issue I'll document here

**Comment by lorenzoPrimi** [comment]
Doing more tests I discovere that the Countly JSON is different from a notification sent from the Firebase console.
There are two types of messages in FCM (Firebase Cloud Messaging):

1. Display Messages: These messages trigger the `onMessageReceived()` callback only when your app is in foreground
2. Data Messages: Theses messages trigger the `onMessageReceived()` callback even if your app is in foreground/background/killed

You can send a data message by not adding JSON key notification (see below)
Ref: https://stackoverflow.com/questions/37711082/how-to-handle-notification-when-app-in-background-in-firebase

Typical FCM message
```
{
  "to": "FCM registration ID",
  "notification": {
    "title" : "title",
    "body"  : "body text",
    "icon"  : "ic_notification",
    "click_action" : "OPEN_ACTIVITY_1"
   },
   "data": {
     "someData"  : "This is some data",
     "someData2" : "etc"
   }
}
```
Countly message (from https://support.count.ly/hc/en-us/articles/360037754031-Android-SDK#setting-up-push-notifications)
```
{
	collapse_key: “collapse_key”, // if present
	time_to_live: 123,
	data: {
		message: “message string”, // if present
		title: “title string”, // if present
		sound: “sound string”, // if present
		badge: 123, // if present
		c.i: “message id string”,
		c.l: “http://message-wide-url”, // if present
		c.m: “http://rich.media.url.jpg”, // if present
		c.s: “true”, // if sound & message absent
		c.b: [ // if present
			{t: “Button 1 title”, l: “http://button.1.url”},
			{t: “Button 2 title”, l: “http://button.2.url”} // if present
		],
		// any other data properties if present
	}
}
```
When receiving a notification with countly a notification is never displayed, the `onMessageReceived()` method is always called and the `data` is handled in there, like in their code example: 

- App background : Show notification banner
- App foreground : Show modal in the app
- Do other actions ...

**Comment by lorenzoPrimi** [comment]
Countly SDK also exposes methods `CountlyPush.displayNotification()` & `CountlyPush.displayDialog()` in case you only need Notifications and don't want Dialog or vice versa.

So we can even disable the modal when the app is in foreground. (It doesn't work anyway)

**Comment by lorenzoPrimi** [comment]
Apparently as the countly notification are of Data type all the handling is in the app, an example algorithm would be:
- The app receives a notification 
- The data is handled in `onMessageReceived()`
- A notification  banner or modal is generated
- The user will click open in the modal or on the notification banner  
- The app will perform an action
