### ISSUE TITLE
Investigate if the countly community edition is enough or if we need to consider the enterprise version

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1057]

**Comment by lorenzoPrimi** [comment]
First analisys on Countly:
The push notification service has (almost) everything we need: possibility to send a json, possibility to send a deeplink (I don't know work with OONI Run links, it has to be tested) and also data-only messages.

The only missing feature is possibility to target by country, as we have the `cc` data in Countly, we can target by location and radius but it's not what we want.

So by now the community edition is enough but we will need to write ourselves a plugin to target notificationn based by country

Ref:
https://support.count.ly/hc/en-us/articles/360037681532-countly-app-users-appID-

**Comment by lorenzoPrimi** [comment]
User profiles are available only in the enterprise edition, in case we need them (I don't think so)
https://support.count.ly/hc/en-us/articles/360037630571-User-profiles

**Comment by lorenzoPrimi** [comment]
To target user by country we need User Profile
https://support.count.ly/hc/en-us/community/posts/360059114171-Target-push-by-country

So yes, we can target user by country code but only with Enterprise

**Comment by hellais** [comment]
We got a quote for the enterprise edition and it's a bit out of our budget.

For the time being we are going to see if we can do with the community edition and rather try to self host it.

**Comment by hellais** [comment]
The next steps for this are to create the countly plugin, which is documented here: ooni/backend#378.
