### ISSUE TITLE
Create a beta branch with support for automatic daily testing

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1059]
Beta branch of the app that includes automatic daily testing => the measurements would go through the test infrastructure (“parallel OONI-verse”).

**Comment by agrabeli** [comment]
@hellais @lorenzoPrimi I asked our partners if having OONI Probe run automatically on a regular basis from an old Android phone would be a convenient or desirable option. While many said that yes, that could work, others proposed the following alternatives for running automatic, regular OONI Probe tests:

1. Home Assistant: https://www.home-assistant.io/

2. Apple devices

3. If we got a stable version of probe-cli, then install OS like Raspbian or Ubuntu sever on raspberry pi, then install probe-cli (this requires doing this first: https://github.com/ooni/probe/issues/807).

**Comment by lorenzoPrimi** [comment]
Basic app that execute web_connectivity at a scheduled time in background (and send a local notification afterwards)

[OONIProbe-2.3.2-automated_testing.apk.zip](https://github.com/ooni/probe/files/4426086/OONIProbe-2.3.2-automated_testing.apk.zip)

**Comment by hellais** [comment]
This has been done: https://github.com/ooni/probe-android/tree/automated_testing
