### ISSUE TITLE
Generate .deb and .rpm packages for ooniprobe CLI

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/probe#1061]
Generate .deb and .rpm for ooniprobe CLI using Travis/Circle/GH actions. Push packages into dedicated repos on bintray

- Pull python script  https://github.com/ooni/pipeline/blob/master/.circleci/debops-ci in the build
- Adapt script to this use-case
- Create bintray repos: one for PRs and one for master
- Detect git tags if needed    
- Install /etc conf file     
- Create systemd timer     
- Create systemd sandbox     
- Use shared unix group
- Capture logs
- Create CLI command/wrapper to show probe status
- Document usage in the package description

**Comment by hellais** [comment]
We now have debian packages available for download with the instructions at this URL: https://ooni.org/install/cli/ubuntu-debian
