### ISSUE TITLE
Add support for native sharing capability in OONI Probe

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1070]
Currently most people are sharing OONI Probe measurements by taking screenshots of their phone which is cool, but not the best way to share an OONI measurement.

For example we find ourselves often times struggling to identify which is the original measurement (or measurements) that are related to a screenshot we see on twitter or elsewhere.

While we can't prevent entirely people from taking screenshots, they are bound to do that, I think we can at least have a recommended way of sharing data with a clear "share" button.

This is now possible in light of the fact that our data processing pipeline is much faster making a measurement visible in OONI Explorer within seconds from the test run having finished.

I think as part of this we should consider the following aspects:
1. How a user is going to share an individual measurement (this is showhow easy, it's just a matter of making the button more visible and clear in the measurement page)
2. How the OONI Explorer measurement preview appears on social media, this is related to: https://github.com/ooni/explorer/issues/202
3. How a user is going to share a set of measurements. This is currently a missing functionality which we need to evalute

Perhaps we can start with the first few items by doing some mockups and iterating on that.

**Comment by hellais** [comment]
This should become an epic. I am converting it to that.

**Comment by lorenzoPrimi** [comment]
In the app the native share of explorer link as been implemented in
https://github.com/ooni/probe/issues/1176

**Comment by hellais** [comment]
This is now supported in the apps. This becomes just a mater of making the button more discoverable, see: https://github.com/ooni/probe/issues/1160
