### ISSUE TITLE
Upload all measurements button missing from result list view

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1081]
OONI Probe Version: 2.3.0 on iOS

When a measurement fails to upload, the top level views (the result list and measurement list), should display an "Upload all measurements" toast, but instead none is visible.

The icon indicating there are not uploaded measurements is also missing from the view.

![IMG_6635](https://user-images.githubusercontent.com/424620/78368182-834aa080-75c3-11ea-9898-3d1f4da7425b.PNG)

![IMG_6634](https://user-images.githubusercontent.com/424620/78368178-8180dd00-75c3-11ea-9203-02e4be95c56e.PNG)
![IMG_6636](https://user-images.githubusercontent.com/424620/78368187-847bcd80-75c3-11ea-97f2-2dccb06537fb.PNG)

**Comment by hellais** [comment]
I was not able to reproduce the issue on Android.

**Comment by lorenzoPrimi** [comment]
I was not able to reproduce it and codewise seems ok (The foother is the same view in every screen)
I need more information

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-14 at 09.14.43.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/86f6dcc1-181d-40a1-8509-0b5d64733791)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-14 at 09.14.45.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/595ebec0-d645-4d88-b50b-11427587e0fb)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-14 at 09.14.47.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/833a7a46-88c9-481b-a659-bac376541404)

**Comment by lorenzoPrimi** [comment]
Can you paste the logs

**Comment by lorenzoPrimi** [comment]
We weren't able to reproduce this behaviour.
