### ISSUE TITLE
Translations for OONI Probe desktop for public launch

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1083]
We should ensure the translations fo the OONI Probe Desktop app are ready for the stable launch.

Things to do are:

* [x] Ensure the copy for the OONI Probe Desktop app is final (cc @agrabeli)
* [x] Upload the final copy to transifex (@sarathms)
* [x] Reach out to translators asking them to reach 100% on the required translations by the launch deadline
* [x] Update the translations into the app
* [x] Circulate a preview build with the translations for translators to test

**Comment by hellais** [comment]
This issue is also related: https://github.com/ooni/probe/issues/1072

**Comment by agrabeli** [comment]
@hellais The OONI Probe desktop app copy is finalized, and it has already been uploaded to transifex. 

The translations are 100% complete (and ready to use) for 9 languages, while an additional 5 languages are just missing the translation of 1 string (i.e. the latest string added with regards to the new Websites card copy on desktop). I'll ping the Localization Lab now to coordinate on the translation of this missing string.

**Comment by agrabeli** [comment]
@sarathms please ping me when/if there's a new release candidate to share with translators.

**Comment by agrabeli** [comment]
Currently the following 9 languages are 100% translated and ready for use:

1. Chinese
2. Persian
3. French
4. Italian
5. German
6. Greek
7. Slovak
8. Portuguese
9. Thai

While the following 5 languages are just missing the translation of 1 string (I have reached out to the Localization Lab to coordinate on this):

1. Arabic
2. Spanish
3. Catalan
4. Russian
5. Turkish

**Comment by agrabeli** [comment]
In general, the priority languages include:

1. Arabic
2. Persian/Farsi
3. Chinese
4. Spanish
5. French
6. Russian
7. Turkish

I would add Indonesian, Hindi, Bengali, Ahmaric (because Ethiopia has experienced a lot of internet censorship), Thai, and Vietnamese.

**Comment by hellais** [comment]
Thanks for this @agrabeli ! I have added them to the Readme of our translations repo so we don't loose track of it: https://github.com/ooni/translations/blob/master/Readme.md#language-priorities.

**Comment by hellais** [comment]
We have done this. Launch has been moved out of this.
