### ISSUE TITLE
Improve discoverability of measurements inside the OONI Probe mobile app

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1084]
Since the launch of the revamped OONI Probe mobile app, I have noticed that many community members share screenshots on social media of the main Test Results page, rather than of individual measurement pages (as they used to). 

This has made me suspect that perhaps it's not clear that the displayed results in the Test Results page are tap-able, and that they can eventually access individual measurements pertaining to each tested website.

Yesterday during a call with a community member (who has used OONI Probe for several years -- though not regularly), they were surprised when I pointed them to the individual measurement pages, confirming my aforementioned suspicion. 

I think it's great that we're presenting information in a sort of hierarchy and we're definitely doing a better job (in comparison to the previous app) in refraining from overwhelming users with too much technical information at once. 

That said, I think there may be the risk that we're nesting information a bit too much, and that we need to work more on finding a balance (UX-wise) between not overwhelming users with too much technical information at once and ensuring that information is easily discover-able (for those interested). 

I'm not sure what the solution from a UX perspective could be. I just wanted to flag this potential issue and highlight that perhaps we can start brainstorming on ways to make the measurements more obvious or easily discoverable inside the app.

**Comment by hellais** [comment]
We are going to measure this using events and then evaluate how much this is in fact a problem.

@lorenzoPrimi can you share the events which we might use to understand how many people are clicking on a measurement row?

**Comment by hellais** [comment]
I see now that inside of issue https://github.com/ooni/probe/issues/1277 @lorenzoPrimi says it's not possible to do a funnel with "Funnel from test results until the test details.".

@lorenzoPrimi can we still just count the absolute number and compare between the tabs?

**Comment by lorenzoPrimi** [comment]
We can't make a funnel with countly basic but we can measure every click event.
The fact that is not clear is how we would have an answer to the question about "how many people opens the measurement details" from the absolute numbers.

**Comment by agrabeli** [comment]
@hellais @lorenzoPrimi perhaps this potential problem could be "solved" by **adding an arrow on each measurement row** (in the Test Results listing), clearly indicating that they can tap on each measurement to view the measurement page?

**Comment by hellais** [comment]
> The fact that is not clear is how we would have an answer to the question about "how many people opens the measurement details" from the absolute numbers.

What we can do is count the events:
* Test results page opened
* Test row opened
* Test details opened

**Comment by lorenzoPrimi** [comment]
> What we can do is count the events:
> 
> * Test results page opened
> * Test row opened
> * Test details opened

Still wouldn't solve the problem, as I can open the test result page once, then navigate to 50 different test details and you could open test result and zero test details.
This gives us data of
- 2 test result page opened
- 50 test details page opened

**Comment by hellais** [comment]
I see what you mean, but still if we notice that the absolute number of opened test details page is very low, it gives us an indication it's not being used much.

Maybe we can do an experiment with only one of the tests, for example the performance test which is the one which is run the most and has the least number of rows so we can minimise the noise introduced in the data.

**Comment by lorenzoPrimi** [comment]
Should I add these events in this release?
Apparently we already have a view counters but they take the title of the activity
https://countly.ooni.io/dashboard#/5ea6cf6ad7b7950499a822db/analytics/views
and it it's localized they don't add up together

**Comment by hellais** [comment]
> Should I add these events in this release?

If possible that would be very helpful.

**Comment by hellais** [comment]
We are going to measure this and then evaluate further. Adding a new card to the next sprint: https://github.com/ooni/probe/issues/1288
