### ISSUE TITLE
Add language selector to OONI Probe Desktop

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1088]
Currently the app will use whatever is the OS language. It should be possible for users to override this with a settings selector.

**Comment by pappasadrian** [comment]
If I may add to this, being able to switch between languages also helps the translators quite a bit :)

**Comment by sarathms** [comment]
We have working language switcher coming up in ooni/probe-desktop#164

![Screenshot from 2020-07-24 12-14-27.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/d8342b6d-b92c-4cd7-9cf3-d5eb358536a9)

Just need to find a good way to map the codes to localized names. @hellais I wonder if it is better to include a `Language.Name` string in the copy for translators to give us names for the dropdown. Is there another solution?

**Comment by hellais** [comment]
You should have the localized language names as part of formatjs (react-intl): https://formatjs.io/docs/react-intl/components#formatteddisplayname.

We should show the available languages in the localized language name (ex. it -> Italiano).

**Comment by hellais** [comment]
This is done inside of the settings PR: https://github.com/ooni/probe-desktop/pull/164
