### ISSUE TITLE
Implement run all tests

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1093]
This issue is about implementing https://sketch.cloud/s/8vqJq/v/g119vz/ inside of probe-mobile.

Based on this specification ooni/probe#826
And probably this interface ooni/probe#870

**Comment by hellais** [comment]
Related: https://github.com/ooni/probe/issues/1094

**Comment by lorenzoPrimi** [comment]
@hellais I guess these are different issue. This is about implemented "Run all" in a technology point of view and that other one is an UX modification card. Reopening
