### ISSUE TITLE
Remove country code opt-out option in the app settings

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1105]
Currently the OONI Probe apps include a setting that enables users to opt-out of sharing their country code.

I propose that we remove this option from the apps, as measurements that do *not* include the country code cannot be used in any way.

**Comment by lorenzoPrimi** [comment]
At the moment we have an alert that appears every time we want to disable that setting:
`
This information (e.g. IT for Italy) is required to identify which country the measurements are collected from. Are you sure you want to disable this option?`

**Comment by hellais** [comment]
Yeah, we should in fact remove the option all-together and only offer people to opt out of measurement submission all-together.
