### ISSUE TITLE
Revisit the way in which we show performance results

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1106]
We should revisit the way in which we show performance results. We should consider adding plots with interim results such as the progress of speed during an experiment.

This needs to be a broader conversation. The starting point is however that currently we are exposing in the mobile apps and in explorer metrics that ndt7 does not provide.

On this note, this is how a ndt4/ndt5 "advanced" result looks like:

```JSON
{
  "avg_rtt": 22.386138613861387,
  "congestion_limited": 0,
  "fast_retran": null,
  "max_rtt": 34,
  "min_rtt": 19,
  "mss": 1440,
  "out_of_order": 0,
  "packet_loss": 0,
  "receiver_limited": 0,
  "sender_limited": 0,
  "timeouts": 0
}
```

This is how a ndt7 "summary" result looks like:

```JSON
{
  "avg_rtt": 41.085,
  "download": 83885.61215918642,
  "mss": 1448,
  "max_rtt": 86.452,
  "min_rtt": 18.471,
  "ping": 18.471,
  "retransmit_rate": 0,
  "upload": 19788.998726391314
}
```

The following table summarises the changes

| ndt4/ndt5 name     | ndt7 replacement | comment       |
| ------------------ | ---------------- | ------------- |
| avg_rtt            | avg_rtt          |               |
| congestion_limited | N/A              |               |
| fast_retran        | N/A              |               |
| max_rtt            | max_rtt          | estimate      |
| min_rtt            | min_rtt          |               |
| mss                | mss              |               |
| out_of_order       | N/A              |               |
| packet_loss        | retransmit_rate  | similar       |
| receiver_limited   | N/A              |               |
| sender_limited     | N/A              |               |
| timeouts           | N/A              |               |

So, the we need to make sure that we are not showing variables that we cannot show because they are not collected anymore. I will open more detailed issues wrt that.

**Comment by hellais** [comment]
We don't want to do this in the app, we should rather do this in OONI Explorer, but add a link to the country inside the app.
