### ISSUE TITLE
mobile: remove/update obsolete NDT fields

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1107]
The following screen lists what "advanced" variables we're showing that they should either be updated or removed. The parent discussion is https://github.com/ooni/probe/issues/1106.

![WhatsApp Image 2020-04-15 at 16 31 49](https://user-images.githubusercontent.com/337298/79349812-fbf01c00-7f36-11ea-89ae-0658d8a99a42.jpeg)

Specifically:

- [x] update packet loss to be retransmit rate
- [x] out of order is gone and we should not be showing it
- [x] max ping is now an estimate so maybe we tell it's an estimate or we remove it
- [x] timeout is gone and we should not be showing it

As @hellais mentioned, in https://github.com/ooni/probe/issues/1106 we will ask the more broad question, while here we're mostly concerned with fixing the view.

**Comment by lorenzoPrimi** [comment]
Strings to edit:
"packet loss" => "retransmit rate"
"Max ping" => "Max ping estimate"

Strings to remove:
TestResults.Details.Performance.NDT.OutOfOrder
TestResults.Details.Performance.NDT.Timeouts
