### ISSUE TITLE
Verify if the share network information settings is respected for wifi or mobile annotation metadata

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1112]
When you run an OONI Probe test on mobile, part of the metadata includes if the test was run on a mobile or wifi network.

We should check if we are removing this metadata in the event of a user opting out of network information and if not evaluate if we should change that behaviour.

cc @bassosimone @agrabeli

**Comment by lorenzoPrimi** [comment]
At the moment `network_type` is sent as annotation always, it's separated from `probe_cc`, `probe_asn` and the other measurement kit data.
In the case of mk is mk itself to know if sending these data based on the preference of the app, in the case of `network_type` the annotation is always added
