### ISSUE TITLE
About Window opens up at app start up

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1122]
## Expected Behavior
About window should be opened only when launched from the menu.

## Actual Behavior
About window opens up when the app is launched. This happens because every call to get a reference to the About window in turn launches the window itself.

## Steps to Reproduce the Problem

  1. Launch app. 

## Specifications

  - Version: 3.0.0
  - Platform: MacOS, Windows

**Comment by hellais** [comment]
This has been fixed.
