### ISSUE TITLE
Add ability to choose which website categories to test on the OONI Desktop app

### ISSUE THREAD

**Issue by pappasadrian** [ooni/probe#1132]
Basically, it'd be nice to have the same ability as in the mobile app. This will allow users to narrow down their contribution to specific areas where they suspect might be a problem, while at the same time making the testing shorter than the current hours long full list testing. 
Also, as described in the risk assessment document ( https://ooni.org/about/risks/ ), which types of sites are tested is considered a risk factor, so it'd be good to give the user control over it.

**Comment by hellais** [comment]
Yeah this is planned and we are tracking it in this issue already: https://github.com/ooni/probe/issues/1022
