### ISSUE TITLE
The about window should not open on startup

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1134]
Currently when I start the OONI Probe app, by default two windows are opened, the main one and the about window.

The about window was originally opened to expose the reset OONI Home features while testing, but we should now only show it when an update is available and we are downloading it.

By default it should not be opened and only open when the user directly opens it.

**Comment by sarathms** [comment]
This is not happening on Windows or Mac anymore.

**Comment by bassosimone** [comment]
Yup. I am going to close this issue. Thanks for working on it.
