### ISSUE TITLE
Remove hard-coding of title casing in OONI Probe apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1136]
A translator has requested that we refrain from hard-coding title casing in the OONI Probe apps. Specifically, they say:

> "On the second onboarding screen (see below), hard-coded title casing is applied to
> "Je comprends" (I understand) which is wrong. Title casing might be applied in English but should never be hard-coded in the translation UIs, as different languages have different typographical rules. Casing should always be used as is is being displayed in the translations. Even all caps should appear in the source string for the same reason. In this case, it looks quite out of place."

![2020-04-24 Title casing and English on the 2nd onboarding screen](https://user-images.githubusercontent.com/8290574/80992235-81c9fd80-8e39-11ea-87ea-ebfb4e855a20.png)

I think they make a good point. It would be great if translators have the flexibility to decide if words should be capitalized or not, depending on what makes sense in the local language.

**Comment by lorenzoPrimi** [comment]
This doesn't understand neither in OONI Probe iOS, Android nor Desktop, closing.
