### ISSUE TITLE
Add support for translating "processing input" when tests run

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1142]
"Processing input" is being displayed in English in the localized UI and needs to be pushed to Transifex for translation.

![2020-04-24 Processing input appears in English in the localized UI](https://user-images.githubusercontent.com/8290574/80996126-9b6e4380-8e3f-11ea-915d-db1eec4dfef5.png)

**Comment by lorenzoPrimi** [comment]
I don't think that is an app string, rather it's a log message from mk. @bassosimone

**Comment by lorenzoPrimi** [comment]
I've seen that @hellais already commented about this another issue https://github.com/ooni/probe/issues/1150#issuecomment-623955107
