### ISSUE TITLE
Add space between "WhatsApp Web" and "Registration" in WhatsApp test results

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1159]
It would be nice to create space between "WhatsApp Web" and "Registration", so that they're not squashed together and easier to read. 

See:

![Screenshot_2020-05-18-14-50-10-133](https://user-images.githubusercontent.com/8290574/82222903-3841de00-9922-11ea-96b8-99fce5fa8619.jpeg)

**Comment by lorenzoPrimi** [comment]
3 column when dps >= 400. 2 columns when < 400

**Comment by hellais** [comment]
Some notes on this:

https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins
https://material.io/design/layout/pixel-density.html#pixel-density-on-android

So basically if you have a screen with density of 160, 240 px == 240 dps
