### ISSUE TITLE
Localize "hard reset" and "debug information" in About OONI Probe window on desktop

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1172]
A community member reported that on Windows (OONI Probe desktop 3.0.1), the following is in English in the **About OONI Probe** window:

_Hard reset
Debug information_

This should, instead, be in French (and other translations). This may be an issue across translations.

See: 

![2020-05-13 English in the localized UI on  3 0 1 for Windows](https://user-images.githubusercontent.com/8290574/83040405-81d7aa80-a03f-11ea-92dd-cd6d43e0b01f.png)

**Comment by hellais** [comment]
This is debug level information. We don't have any plans to localise this.

The hard reset button should eventually get dropped though.

I am closing this issue as wontfix.
