### ISSUE TITLE
Update to the latest version of probe-cli/probe-engine

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1178]
This has been recommended by @stephen-soltesz because soon m-lab is going to phase out clients that are not using access tokens, therefore, by releasing w/ the latest probe-engine we will help @m-lab rolling out this improvement more quickly and we'll enjoy more capacity b/c clients hammering m-lab will be unable to run.

I am the person responsible of making this happen, but I also assigned @hellais and @sarathms so they know that we have this issue and they can more easily follow/track the work being done.

**Comment by bassosimone** [comment]
@hellais this is the PR upgrading probe-engine: https://github.com/ooni/probe-cli/pull/133

**Comment by bassosimone** [comment]
Today we released probe-cli@v3.0.1 which uses probe-engine@v0.11.0, which uses locatev2 and probe-desktop@v3.0.2 including probe-cli@v3.0.1. Also the Android mobile app seems OK.

This counts as progress.

**Comment by bassosimone** [comment]
@hellais we probably want to include ooni/probe-engine@v0.11.0 in the next probe-cli because this also allows us to pull the updated MaxMind DB. Maybe we can chat about this next Monday?

**Comment by bassosimone** [comment]
Scheduled to be discussed in the next 1:1 with @hellais.

**Comment by bassosimone** [comment]
We will ship the next version of probe-cli along with probe-desktop this week.

**Comment by bassosimone** [comment]
This issue needs to be reconsidered. We need to strip adding `stun_reachability` to probe-cli, then we need to circle back and merge into master and tag the next probe-cli.

**Comment by bassosimone** [comment]
Effort is actually slightly higher because I need to revert part of the diff and bless new CLI. So bumped this to effort/S and 5 points. Balance of points should be OK because of other postponed issues.

**Comment by bassosimone** [comment]
This is mostly done. It remains to cut a release for probe-cli, which I'll do tomorrow.

**Comment by bassosimone** [comment]
We want to have an updated ASN database, so:

* https://github.com/ooni/probe-engine/pull/722

* https://github.com/ooni/probe-engine/commit/1f2ba9751cf63a5fc42c96e63720cae30fa5483a

* https://github.com/ooni/probe-cli/pull/139

**Comment by bassosimone** [comment]
Released the CLI: https://github.com/ooni/probe-cli/releases/tag/v3.0.2

The next step is now to use this with probe-desktop

**Comment by bassosimone** [comment]
We're now updating probe-desktop: https://github.com/ooni/probe-desktop/pull/152

**Comment by bassosimone** [comment]
The original reason why we opened this issue was to make sure our users had migrated to a version of the code base using m-lab's locatev2 services. Today we looked into the volume of OONI generated measurements per day together with @stephen-soltesz. It seems 2-3% of OONI users are still using the old locatev1 services. They are probably the users that we also see in OONI monitoring as using older versions of OONI (e.g. desktop release candidates). It probably can't be helped much.

During its lifecycle, this issue also changed a bit its scope and started encompassing the need to have a new release using a version of our ASN database that has nice names. Today I blessed a version of probe-engine (v0.13.1) that contains that and prodded @sarathms and @lorenzoPrimi to update to this version of the database. I am going to drag this issue along to the next sprint.

**Comment by bassosimone** [comment]
Adding also @lorenzoPrimi: we still need to update the mobile apps.

The version to be used is listed here: https://github.com/ooni/probe-engine/releases/tag/v0.13.1

**Comment by lorenzoPrimi** [comment]
An apk and a testflight with latest version has been released today

**Comment by bassosimone** [comment]
We're done!
