### ISSUE TITLE
Evaluate how to manage privacy in countly

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1182]
Based on the countly support page we need to check consent for the different features:
https://support.count.ly/hc/en-us/articles/360037753291-SDK-development-guide#gdpr-compatability

One feature is `Push` and will go under a dedicated menu,
another one is `Crash` and  it's already present in the app, although we might want to move it into a new tab called `Privacy` or `Data choices` together with:
sessions, views, events (present now)
scrolls, clicks, forms, attribution (to activate in the future)

**Comment by lorenzoPrimi** [comment]
First round: I tried 30 random apps
- 2 of them had a "Collect Analytics" setting (well hidden), 
- One of them had the send crash setting (iTunes and gPlay collect them anyway)
- All of them (with push) had a push notification setting 


The ideal solution for me would be:
- `Push` inside `Push notification` settings
- `Send Crash` moved from `Advanced` to `Privacy` settings
- `Anonymous app usage` (that includes sessions, views, events) inside `Privacy` settings on by default

**Comment by lorenzoPrimi** [comment]
Add footer in the Privacy settings screen

**Comment by hellais** [comment]
TODO still is to get input on GDPR compliance from a privacy lawyer

**Comment by hellais** [comment]
To evaluate how we should go about doing this I used as a reference 3 apps that I think would be appealing to our target audience and have similar sensibilities WRT privacy: Mozilla Firefox, Brave Browser, Speedtest by Ookla.

Mozilla Firefox 

![FirefoxPrivacy.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/f8284561-627b-4620-8e61-9e7c54260da9)

They don't mention the fact that they collect analytics about app usage (they call it Firefox Health Report) or crash reports, which is enabled by default, but the user can opt out in the privacy settings.

Brave

![BravePrivacy.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/23c1920f-0b00-49d1-895e-32f435d93c9e)

They don't mention this data collection in the onboarding and although they speak about being able to opt-out of submitting this (which is enabled by default) on their website, no such setting can be found in the app settings.
This might be a bug in the mobile app.

Speedtest

![SpeedtestPrivacy.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/
5a88463b-1fe9-4129-990b-fef7bc2ca38d)

They mention both crash report logging and app analytics in the onboarding and offer the ability to opt out there directly. It's also possible to opt out in the settings.


In light of this I think we should have both analytics and crash reporting enabled by default, mention it in the onboarding and offer the ability to easily opt-out in the privacy settings.

**Comment by hellais** [comment]
I think we should go ahead with updating our privacy policy, but not block on getting a lawyer input. It seems like country is compliant with GDPR and probably the only thing we need to implement in the app is some screen that shows the countly ID to implement the right to be forgotten.

Useful links are:

https://blog.count.ly/countly-the-gdpr-how-worlds-leading-mobile-and-web-analytics-platform-can-help-organizations-5015042fab27

https://www.mobiloud.com/blog/gdpr-compliant-mobile-app/

**Comment by hellais** [comment]
I have documented all the next steps for this as separate dedicated issues:

* https://github.com/ooni/ooni.org/issues/547
* https://github.com/ooni/probe/issues/1211#issuecomment-649401030

I think this issue can now be closed.

**Comment by lorenzoPrimi** [comment]
@hellais should we create a "Privacy" item in settings or leave everything under "Advanced"?

**Comment by hellais** [comment]
I filed an issue for that so it's not lost as this is a closed issue: https://github.com/ooni/probe/issues/1217

**Comment by agrabeli** [comment]
@lorenzoPrimi @hellais I think it makes sense to have a Privacy tab, so that it's potentially clearer to users that that's where they have to go in order to opt out of things like analytics (also, "Advanced" may sound overwhelming and many users may not tap it at all). However, would the Privacy tab only include "app usage statistics" or are there also other settings (related to opt out) that would go there?

**Comment by lorenzoPrimi** [comment]
@agrabeli can you move your comment in https://github.com/ooni/probe/issues/1217 so we can stimulate the discussion?
