### ISSUE TITLE
Come up with a better way to make Probe Desktop releases

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1192]
Since the last probe-desktop release, I lost the ability to make OONI Probe desktop builds from macOS for windows.

This means that we had to split doing the release between me and @sarathms .

We should come up with a better way of making the release for windows, mac and linux.

Options to evaluate include:
- Setting up a build VM
- Integration with some CI system
- Resolving the issue with electron-builder on macOS catalina
- ??

**Comment by hellais** [comment]
Some progress was done on researching this topic, mostly in understanding the security implications of storing keys for signing the releases on a live server or on CI infrastructure.

The tl;dr is that on macOS it's possible and reasonable to revoke keys, because of the notarization process, while on windows it's not so straightforward.

WRT to windows code signing here is some more information:

1. Technicaly it is possible to revoke code signing certificates. According to: https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)?redirectedfrom=MSDN, the section “Revocation” states:
 > If a private signing key is compromised, the publisher must contact the issuing CA and have the certificate revoked. Revocation invalidates the certificate and adds it to the CRL.

2. However, though it’s technically possible, I could not find a way to do it from the web interface of the CA we are using (which is ssl.com)

Other CAs do however provide ways to revoke certificates from their web interface, for example: https://knowledge.digicert.com/solution/SO982.html.

In doing this research I also noticed that our code signing certificate expires Oct 28, 2020. From what I understood reading online, it’s not possible to renew the certificate, but the renewal process is basically just getting a new one issued.

In light of this, we might want to consider switching to another CA

3. It appears that although there is technically a way to revoke certificates, it doesn’t really work super well, see: https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-kim.pdf
Overall storing code signing keys in a CI or on a live server where we are signing code automatically makes me a little bit nervous and I think it would be better if we found some solution that did not require us having such important keys on live machines.
The section of the “Code-signing best practices”, specifically addresses the problem of automation, see the screenshot in here: https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653556(v=vs.85)?redirectedfrom=MSDN
That document also outlines three possible approaches to code signing which they divide into:
Offline manual signing
Manual submission with automated signing
Automated submission from a build computer with automated signing

**Comment by sarathms** [comment]
Thanks for sharing `best_practices.doc`. From what I understand, the three topologies described in the document don't directly suit out needs and/or capacities. Maybe a modified version of the '**online signing with manual approval**' should be implemented which uses a build server but not a web frontend for approval.

I am unable to visualize the full setup because it is unclear how to deploy a build server running `macos`?

**Comment by bassosimone** [comment]
As mentioned in https://github.com/ooni/backend/issues/449#issuecomment-698463529, I was really not able to work on this issue for this sprint, and no-one else was actually able. I think I was the person being mostly on call here, so I am going to steal the points from this issue to cover the unexpected work I did tending to the breaking pipeline. Removing this issue from sprint.

**Comment by sarathms** [comment]
As part of preparing for the [3.0.4 release](https://github.com/ooni/probe-desktop/pull/180), @bassosimone proposed we make use of the `pre-release` feature of github releases, also supported by `electron-builder`.  The workflow then involves publishing the prerelease builds from workstations/build-server/CI and then flipping off the `This is a pre-release` flag off when it is ready to be published.

**Comment by bassosimone** [comment]
After upgrading to Big Sur, I have also lost the possibility of making Desktop releases. I don't actually remember the specific failure, but my recollection is that it was during the notarization phase of the build.

**Comment by sarathms** [comment]
- [ ] Evaluate the option to run code signing in a self-hosted job runner within a github CI workflow. [Relevant documentation](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow)

**Comment by hellais** [comment]
We ended up solving this by getting a mac computer for @sarathms. I believe no further action needs to be taken on this issue.
