### ISSUE TITLE
Discuss the experimental nettest group

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1197]
Follow-up from https://github.com/ooni/probe/issues/1190

**Comment by bassosimone** [comment]
We could not work on this topic in Sprint 24. Let's see whether we'll managed to do that in Sprint 25.

**Comment by hellais** [comment]
I think we should add an advanced setting which is called: "Run experimental tests". We can promote it via push notifications (@lorenzoPrimi is it possible with a mobile deep link to send them to that specific setting page when they tap on the notification).

Inside of the advanced setting we can add a text at the bottom saying what this means "When you enable experimental tests we will be running, when you tap the run button, tests which don't yet have a user interface. You can learn more about experimental tests we run here: https://github.com/ooni/spec/nettests".

**Comment by lorenzoPrimi** [comment]
It's possible but will need some code in the app, we didn't inserted any code to open a specific activity.

**Comment by bassosimone** [comment]
Renamed: we have a meeting about this topic near the end of the week. We recently received community interest with respect to an experimental nettest group including the sni_blocking experiment with possibly a custom test list. I am going to explain this use case in the upcoming meating with the rest of the team and we're then going to spec out a specific issue for that.

**Comment by bassosimone** [comment]
This will happen today in a few hours.

**Comment by hellais** [comment]
We had a discussion about this and came up with a set of concrete next steps. They are documented in the relevant doc in our team drive: https://docs.google.com/document/d/1w7vq34oiwi7HNjZlPoA_XUMYQfZIxl61RgQ_ux6bK8I/edit
