### ISSUE TITLE
Implement countly in Android

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1208]
Implement countly for push notification in android and in particular
- [x]  Handle Ooni run links
- [x] Registration with backend
- [ ] Settings screen And privacy https://github.com/ooni/probe/issues/1182
- [ ] Ask old user to enable analytics https://github.com/ooni/probe/issues/1211#issuecomment-649401030

**Comment by agrabeli** [comment]
This is done. It needs to be reviewed before it's merged.

**Comment by lorenzoPrimi** [comment]
Countly report Android
When sending an url like
https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Frun.ooni.io%2F%22%5D%7D&mv=1.2.0
If the user taps on the notification it ask to open a browser (then he has to press run and will open OONI Probe)

![Screenshot_2020-07-27-14-02-23-619_android.jpg](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/6f0f0239-93f2-4001-8cfd-5786952b74d7)

Instead if the url sent is like
ooni://nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Frun.ooni.io%2F%22%5D%7D&mv=1.2.0
From the notification it will trigger directly the OONI Probe app (In my case I have the choose because I have ooni dev and prod)

![Screenshot_2020-07-27-14-02-56-602_android.jpg](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/9ccd806d-783b-425f-a228-640e88be27be)
