### ISSUE TITLE
Ask notification permission in the app

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1210]
As discussed in https://github.com/ooni/probe/issues/813
All the findings are in this doc
https://docs.google.com/document/d/1x1jMjMq4-e8Xb4USegBSUV6V_cpNUWb2GwfBE5jhAV4/edit#

copy: https://docs.google.com/document/d/14RxWiI2tCl8LkRpVt87eF0y0N1wF7_f4GKqQqBjq6_k/edit#

**Comment by agrabeli** [comment]
@lorenzoPrimi what are we supposed to do for this ticket? Is this the copy that I shared with you privately for the title and description of the push notifications channel on Android?

**Comment by agrabeli** [comment]
@lorenzoPrimi I think the pop-up window should have different copy than that which is included in the Notifications section inside the app. 

Because (to my understanding) the Notifications channel will live in the Android app in general, it can have the copy that I previously shared ("We will notify you to coordinate on OONI Probe testing when we hear of censorship events in your country. We may also share news and updates from the OONI-verse."), which is a bit more generic.

In the pop-up window, where our goal is to encourage users to sign-up for push notifications, I think we need more "exciting" copy, such as that which is proposed (presumably by @hellais) in the mock-up that you share.

So for this pop-up, I'd recommend the following:

Title (same): **Become an OONI Observer!** 

Description (edited): **Would you like to receive notifications for OONI Probe testing when we hear of censorship events in your country or network?**

Buttons (very slightly edited): `**Not now**`, `**OK**`

**Comment by lorenzoPrimi** [comment]
After a discussion with @agrabeli we decided at the moment we don't need this string "We will notify you to coordinate on OONI Probe testing..." as we only have only one notification type, in the future when we'll have testing, news and updates we can allow the user to select only one type of notification. In the OONI Probe settings, not the android settings.

What is needed now is to get the generic notification permission and personally I like the other copy your shared with me much more:

**Description: Are you interested in contributing testing during emergent censorship events? By enabling notifications, you will receive messages from us when we hear of censorship events in your country, asking you to run specific tests or test specific websites.**

**Comment by agrabeli** [comment]
@lorenzoPrimi I think this description is a bit too long for a pop-up message, and it also doesn't communicate the potential other use cases of push notifications (such as receiving news and updates from the OONI-verse). 

Here are two alternative descriptions:

1. Would you like to receive updates and notifications for OONI Probe testing when we hear of censorship events in your country?

2. Would you like to receive notifications for OONI Probe testing when we hear of censorship events in your country? We may also share news and updates from the OONI-verse.

@lorenzoPrimi @hellais What do you think? Would either of the above 2 work?

**Comment by agrabeli** [comment]
@lorenzoPrimi @hellais I'm also not sure if we should say "become an OONI observer" (instead of just "receive notifications"). While I very much like it, it doesn't communicate the point, which is to receive notifications, which may expand beyond testing. What do you think?

**Comment by lorenzoPrimi** [comment]
I have no strong preference between 1 and 2, maybe 2 is more complete.
I like "receive notifications" better, it's straight to the point

**Comment by lorenzoPrimi** [comment]
This has been discussed, now it's implementation time!

**Comment by agrabeli** [comment]
@lorenzoPrimi Speaking of implementation => Following the internal discussions with you & @hellais, let's go with the following copy for the pop-up to sign-up for push notifications:

Title: **Receive notifications**

Description: **Interested in running OONI Probe tests during emergent censorship events? Enable notifications to receive a message when we hear of internet censorship near you!**

**Comment by lorenzoPrimi** [comment]
Strings uploaded to transifex

**Comment by lorenzoPrimi** [comment]
The popup has been created.
Now it's a matter on deciding when to call it

**Comment by lorenzoPrimi** [comment]
This modal is gonna be called on the second app launch if the tests are > 0

**Comment by lorenzoPrimi** [comment]
This has been done but it won't go in the next release, not closing it until merged

**Comment by hellais** [comment]
Also to consider as part of this work my feedback on the push notification branch: https://github.com/ooni/probe/issues/1239#issuecomment-682394571

**Comment by lorenzoPrimi** [comment]
Title "Get updates on Internet Censorship"
Text "Interested in running OONI Probe tests during emergent censorship events? Enable notifications to receive a message when we hear of internet censorship near you!"
Buttons:
- Sounds great
- No, thanks

@agrabeli please confirm

**Comment by lorenzoPrimi** [comment]
@hellais show this modal to "Third app open of the 2.6.0 and test ran > 0"

**Comment by agrabeli** [comment]
@lorenzoPrimi the only edit I would propose is writing "Get updates on internet censorship" in the title (instead of using a capital I for "internet"), since we generally say "internet" throughout the copy.

**Comment by lorenzoPrimi** [comment]
Copy updated, now it's implementation time!

**Comment by lorenzoPrimi** [comment]
@hellais should we save the number of app open even after the 3rd?
What do you think of something similar?
https://stackoverflow.com/questions/13044342/count-the-number-of-times-the-app-was-opened-in-xcode
Or we should call it "2.6_appopen"?

**Comment by hellais** [comment]
> @hellais should we save the number of app open even after the 3rd?

Is this going to be stored in the in-app DB? What are the tradoffs of storing it also after the 3rd open vs not?

**Comment by lorenzoPrimi** [comment]
Not in the db, in the local preferences

**Comment by lorenzoPrimi** [comment]
With @bassosimone we decided to use 5 (int) as value to show the dialog for notification.
After the 5 run of the app the value of this int will not be updated
