### ISSUE TITLE
cli: compress Windows binary using zip

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1219]
On Windows, decompressing `.tar.gz` is rather annoying, according to a user report. Using `zip`, this user adds, would significantly simplify and better the experience for Windows users.

**Comment by sarathms** [comment]
We do not publish a `.tar.gz` build for Windows. The closest thing would be the automatic github release (v#.#.#.tar.gz) file, but it has the `.zip` alternative right next to it. So, I am not sure how to resolve this issue.

**Comment by bassosimone** [comment]
@sarathms I believe then the bug was related to probe-cli. Reassigning to me.

**Comment by bassosimone** [comment]
Done in https://github.com/ooni/probe-cli/pull/147
