### ISSUE TITLE
whatsapp: remove AllEndpoints option

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1226]
This option increases the false positive rate. If an endpoint is blocked/down and we choose it, then we say that WhatsApp is down when instead it may just be a minor disruption. The Go implementation and the spec have been updated to not mention this option anymore. Using this option on mobile will now trigger a warning.

See https://github.com/ooni/probe-engine/issues/743#issuecomment-656145345

**Comment by lorenzoPrimi** [comment]
@bassosimone should I also switch to the Go implementation of whatsapp test?

**Comment by bassosimone** [comment]
@lorenzoPrimi I think it's fine to start removing the option. If you switch to Go now it breaks b/c you don't have the new engine version that also implements WhatsApp.
