### ISSUE TITLE
Icon for privacy setting

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1229]
xRef: https://github.com/ooni/probe/issues/1217

**Comment by hellais** [comment]
I suggest using for the privacy settings the material design lock icon: https://material.io/resources/icons/?icon=lock&style=baseline.

I have found that most apps will have a setting group labelled "Security & Privacy". While we currently only have Privacy related settings, I think the two things go hand in hand so it's reasonable to use the same icon.

If we eventually also have Security option, maybe we can put them in here too.

We could even, starting from now, change the copy of the settings section to be "Security & Privacy", though would like input from @agrabeli on this.
