### ISSUE TITLE
Test the OONI Probe dev build with countly support

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1239]
This is about installing the apk on Android and the test flight on iOS.

Things to test include:
- Sending push notification by specifying the country with only text
- Sending push notification with a OONI Run link (android + iOS)
- ??

**Comment by hellais** [comment]
@lorenzoPrimi can you share the link to the dev build?

Do you have pointers for what I should be testing in particular?

Thanks!

**Comment by lorenzoPrimi** [comment]
iOS is in Testflight
Android: https://drive.google.com/file/d/1J9NCMxqt5LO7iha19suVIpxuE6iJZYkm/view?usp=sharing

Test link: oonitest://nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Frun.ooni.io%2F%22%5D%7D&mv=1.2.0

**Comment by hellais** [comment]
I am doing some testing of this code and will take note of some feedback:

- Perhaps the notification settings options needs some text/copy to explain what they are in fact signing up to, similar to how we explain stuff in the sharing menu section
- Can we do that when the user clicks on a push notification they received and it does not have an OONI Run link, the text of the push notification is displayed inside of the mobile app in a modal? We don't have to save the text, but I think we should display it again otherwise the user might not have read it when they saw the notification.
- The OONI Run deep link works great! I tested it both with the app in foreground and background. When the app is in foreground, is it easy to show the notification on screen, similar to the modal in the above point?

When testing this I found some issues with the countly plugin:
- The countries in the country selector are duplicated making it not possible to select a country
- I suspect the user count at the end of the wizard might not be accurate, because the number of target users kept changing

@sarathms ^

**Comment by lorenzoPrimi** [comment]
> * Perhaps the notification settings options needs some text/copy to explain what they are in fact signing up to, similar to how we explain stuff in the sharing menu section

We can add the text we already made for https://github.com/ooni/probe/issues/1210 as a footer

**Comment by lorenzoPrimi** [comment]
> * Can we do that when the user clicks on a push notification they received and it does not have an OONI Run link, the text of the push notification is displayed inside of the mobile app in a modal? We don't have to save the text, but I think we should display it again otherwise the user might not have read it when they saw the notification.

There is no native way to save or retrieve that text, unless we decide to store in the database every received notification, if it's something we need to discuss open an issue, I don't think will go in this immediate release

**Comment by lorenzoPrimi** [comment]
> * The OONI Run deep link works great! I tested it both with the app in foreground and background. When the app is in foreground, is it easy to show the notification on screen, similar to the modal in the above point?

Only iOS
