### ISSUE TITLE
Edit network count after deleting test data

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1240]
After running a few tests, when you delete all the test data, the network count in the Hero doesn't change. This is more perceivable in freshly installed app when initially all counts are zero, then running a test increases the test count and network count to 1, and then deleting that one test doesn't reset the network count to 0.

<img height=500 src='https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/4e53cf3a-738a-4622-b009-cf3f7919a004' />

## Specifications

  - Version: ooniprobe-android-dev: 2020.08.25-10
  - Platform: Android

**Comment by lorenzoPrimi** [comment]
Furthermore:
- This bug doesn't affect iOS.
- Android: Tests is not updated when delering one (or more) tests. You need to go away and come back to this screen to see it updated
