### ISSUE TITLE
Test & release mobile app with Countly

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1241]
Remember to clean Countly database

**Comment by lorenzoPrimi** [comment]
@bassosimone we will use the "Staged rollout" for this release to understand how it works in practice.
Basically you set a % of users that will get the update, and every day you can update that % (even directly to 100%) or stop the rollout and send a new build.

I think we will need this approach in the future so better get to understand how it works now with calm waters

**Comment by bassosimone** [comment]
> I think we will need this approach in the future so better get to understand how it works now with calm waters

absolutely! Thanks a lot!

**Comment by lorenzoPrimi** [comment]
@agrabeli can you provide the release notes for this version?
We need to enphatize that we switched to a self hosted platform for analytics (to improve the app bla bla,
and that now user can enable notification (or the other word we used)
Basically we will link the copy about modal and notification in a "release note"

Ref:

Get updates on internet censorship
Interested in running OONI Probe tests during emergent censorship events? Enable notifications to receive a message when we hear of internet censorship near you!

Help us improve OONI Probe
With the new OONI Probe, you can contribute anonymized usage metrics to help us improve the app. You can opt out through the settings at any time.

**Comment by bassosimone** [comment]
Regarding testing, let us also remember about https://github.com/ooni/ooni.org/issues/561#issuecomment-694418964

**Comment by agrabeli** [comment]
Thanks @lorenzoPrimi and apologies for the delay. You can use the following release notes:

# What's new?

* Notifications to run OONI Probe tests when censorship events emerge

* Self-hosted platform for the collection of anonymized usage metrics so that we can improve OONI Probe
