### ISSUE TITLE
Display the text of the push notification that is received even when the app is in foreground

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1242]
Can we do that when the user clicks on a push notification they received and it does not have an OONI Run link, the text of the push notification is displayed inside of the mobile app in a modal? We don't have to save the text, but I think we should display it again otherwise the user might not have read it when they saw the notification.

This came from:  https://github.com/ooni/probe/issues/1239#issuecomment-682394571

**Comment by hellais** [comment]
@lorenzoPrimi wrote in https://github.com/ooni/probe/issues/1239#issuecomment-682426206

> Can we do that when the user clicks on a push notification they received and it does not have an OONI Run link, the text of the push notification is displayed inside of the mobile app in a modal? We don't have to save the text, but I think we should display it again otherwise the user might not have read it when they saw the notification.

There is no native way to save or retrieve that text, unless we decide to store in the database every received notification, if it's something we need to discuss open an issue, I don't think will go in this immediate release

> The OONI Run deep link works great! I tested it both with the app in foreground and background. When the app is in foreground, is it easy to show the notification on screen, similar to the modal in the above point?

Only iOS

**Comment by hellais** [comment]
Is there some way in which we can achieve this feature on both Android and iOS (priority is for Android support)?

How much effort would it require to implement this on both platforms?

**Comment by lorenzoPrimi** [comment]
We need to specify exactly what we are trying to achieve and why.

In my opinion saving the push notifications is not only difficult but can lead to many problems, not receiving some, losing some of them for timeouts...
It seems me what you want to achieve is kind of a "news" feed or something like that, it would be much better to have an API get_notifications to be called and a table to get populated instead of saving the actual content of notifications.

**Comment by hellais** [comment]
> We need to specify exactly what we are trying to achieve and why.

The problems we are facing are two-fold:

A. When a user has the app in foreground and they receive a notification, it may not be apparent to them that they received it, because the app is foreground, so we need to handle this in some way in the app ideally.
B. If the phone is in the users pocket locked and they receive a notification, they may just tap on it quickly without reading the text and then it's confusing that they end up in the app without any recollection of what was said in the push notification. For OONI Run links it's not so much of a problem, but for push notifications informing them of stuff, that is not so nice

> In my opinion saving the push notifications is not only difficult but can lead to many problems, not receiving some, losing some of them for timeouts...

Can you provide more information and explaination as to what these "many problems" are and why this could lead to some notifications not being received?

> It seems me what you want to achieve is kind of a "news" feed or something like that, it would be much better to have an API get_notifications to be called and a table to get populated instead of saving the actual content of notifications.

No what I am talking about is a different thing. 

We don't need to store all the notifications, we just need to have the notification "in memory" at runtime. Once the user has seen it and/or tapped away from the modal, the notification can be forgotten by the app.

**Comment by lorenzoPrimi** [comment]
A. It's how Android works, we can force a modal when receiving the notification, but so far I haven't seen one app that does that. (that = showing the notification on screen instead in the notification centre) This because notification exists for a reason, showing a modal while the user is doing something interrupt his work and it's not clear is a notification.

B. Show an alert with the notification text when you tap on the notification centre is the easiest way.

Both approach requires to modify the "receiver" code provided by countly and handle the notification ourselves, not relying on their classes. I need to check how difficult and smooth will be to make ooni run link work without having to rewrite a lot of code.
 
And my question is again what are we trying to achieve? In this round I thought we just want to send OONI Run links and we delayed other type of notifications for the future, with an appropriate study, instead of adding code in the app that we might never use.

**Comment by hellais** [comment]
> And my question is again what are we trying to achieve? In this round I thought we just want to send OONI Run links and we delayed other type of notifications for the future, with an appropriate study, instead of adding code in the app that we might never use.

I suspect I may not have explained myself properly. A & B are NOT solutions, but rather PROBLEMS that we should solve.

Perhaps we can have a chat about this in realtime so I can explain this to you better.

**Comment by lorenzoPrimi** [comment]
To recap our call, I need to do more research on (if doable)
- Show a modal when tapping on a notification with only text
- Show a modal with notification text when opening the app if there is something in the notification centre (and clear it)
- Show modal when notification received with app opened

**Comment by lorenzoPrimi** [comment]
3rd Point "Show modal when notification received with app opened"
is already implemented
![Screenshot_2020-09-02-10-52-31-034_org.openobservatory.ooniprobe.dev.jpg](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/51dc52b0-33e7-4493-b52c-d174078cb8f8)

**Comment by lorenzoPrimi** [comment]
From countly doc:
Here are the explanations of common usage scenarios that are handled automatically: 

- It doesn't do anything, apart from conversion tracking if you specify it as a Data-only notification in the dashboard. This effectively sets a special flag in the message payload, so you may process it on your own.
- It displays a Notification whenever a message arrives, and your application is in the background.
- It displays Dialog when a new message arrives, and your application is in the foreground. 
- It displays Dialog when a new message with an action arrives (open URL), and the user responds to it by swiping or tapping the notification.

A Dialog always has a message, but the set of displayed buttons depends on the message type:

- It displays a single ‘Cancel’ button for notifications without any actions (only a text message).
- For notifications with a URL (for instance, you ask the user to open a link to some blog post), it displays both the ‘Cancel’ & ‘Open’ buttons.
- It displays the corresponding buttons for notifications with custom buttons.

**Comment by lorenzoPrimi** [comment]
Android:
- Show a modal when tapping on a notification with only text
[Waiting countly expert answer]
- Show a modal with notification text when opening the app if there is something in the notification centre (and clear it)
[Waiting countly expert answer]
- Show modal when notification received with app opened
[Working]

**Comment by lorenzoPrimi** [comment]
Based on this research I think the easier and most flexible approach is to create a click_action/deeplink that is gonna be sent with a normal non OONI run notification.
There is no escape to this.
https://stackoverflow.com/questions/30785609/how-to-handle-tap-of-notification-in-android-if-displayed-automatically-by-gcm

In alternative as a super hack, we could save the notification text in the local storage in `public void onMessageReceived` method, then show it on app start and finally delete it.

As last option we do nothing and we keep the default behaviour for now, at least we have statistics on how many people interacted with the notification.

**Comment by lorenzoPrimi** [comment]
***iOS***
This is how notifications work in iOS
https://count.ly/images/guide/0176050-diagram-3.png

But I can override some notification methods https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#how-push-notifications-work-in-countly

That means:
- Show a modal when tapping on a notification with only text
Definitely, using `didReceiveNotificationResponse` method.
https://stackoverflow.com/questions/39267549/ios-how-to-integrate-push-notification-in-ios-10

- Show a modal with notification text when opening the app if there is something in the notification centre (and clear it)
Doable, using the `getDeliveredNotificationsWithCompletionHandler` in the  `applicationWillEnterForeground` callback
https://stackoverflow.com/questions/44161196/get-pending-notifications-when-app-enters-foreground

- Show modal when notification received with app opened
Could be possible but countly behaviour will also show the notification on top of the screen. 
It's to evaluate if we could prevent that to happen but it seems we can't 

![IMG_3592.PNG](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/b4ff0d6e-5eb7-4434-b6e7-c325656c443f)

**Comment by lorenzoPrimi** [comment]
A doc has been created https://docs.google.com/document/d/1TvjRxey5XnwAnFkgt06fletsa9XudFJqIjlgcFurSu8/edit#

**Comment by bassosimone** [comment]
Created tentative meeting w/ @lorenzoPrimi @agrabeli to discuss this and sort it out.
