### ISSUE TITLE
Investigate initial load time performance issues in desktop app UI

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1243]
While developing the language selector feature (#1088), I observed that the load time of the app increased significantly in development environment. This issue is to collect more information about performance during initial load and possibly identify areas to optimize.

@agrabeli @hellais Since you mentioned that some users also reported something similar from earlier versions, can you please add details here. In case they were not related to the loading time performance, maybe we can document those as separate issues.

**Comment by sarathms** [comment]
One preliminary observation is that the way we load the translated strings is not efficient because we load all strings from all supported languages. We can change this to load the translation for the currently detected locale and reload when we change language in settings.

**Comment by sarathms** [comment]
Another related improvement to do in this regard is to refactor the way we bundle the translations. Right now, we pack everything into a single JSON and access it from `window.OONITranslations` and we use this as a source of truth for `supportedLanguages` etc. We should instead use the `${lang}.json` files as-is and load them at run time.

**Comment by sarathms** [comment]
Linking this with #1279

**Comment by sarathms** [comment]
Some work is done here: https://github.com/ooni/probe-desktop/tree/fix/load-locales-ondemand

**Comment by hellais** [comment]
This has been identified to be caused by: #1279
