### ISSUE TITLE
Review how we request for countly permissions

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1244]
@lorenzoPrimi can you share more information on how and when we request permissions for the new privacy settings and how they work exactly.

Screenshot and detailed logic workflow would help in assessing this.

I believe this might also be connected to how we request notification permissions https://github.com/ooni/probe/issues/1210.

**Comment by lorenzoPrimi** [comment]
Strings 
`Modal.ShareAnalytics.Title` = `Help us improve OONI Probe`
`Modal.ShareAnalytics.Paragraph` = `We would like to collect some metrics about how you use OONI Probe so that we can improve it. You can opt out of this at any time through the settings.`

**Comment by lorenzoPrimi** [comment]
When a user updates to the new version will be prompt with the following modal*, with no possibility to skip it, either they accept or refuse to share data.

![Screenshot_1598883029.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/26bede17-e700-450f-8225-642419540f48)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-31 at 15.03.50.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/00e68ef7-d205-4303-a886-ebc8c0409d51)

* It's the same style of modal we used to ask users "Enable manual upload?"

**Comment by lorenzoPrimi** [comment]
Change the title and text of the modal:
"You wanna help us making the app better?"
"Share *anonymous* metrics, it's the best thing you can do."
- Mention "new feature in this update", "The new ooniprobe supports privacy preserving ...", say "self hosted"
- Stress the "any time you can opt out"

Buttons:
- Sounds great
- No, thanks

**Comment by agrabeli** [comment]
And here are some of my notes:

New privacy-preserving metrics

With the new OONI Probe, you can contribute anonymized metrics to help us improve the app. At any time, you can opt out through the settings. 

Sounds great!

No, thanks

**Comment by agrabeli** [comment]
@lorenzoPrimi @hellais Here are several versions of what we could potentially use for the title and paragraph of this pop-up:

## 1

> # Help us improve OONI Probe
> 
> Contribute anonymized metrics and help us improve OONI Probe! You can opt out through the settings at any time.

## 2

> Title: New privacy-preserving metrics
> 
> Paragraph: With the new OONI Probe, you can contribute anonymized metrics to help us improve the app. At any time, you can opt out through the settings.

**Comment by agrabeli** [comment]
Thanks @lorenzoPrimi . @hellais what do you think?

**Comment by hellais** [comment]
Can we try adding something about the self-hosted nature of the metrics collection?

Let me try to make a suggestion based on the number 2.

> You can now help us make OONI Probe better!

This way we can capture the fact that it's new (we say "now") and the fact that the user is helping us make the software better.

> With the new OONI Probe, you can contribute usage statistics to our self-hosted privacy-preserving metrics server to help us improve the app. At any time, you can opt out through the settings.


What do you folks think?

**Comment by lorenzoPrimi** [comment]
I think it's overcomplication, to me "self-hosted privacy-preserving" seems like auto jerking off ourselves.
Also I think many people wouldn't understand all these words and can create an opposite effect of what we want to achieve.

**Comment by agrabeli** [comment]
@hellais I like the title you're proposing, but I agree with @lorenzoPrimi that perhaps the paragraph ends up being a bit too long and complicated (particularly since terms like "self-hosted" may not be clear to everyone).

Perhaps we can go with the following:

> ## You can now help us improve OONI Probe!
> 
> With the new OONI Probe, you can contribute anonymized usage metrics to help us improve the app. You can opt out through the settings at any time.

What do you think?

**Comment by hellais** [comment]
Yes this is perfect! Thanks for putting it together @agrabeli and @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
Agreed, you can safely remove "you can" from the title :D

**Comment by agrabeli** [comment]
@hellais great, thanks!

@lorenzoPrimi Please use the following copy:

> # Help us improve OONI Probe
> 
> With the new OONI Probe, you can contribute anonymized usage metrics to help us improve the app. You can opt out through the settings at any time.

For the buttons:

> Sounds great
> 
> No, thanks

**Comment by lorenzoPrimi** [comment]
Copy updated
https://github.com/ooni/probe-android/commit/617844ee3a6213e96d7f0586e2ecef7c2f2f0657
https://github.com/ooni/probe-ios/commit/b1d39d0bb5bbfe773416fddf590097c81a6495ad
