### ISSUE TITLE
When interrupting the performance test group the row becomes inaccessible and app crashes

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1245]
OONI Probe version: `3.0.4-dev` 0b65b25

Steps to reproduce:
- Start the performance test group
- Interrupt it mid-way through the test
- Go to the result and tap on the row
- Notice the crash

This is only a crash of the Desktop UI, because I can see that probe-cli exits with a good exit code:
```
10:10:08.521 › running /Users/x/code/ooni/probe-desktop/build/probe-cli/darwin_amd64/ooniprobe [
  '--batch',
  '--software-name=ooniprobe-desktop',
  '--software-version=3.0.4-dev',
  'list',
  '7'
] {
  stdio: [ 'pipe', 'pipe', 'pipe' ],
  env: {
    OONI_HOME: '/Users/x/code/ooni/probe-desktop/ooni_home',
    OONI_STDIN_EOF_IMPLIES_SIGTERM: 'true'
  }
}
10:10:08.594 › stdout:  {"fields":{"asn":30722,"failure_msg":"","id":297,"is_anomaly":false,"is_done":true,"is_failed":false,"is_first":true,"is_last":true,"is_upload_failed":false,"is_uploaded":true,"measurement_file_path":"/Users/x/code/ooni/probe-desktop/ooni_home/msmts/performance-2020-09-01T080005.8645Z/msmt-dash-0.json","network_country_code":"IT","network_name":"Vodafone Italia S.p.A.","report_file_path":"","runtime":13.568716,"start_time":"2020-09-01T08:00:05.906765Z","test_group_name":"performance","test_keys":"{\"connect_latency\":0.018166105,\"median_bitrate\":67550,\"min_playout_delay\":0}","test_name":"dash","type":"measurement_item","upload_failure_msg":"","url":"","url_category_code":"","url_country_code":""},"level":"info","timestamp":"2020-09-01T10:10:08.594334+02:00","message":"measurement"}
10:10:08.595 › stdout:  {"fields":{"anomaly_count":0,"asn":30722,"data_usage_down":102788.623046875,"data_usage_up":233.3974609375,"network_country_code":"IT","network_name":"Vodafone Italia S.p.A.","start_time":"2020-09-01T08:00:05.906765Z","total_count":1,"total_runtime":13.651222,"type":"measurement_summary"},"level":"info","timestamp":"2020-09-01T10:10:08.594535+02:00","message":"measurement summary"}
```

![Screenshot 2020-09-01 at 10 14 38](https://user-images.githubusercontent.com/424620/91825211-3cc5a480-ec3c-11ea-93cc-c090372ac222.png)
![Screenshot 2020-09-01 at 10 14 46](https://user-images.githubusercontent.com/424620/91825221-3f27fe80-ec3c-11ea-9a75-ac7501d04467.png)

**Comment by sarathms** [comment]
I considered using the `N/A` string from the copy. But it may not work well in all languages. One alternative I can think of (but not fully convinced) is to drop the column and show only the available ones. @hellais Do you have any suggestions?

`LANG=en`
![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/403c9d3d-d418-4acc-a677-e42151a694ed)

`LANG=sq`
![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/0ef7987f-8389-472c-a295-2587d5c3c58f)
