### ISSUE TITLE
Multiple mobile deep link URL prefixes

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1246]
In a testing branch we added, additionally to the `ooni://` mobile deep link prefix, also `oonitest://`, which are both handled in the same way.

We might eventually want to use specific URL prefixes to trigger different behaviours in the app or potentially even different apps owned by OONI.

As part of testing we added the `oonitest://` prefix, because we needed to test the OONI Probe dev flavour side-by-side with the canonical OONI Probe flavour. If we were using the same prefix, it would have lead to a collision and an annoying popup asking the user to pick which of the two OONI Probe they wanted to use to open that specific prefix.

The question posed by @lorenzoPrimi is if we should keep this `oonitest://` prefix even in the release or not.

**Comment by lorenzoPrimi** [comment]
![Screenshot_2020-07-27-14-02-56-602_android.jpg](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/9ccd806d-783b-425f-a228-640e88be27be)

**Comment by lorenzoPrimi** [comment]
I think this branches should be deleted as there will never be the case for the user to have two OONI Probe apps.
It was something you needed for testing purpose pre-Countly release.

**Comment by hellais** [comment]
I think this is going to require a bit longer discussion and thinking. I suggest we discuss this during the weekly frontend call.
