### ISSUE TITLE
probe-ios, probe-android: release v2.7.0

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1251]
With @lorenzoPrimi we've been working for quite some time towards this goal. During Sprint 23, we aim at releasing a stable version of ooni/probe-engine (https://github.com/ooni/probe-engine/issues/871) and removing the MK dependency from the iOS app (https://github.com/ooni/probe-engine/issues/668). Once this work is done, we can release v2.7.0.

I am tentatively adding this issue to Sprint 23, but I think we'll likely only be done in Sprint 24.

**Comment by lorenzoPrimi** [comment]
Moving to Spring 24, no way we do two releases in less than a month.

**Comment by lorenzoPrimi** [comment]
Due to new circumstances the release will be anticipated in this sprint.

**Comment by bassosimone** [comment]
Staged rollout in progress for both apps. Time to close this issue.
