### ISSUE TITLE
mobile: log progress messages to progress screen

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1254]
There is useful content in progress messages, e.g., the currently measured speed for ndt. We want this information to appear on the screen when we are running the text rather than a boring "Start nettest with index 0".

**Comment by lorenzoPrimi** [comment]
@bassosimone should I write the log progress message on the log.txt file of the test?

**Comment by bassosimone** [comment]
@lorenzoPrimi we wanna see progress both in the test file and on screen.
