### ISSUE TITLE
Google Services included in fdroid build

### ISSUE THREAD

**Issue by mimi89999** [ooni/probe#1255]
## Expected Behavior
They should not be part of the build

## Actual Behavior
They are. See https://f-droid.org/wiki/page/org.openobservatory.ooniprobe/lastbuild_64

## Steps to Reproduce the Problem
`./gradlew assembleStableFdroid`

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by bassosimone** [comment]
@mimi89999 Thank you for letting us know about this! Is there a way for us to run a fake f-droid build as part of continuous integration, so that we can avoid publishing releases that break f-droid?

**Comment by mimi89999** [comment]
@bassosimone Something like https://github.com/ooni/probe-android/pull/373 ?

**Comment by lorenzoPrimi** [comment]
@mimi89999 we created the fdroid flavor to remove the gplay services 
as you can see firebase is only implemented in the full flavor 
https://github.com/ooni/probe-android/blob/master/app/build.gradle#L87

And the plugin is only applied if the flavor is not fdroid
https://github.com/ooni/probe-android/blob/master/app/build.gradle#L66
https://github.com/ooni/probe-android/blob/master/app/build.gradle#L142

Can you tell us how did it end up in the build?

**Comment by mimi89999** [comment]
@lorenzoPrimi I run the `assembleStableFdroid` task: `./gradlew assembleStableFdroid`

**Comment by lorenzoPrimi** [comment]
Apparently this approach 
https://github.com/ooni/probe-android/blob/master/app/build.gradle#L142
doesn't work anymore for some reasons.

I think we should revert the gradle file to the old version:
https://github.com/ooni/probe-android/blob/v2.5.2/app/build.gradle#L120
to fix this

**Comment by lorenzoPrimi** [comment]
@mimi89999 can you try this branch as well? 
Thank you

https://github.com/ooni/probe-android/tree/fdroid_fix

**Comment by mimi89999** [comment]
@lorenzoPrimi That branch does build for me.

**Comment by bassosimone** [comment]
@mimi89999 thank you for checking. I will take a look at https://github.com/ooni/probe-android/pull/373 soon.

**Comment by lorenzoPrimi** [comment]
@mimi89999 we will deploy the fix soon and tag a `2.7.1` for fdroid.
One question: do we have to bump up also the `versionCode 65` even if it was never released on fdroid?

thank you for your help

**Comment by mimi89999** [comment]
@lorenzoPrimi You don't need to make a new release. I added `sed -i -s '/com.google.gms/d' build.gradle app/build.gradle` to the build commands.

**Comment by licaon-kter** [comment]
@mimi89999 That does it, I'm updating the recipe now
