### ISSUE TITLE
Make MSI package

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1258]
@xmha97 commented on [Thu Sep 10 2020](https://github.com/ooni/probe-desktop/issues/175)

Hello,
Please make MSI Installer.
Thanks.

**Comment by sarathms** [comment]
Thanks for opening this issue @xmha97. We are trying to understand how to make this more effective to our users. Can you share some details about how you might benefit from having an MSI package compared to the windows package we currently publish?

**Comment by xmha97** [comment]
> 
> 
> Thanks for opening this issue @xmha97. We are trying to understand how to make this more effective for our users. Can you share some details about how you might benefit from having an MSI package compared to the windows package we currently publish?

I want to create a Chocolatey package for the OONI Probe desktop app.
MSI packages is more compatible with Chocolatey package.

**Comment by sarathms** [comment]
We use `electron-builder` to generate the official packages we publish. [According to their documentation](https://www.electron.build/configuration/squirrel-windows), it uses [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) to generate MSI installers. But that project is currently not actively developed, although it is maintained.

I don't have any experience packaging for `chocolatey`. I have used it a few times recently to setup a temporary dev environment on Windows.

So if you are interested, I can support you in doing this as an experiment. You can start with generating the MSI installer. By the time it works, I should be able to assess if we can officially support publishing this format. There are factors like code signing, security implications that need to be considered before we can get there. And depending on that, we can decide if we want to have official chocolatey packages or some other alternative.

What do you think @xmha97?

**Comment by xmha97** [comment]
Thanks for your explanation
Now I understand that there is no need to make an MSI package because the installer installed the program without any questions. (Sorry for my bad English)
So, Please close this issue.

**Comment by sarathms** [comment]
I am glad you were able to find what you were looking for. I also just noticed that you have published a package for `probe-cli`. Congratulations and thank you for volunteering to maintain it! Feel free to reach out if you need any help in carrying it forward. Do consider joining our slack channel to keep in touch. Looking forward to the `probe-desktop` package :wink:
