### ISSUE TITLE
WebConnectivity progress stuck at 72 seconds

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1261]
The progressbar on `WebConnectivity` test is stuck at 72 seconds remaining. 
This could be because the `LOG` event only update the logs and the `PROGRESS` event are not sent as before

**Comment by bassosimone** [comment]
This happens because we're not emitting events while we make progress in oonimkall. Will fix that in probe-engine 0.20.0. Thank you for letting me know about this issue, which I completely missed when testing the new Go engine.

**Comment by bassosimone** [comment]
Moving to next Sprint.

**Comment by bassosimone** [comment]
Should be fixed in https://github.com/ooni/probe-engine/pull/1031. Let's reopen if needed @lorenzoPrimi

**Comment by bassosimone** [comment]
We're not done yet. MK was taking also into account the maximum runtime. We need to do the same, see: https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/nettests/runnable.cpp#L65

**Comment by bassosimone** [comment]
Fixed in https://github.com/ooni/probe-engine/commit/c790ebf5a61489e93570d2ed0e78acbf2e380565 and https://github.com/ooni/probe-engine/pull/1044.
