### ISSUE TITLE
Design measurement deletion feature for desktop apps

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1264]
In a discussion about #1257, we discussed about designing the UI and workflow to allow users to delete measurements manually.

**Comment by hellais** [comment]
I have designed some mocks for this:


![OONI Probe Settings.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/54258b7e-500a-4541-9164-00760fa975c1)

![OONI Probe Settings delete confirm.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/df758469-503e-4b2c-8615-873caeb0f85b)

**Comment by hellais** [comment]
@agrabeli should review the copy of these modals

**Comment by agrabeli** [comment]
Thanks @hellais for creating the mockup, and thanks @sarathms for opening this ticket (and developing this important feature!). 

You can use the following copy for the "delete all uploaded" setting:

**Delete all uploaded results**

And you can use the following copy for the pop-up window:

**Title:** Do you want to delete all uploaded results?

**Paragraph:** You are about to delete all uploaded OONI measurements from your device. They will still be available on [OONI Explorer](https://explorer.ooni.org/).

**Buttons:** `Cancel`, `Delete`

^^ The copy in the paragraph assumes that it's possible to add hyperlinks. If not, please remove the OONI Explorer link.

**Comment by hellais** [comment]
Thanks, I updated the mocks based on your copy edits.

**Comment by hellais** [comment]
This is done.
