### ISSUE TITLE
Restructure the Test to a Android Service 

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1269]
During https://github.com/ooni/probe/issues/916
I discovered that the best way to restructure the test run is to make an Android Service.
In this Issue I will track the code revamp to change this while the other ticket will be done after this one to make the service in background

This issue include a lot of testing. 
We might want to release this before having the service in the background as an automatic testing

**Comment by lorenzoPrimi** [comment]
Two bugs found by @hellais 
- If I tap “Interrupt” (big x in the corner), while “preparing the test” it doesn’t stop and just runs normally
- It also vibrates way too often while it’s running. Can we make it only vibrate at the start?

**Comment by lorenzoPrimi** [comment]
- Interrupting the test while downloading the urls wasn't easy, I manage to prevent running webconnectivity test after the urls have been downloaded without distort much the code. And showing "finishing pending test please wait"

**Comment by lorenzoPrimi** [comment]
My phone wasn't vibrating at all, but I researched the code to disable vibrations and implemented. Your turn to test it.
I also disabled lights and sounds.
Unfortunatelly the settings are per channel so I can't make it vibrate once.

**Comment by hellais** [comment]
> My phone wasn't vibrating at all, but I researched the code to disable vibrations and implemented. Your turn to test it.

I tested it again and it's fixed!
