### ISSUE TITLE
Check app usage

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1271]
Check app usage for every test ran, try delete all tests or one and check how app usage will vary

This is neeeded for feature like "Delete tests older than X days" and delete also the db entries.

**Comment by hellais** [comment]
As an experiment I tried deleting all results from an app that had 97 tests (see: https://github.com/ooni/probe/issues/1273)

Below are the screenshots of the data usage before and after:
![Image from iOS (1)](https://user-images.githubusercontent.com/424620/98528245-54dd2400-227c-11eb-83ae-431b874e4554.png)

![Image from iOS](https://user-images.githubusercontent.com/424620/98528236-53136080-227c-11eb-89f0-fbbaf35a732c.png)

**Comment by hellais** [comment]
TODO
* Add debug support for understanding what is occupying so much
* Add total number of MBs used in the app settings
* Investigate why 97 tests is leading to such a high on disk app usage

**Comment by lorenzoPrimi** [comment]
TODO after the investigation
- Add settings to delete all test with label on disk usage
- Measure buttons clicks

**Comment by lorenzoPrimi** [comment]
Found two issues with the iOS app:
- Query in the DB without the 'escapes' on report_id is not always successful so it doesn't delete tests
- Failed measurement are never deleted as the BASIC_QUERY contains `is_failed = 0` 

Will do the same tests on Android
