### ISSUE TITLE
Implement the new dashboard for probe-desktop

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1274]
See: https://github.com/ooni/probe/issues/1222

This is blocking on the choose website options

**Comment by hellais** [comment]
We should for the time being drop the choose websites button and ship this.

**Comment by sarathms** [comment]
Using this as the reference for Choose Websites feature.

![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/50780c5d-a953-4172-827a-be9030689333)
