### ISSUE TITLE
Add support for max_runtime to probe-desktop

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1280]
This is about implementing max_runtime to 90 seconds inside of probe-desktop

**Comment by bassosimone** [comment]
I could review about 1/2 of the PR so far. Overflowing to next Sprint.

**Comment by bassosimone** [comment]
This work seems ready to merge. Can we merge it already, @sarathms, or are you planning on pushing more changes?

**Comment by sarathms** [comment]
@bassosimone The PR is complete. I was investigating why the CI job failed. But those tests are still meaningless anyway. So I will go ahead and merge it.
