### ISSUE TITLE
cli: onboarding bypass when run by systemd

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1281]

**Comment by hellais** [comment]
What should be the expected behaviour?

**Comment by bassosimone** [comment]
I'd say the code should either be stuck forever reading from stdin or (better) recognise that stdin is not a tty and therefore that it should not attempt to provide any onboarding but instead exit. What currently happens (in a semi deterministic fashion) is that the onboarding succeeds and the code starts running, which is really not what I'd have expected.

**Comment by bassosimone** [comment]
I will modify the code to bail if it's not attached to a tty, since this is easy to do and is what legacy probe did.

**Comment by hellais** [comment]
Just to better understand, the issue is that it's bypassing the onboarding when you run it in `--batch` mode unconditionally?

**Comment by bassosimone** [comment]
No, we're not running in background in batch mode. The issue is that we're running in "normal" mode and the tool for responding seems to interpret input from stdin (probably EOF?) as a signal that the user has said yes.

**Comment by hellais** [comment]
Gotcha, thanks for explaining it. Then I strongly agree that this is a bug that should be fixed.

**Comment by bassosimone** [comment]
Done in https://github.com/ooni/probe-cli/pull/176
