### ISSUE TITLE
cli: add support to choose specific websites to test

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1283]
This is similar to the 'Choose Websites' feature in the mobile apps. This feature is part of the new dashboard layout in probe-desktop that we plan to roll out soon.

This also allows `probe-desktop` to provide the desktop version of OONI Run. 

Related:
* New dashboard layout [ooni/probe#1274](https://github.com/ooni/probe/issues/1274)
* OONI Run for desktop [ooni/probe#1071](https://github.com/ooni/probe/issues/1071)

**Comment by bassosimone** [comment]
I'm implementing a plan for having this functionality. It requires a bunch of refactoring to align probe-cli and probe-engine, remove redundant code, make sure we have enough testing etc. In the next 1-2 days, you'll see many commits referencing this issue that are basically pure yak shaving to prepare the codebase for adding this functionality.

**Comment by bassosimone** [comment]
In https://github.com/ooni/probe-cli/pull/177, we start to unify the code for running tests in cli and engine. The end goal is to use ~the same code such that the cli gets a bunch of the options used by the engine, including the ones to customise a test list.

**Comment by bassosimone** [comment]
This has been much more difficult than estimated originally.

**Comment by bassosimone** [comment]
I have created a follow-up issue for this issue: https://github.com/ooni/probe-engine/issues/1127. We can now close this issue and postpone future changes similar to the ones implemented here to a future Sprint.
