### ISSUE TITLE
cli: test and publish new homebrew package

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1289]
Follow up from: https://github.com/ooni/probe/issues/1270

**Comment by hellais** [comment]
We have a working package here: https://github.com/hellais/homebrew-core/pull/1.

To test it you should do:
```
cp Formula/ooniprobe.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ooniprobe.rb
brew upgrade ooniprobe
brew uninstall ooniprobe
brew install ooniprobe
```

Moreover to enable the service on boot you should run:
```
sudo brew services restart ooniprobe
```

The only issue is that the service is running as root. @bassosimone will look into fixing this.

**Comment by bassosimone** [comment]
(Adjusting the estimate because this has been a large fraction of my time.)

**Comment by bassosimone** [comment]
We have an open PR here: https://github.com/Homebrew/homebrew-core/pull/66474

**Comment by hellais** [comment]
We made considerable progress on this, but are now waiting on implementing a native feature to setup the periodic scheduler in probe-cli.

**Comment by bassosimone** [comment]
Progress was made but we're not done, as mentioned above.

**Comment by bassosimone** [comment]
@hellais I failed to understand whether we still want to package ooni/probe-cli for macOS, or whether we want to only package ooni/probe-desktop as a cask instead. Maybe we should have another quick chat about this topic?

**Comment by bassosimone** [comment]
Status update at end of Sprint 30: https://github.com/ooni/probe-cli/pull/192 provides a way forward for running automatic tests using OONI Probe on macOS. We will reasonably finalize this in the next 7-10 days.

**Comment by bassosimone** [comment]
Done here: https://github.com/Homebrew/homebrew-core/pull/69399!
