### ISSUE TITLE
Apple: App privacy questions requirement starts December 8

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1295]
Add App privacy details on the App Store

From: https://developer.apple.com/app-store/app-privacy-details/

**Comment by lorenzoPrimi** [comment]
This has to be done by an Account Holder or Admin. 
Assigning to @hellais

**Comment by hellais** [comment]
![Screenshot 2020-12-08 at 13.08.19.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/9f2ab1b6-eb74-4ad0-a20b-3faea7de3b32)

Done
