### ISSUE TITLE
Add OONI logo in Test Results page of OONI Probe apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1298]
I've noticed that many community members frequently share screenshots of the Test Results page in the OONI Probe apps, rather than screenshots of the individual measurement pages (though those are sometimes shared too).

However, given the fact that the Test Results page doesn't have the OONI logo, those test results (shared on social media) could be from "anywhere", as it's unclear to those who don't use OONI Probe that those measurements come from our apps.

I'd therefore suggest adding the OONI logo in the main Test Results page of the OONI Probe mobile and desktop apps, so that when screenshots of those pages are shared on social media, it's clear that those are OONI Probe tests.

**Comment by hellais** [comment]
We already have the logo in the sidebar, maybe it's a bit too much to have it in the sidebar and also inside of the results screen?
