### ISSUE TITLE
cli: implement check-in API

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1299]
See: https://github.com/ooni/api/pull/202/files

**Comment by bassosimone** [comment]
We did some progress with @lorenzoPrimi and we'll continue in the next Sprint.

**Comment by bassosimone** [comment]
Status update at the end of Sprint 30: we've sketched out a client-side prototype with @lorenzoPrimi. We had a bunch of very detailed design discussions. In particular, with @FedericoCeratto, we explored the intersection between check-in and the new `run` functionality that has recently been introduced in ooni/probe-engine. As we advance, we need to (1) fix how URLs are filtered and returned to probes and (2) add support for probe-wide, persistent settings.

**Comment by bassosimone** [comment]
We'll continue in the next Sprint.

**Comment by bassosimone** [comment]
We have merged code to talk to the API to probe-engine in Sprint 31. We're going to continue working on this in Sprint 32.

**Comment by hellais** [comment]
We are going to implement a simple MVP of this as a next step. This will simply call the check-in API and then start running the tests.

**Comment by bassosimone** [comment]
https://github.com/ooni/probe-cli/pull/266 (which is ~ready) contains a great chunk of the work required to make this happen. The rest of the work consists of (1) adapting `InputLoader` and (2) doing more refactoring of session.go and inputloader.go.

I will finish working on this issue in the next Sprint.

**Comment by bassosimone** [comment]
Before moving forward, we need to teach the CheckIn API to return the whole list when the run is `manual`. This would guarantee that we are honoring our commitment to users that, if they disable the maximum runtime, they are going to test the full test list. Also, this would ensure that `ooniprobe run` works as before, which is indeed what we want. Discussed with now with @agrabeli and @hellais (thanks!).

**Comment by bassosimone** [comment]
With https://github.com/ooni/probe-cli/pull/267, we're getting closer to complete this work. Here's a list of TODO items that I have identified so far and should go as future changes before calling this work complete:

- [ ] ooniprobe: remove the limit argument and introduce max_runtime
- [ ] miniooni: remove the limit argument and introduce max_runtime
- [ ] ooniprobe: propagate the runType
- [ ] inputloader: better separation of unit and integration tests
- [ ] libminiooni: merge back with miniooni
- [ ] fsx: replace interfaces with Go 1.16 fs interfaces
- [ ] other?

When they will all be done, we will have finished the work.

**Comment by bassosimone** [comment]
So, I think this work is done. What's missing is to deploy the changed I've added to the API in https://github.com/ooni/api/pull/229.

**Comment by bassosimone** [comment]
The API has been deployed in https://github.com/ooni/api/pull/230
