### ISSUE TITLE
mobile: make sure we remove unused probe-engine settings

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1305]
In https://github.com/ooni/probe-engine/pull/1103, we removed unused options for probe-engine's mobile API. Let us make sure we remove the same variables also from iOS and Android apps. (It should be the case, let's double check that!)

**Comment by lorenzoPrimi** [comment]
Started in https://github.com/ooni/probe-ios/pull/408 and https://github.com/ooni/probe-android/pull/397
