### ISSUE TITLE
Provide 32 bit builds for linux and windows

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1315]
This was a community request.

**Comment by bassosimone** [comment]
I started working on this. So far I managed to make miniooni compile also on windows/386 and linux/386. Please see the related pull request here: https://github.com/ooni/probe-engine/pull/1190.

**Comment by bassosimone** [comment]
I started working on this. So far I managed to make miniooni compile also on windows/386 and linux/386. Please see the related pull request here: https://github.com/ooni/probe-engine/pull/1190. I have started working on probe-cli at https://github.com/ooni/probe-cli/pull/193. I have still to figure out how to build for linux/386. It seems `docker pull --platform=linux/386 golang:1.14-alpine` pulls the proper image, but ` docker run --platform=linux/386 -it -v`pwd`:/ooni -w/ooni golang:1.14-alpine` is clearly broken. I need to further investigate how to run the 386 image (and whether we have other options).

**Comment by bassosimone** [comment]
More progress: https://github.com/ooni/probe-cli/pull/193#issuecomment-763075959

**Comment by bassosimone** [comment]
This is now done as of ooni/probe-cli 3.4.0.
