### ISSUE TITLE
Update informed consent logic for probe-cli

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1317]
We should change the logic for informed consent checking by:
- Looking for the probe-legacy informed consent file as part of `InitDefaultConfig`
- Write to a file the informed consent flag instead of config file
- Check for informed consent via the config file flag and the file flag
- Test that doing an upgrade from 2.x to 3.x it will work fine

This is necessary to ship: https://github.com/Homebrew/homebrew-core/pull/66474

**Comment by bassosimone** [comment]
This has been done in https://github.com/ooni/probe-cli/pull/188.
