### ISSUE TITLE
Add riseupvpn experiment in the iOS app

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1323]
https://github.com/ooni/probe-engine/issues/1060

**Comment by lorenzoPrimi** [comment]
@cyBerta can I please ask you to give me the RiseupVPN logo for the test for the iOS app?
Ideally I need a svg or better a pdf version of the logo, like the ones already in the repo: https://github.com/ooni/probe-ios/tree/master/ooniprobe/Images.xcassets/tests/websites.imageset

**Comment by cyBerta** [comment]
Oh sorry, I didn't see your message.
