### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [ooni/probe#1327]
Ref: https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild_69&oldid=286040

**Comment by bassosimone** [comment]
@licaon-kter it seems the build keeps failing. This time the error is like:

```
> Task :app:compileStableFdroidReleaseSources
> Task :app:lintVitalStableFdroidRelease
> Task :app:dexBuilderStableFdroidRelease
> Task :app:stripStableFdroidReleaseDebugSymbols FAILED
> Task :app:mergeStableFdroidReleaseJavaResource
> Task :app:mergeDexStableFdroidRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripStableFdroidReleaseDebugSymbols'.
> NDK from ndk.dir at /home/vagrant/android-ndk/r21d had version [21.3.6528147] which disagrees with android.ndkVersion [22.0.7026061]
```

Whole log here: https://f-droid.org/wiki/index.php?title=org.openobservatory.ooniprobe/lastbuild_70&redirect=no

What should we do to fix this issue?

Thank you!

**Comment by licaon-kter** [comment]
Will fix that asap, yes

**Comment by bassosimone** [comment]
It seems the problem has been fixed here: https://f-droid.org/wiki/page/org.openobservatory.ooniprobe/lastbuild_70. I still cannot see the new version of the app being available on my f-droid installation, but I guess this is just a matter of time!
