### ISSUE TITLE
android: CI fails with DeadSystemException 

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1333]
Some tests fails in a non-deterministic way, about 75%/25% success rate (fails 25% times)

This is due to [DeadSystemException](https://developer.android.com/reference/android/os/DeadSystemException)

`The core Android system has died and is going through a runtime restart. All running apps will be promptly killed.`

Logs:
https://github.com/ooni/probe-android/runs/1786302866

```
Starting 63 tests on test(AVD) - 10
org.openobservatory.ooniprobe.AutomateScreenshotsTest > testTakeScreenshot[test(AVD) - 10] FAILED 
	androidx.test.espresso.PerformException: Error performing 'androidx.test.espresso.contrib.RecyclerViewActions$ActionOnItemAtPositionViewAction@a94bc5e' on view 'with id is <org.openobservatory.ooniprobe:id/recycler>'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
org.openobservatory.ooniprobe.UITests > testSettings[test(AVD) - 10] FAILED 
	java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ApplicationPackageManager.hasSystemFeature(ApplicationPackageManager.java:614)
Tests on test(AVD) - 10 failed: Test run failed to complete. Expected 63 tests, received 29. onError: commandError=false message=INSTRUMENTATION_ABORTED: System has crashed.
> Task :app:connectedStableFullDebugAndroidTest FAILED
```

**Comment by bassosimone** [comment]
Thanks for opening this issue! We will keep it open until the related issue is gone _for a long time_.

**Comment by Filmaluco** [comment]
This one should be fixed with the new UI Tests we developed and merged (https://github.com/ooni/probe-android/pull/431)

**Comment by bassosimone** [comment]
That's great to hear, thank you!
