### ISSUE TITLE
Update probe-cli download script to fetch only x64 builds

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1339]
`probe-cli` has recently started publishing builds for the `i386` architecture. By default, these were also being downloaded by the `scripts/download-bin.js` although we do not use it on any platform right now. Because the script runs on every build, it prolongs the build process. We can skip downloading files that are not required for development or production.

**Comment by bassosimone** [comment]
@sarathms yes! It may also be worth skipping the zip release if you're not using it!

**Comment by hellais** [comment]
This is done.
