### ISSUE TITLE
Prevent to run test when custom url doesn't start with http or https prefix

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1344]
When pressing Run check every row and highlight in red every url without prefix. 
Show error toast maybe

**Comment by lorenzoPrimi** [comment]
![andr_wrong_url](https://user-images.githubusercontent.com/1616097/109634441-247a0800-7b41-11eb-9bc3-ce0f865fc18d.png)

**Comment by lorenzoPrimi** [comment]
iOS
![wrong_url2](https://user-images.githubusercontent.com/1616097/109644089-f1d60c80-7b4c-11eb-9f7c-2d0aa7c3ace6.png)

**Comment by lorenzoPrimi** [comment]
Mobile has been implemented, leaving open for @sarathms

**Comment by sarathms** [comment]
This has been done in desktop also now. https://github.com/ooni/probe-desktop/pull/211

**Comment by sarathms** [comment]
This is now released in `v3.4.0` on desktop. :heavy_check_mark: :rocket:
