### ISSUE TITLE
iPhone app v2.9.2 on iPhone 6: crashes

### ISSUE THREAD

**Issue by iphone6user** [ooni/probe#1347]
**Describe the bug**
The app does not open on the iPhone 6 with iOS 12. Yet, the app is ‘on’ to close the app, when swiping up. 

**To Reproduce**
Tap the OONI Probe app and nothing happens. App does not open. 

**Expected behavior**
The ability to open and interact with the app. 

**Screenshots**

**System information (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 12
 - Version 12.5..1

**Comment by bassosimone** [comment]
Thank you for letting us know, @iphone6user! I'm paging @lorenzoPrimi, our mobile developer, for help in triaging this issue. I think we have added crash tracing functionality in 2.9.2, so it should be reasonable easy for us to understand this problem!

**Comment by iphone6user** [comment]
Thank you for the help! FYI I downloaded version 2.9.3 and having the same issue.

**Comment by bassosimone** [comment]
With @lorenzoPrimi we should be investigating this issue in the Sprint starting today!

**Comment by bassosimone** [comment]
Thanks! So, we have identified a bunch of issues thanks to a better system
to organize crashes and we're going to fix them and push out a new release
soon!

Best regards,

Simone


Il giorno sab 13 feb 2021 alle ore 22:16 iphone6user <
notifications@github.com> ha scritto:

**Comment by iphone6user** [comment]
Thank you for the update! Very much appreciated.

**Comment by iphone6user** [comment]
Thank you for the fix!! Much appreciated.

**Comment by bassosimone** [comment]
Happy to see it's working now :-).
