### ISSUE TITLE
Mobile: RiseupVPN test always shows blocked (False positive)

### ISSUE THREAD

**Issue by nk521** [ooni/probe#1348]
**Describe the bug**
The circumvention test will always show that RiseupVPN is blocked though, for me, its has been a false positive everytime.
App version is 2.9.2.

**To Reproduce**
Just run the circumvention test.

**Expected behavior**
The test should have been passed.

**Screenshots**
![image](https://user-images.githubusercontent.com/30789322/107496842-d912b080-6bb7-11eb-8338-b7a51c7f8766.png)

**System information (please complete the following information):**
 - Device: Android Device
 - OS: Android 10

**Additional context**
Logs
```
Looking up OONI backends... please, be patient
session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
contacted bouncer
Looking up your location... please, be patient
geoip lookup
resolver lookup
Opening report... please, be patient
open report
Starting measurement with index 0
riseupvpn: measure https://riseup.net/provider.json: <nil>
riseupvpn: measure https://api.black.riseup.net:443/3/config/eip-service.json: <nil>
riseupvpn: measure https://api.black.riseup.net:9001/json: connection_refused
riseupvpn: measure tcpconnect://212.129.4.124:443: <nil>
riseupvpn: measure tcpconnect://199.58.83.12:443: <nil>
riseupvpn: measure tcpconnect://37.218.244.249:1194: <nil>
riseupvpn: measure tcpconnect://198.252.153.28:443: <nil>
riseupvpn: measure tcpconnect://212.83.144.12:443: <nil>
riseupvpn: measure tcpconnect://212.83.143.67:443: <nil>
riseupvpn: measure tcpconnect://212.83.146.228:443: <nil>
riseupvpn: measure tcpconnect://212.129.4.141:443: <nil>
riseupvpn: measure tcpconnect://212.129.37.129:443: <nil>
riseupvpn: measure tcpconnect://212.83.165.160:443: <nil>
riseupvpn: measure tcpconnect://163.172.126.44:443: <nil>
riseupvpn: measure tcpconnect://212.83.182.127:443: <nil>
riseupvpn: measure tcpconnect://212.129.62.247:443: <nil>
riseupvpn: measure tcpconnect://199.58.83.10:443: <nil>
riseupvpn: measure tcpconnect://185.220.103.12:443: <nil>
riseupvpn: measure tcpconnect://37.218.244.251:443: <nil>
riseupvpn: measure tcpconnect://199.58.83.10:23042: <nil>
riseupvpn: measure tcpconnect://198.252.153.28:23042: <nil>
Submitting measurement... please, be patient
sessionresolver: failure rate: primary: 0/3; fallback: 0/0
```

**Comment by bassosimone** [comment]
Good day, https://github.com/nk521! Thank you for reporting this issue to us and for preparing such a great bug report!. I have seen the same issue yesterday morning when I looked into my automates runs. Today it seems to be working.

The problem in your logs (thanks for providing them!) is indicated by this line:

```
riseupvpn: measure https://api.black.riseup.net:9001/json: connection_refused
```

My reading of this line is that the host could possibly have been down at the time.

Do you still see failures?

**Comment by nk521** [comment]
Hey @bassosimone! I also think that the endpoint was down at that time. Now its working good.

Closing the issue.

**Comment by bassosimone** [comment]
Thanks for confirming, cheers!
