### ISSUE TITLE
riseupvpn: reduce false positives rate

### ISSUE THREAD

**Issue by cyBerta** [ooni/probe#1354]
**Describe the bug**

Currently RiseupVPN is considered blocked even if a single gateway is blocked. Since the RiseupVPN clients are build with redundancy and fallback mechanisms in mind, it normally doesn't reflect the reality. Moreover and even worse, the gateways are indicated as blocked if they are malfunctioning for whatever reason (misconfiguration, DDoS, reboot on security updates etc.). 
This produces a lot of false positives.

**To Reproduce**
Check current RiseupVPN test results, they need to be filtered to be useable for research. 

**Expected behavior**
I propose to adapt the general assumption about when RiseupVPN is considered blocked: 
- if the API blocked (no change to current behavior)
- if a transport is blocked (see below for more detail)

As a first step, I would like to add the following json structure in the test result output described in the spec: https://github.com/ooni/spec/blob/master/nettests/ts-026-riseupvpn.md#semantics
```
    "transport_status":{
        "obfs4": "ok" | "blocked",
        "openvpn":"ok" | "blocked"
    }
```
A transport will be evaluated as blocked if _no_ tcp connection has been established on _any_ gateway supporting that transport.
The structure of the json allows to add other pluggable transports in the future without changing the API.

As a second step, the changes have to be implemented in probe-cli

As a third step the changes need to evaluated in the clients

I propose to use this ticket to discuss the proposal and track the progress:
- [x] spec change: add `transport_status` json array
- [x] implement in core library and CLI (located in probe-cli repo)
- [x] check whether there are disabled integration tests that we should re-enable (@bassosimone)
- [ ] implement changes in Android
- [ ] implement changes in iOS
- [ ] implement changes in Desktop

**Comment by cyBerta** [comment]
sidenote: another discussion will happen here https://0xacab.org/leap/container-platform/lilypad/-/issues/19 in order to discuss how add a maintenenance note endpoint to the new backend riseup will use in the future.

**Comment by bassosimone** [comment]
In https://github.com/ooni/probe-cli/commit/945c1136732afd7ef456f15a35269cfd378c3a98, I temporarily disabled a test that was consistently failing and that would improve after https://github.com/ooni/probe-cli/pull/233.

**Comment by bassosimone** [comment]
I have reverted the disabling of the test here https://github.com/ooni/probe-cli/pull/240

**Comment by bassosimone** [comment]
We will review the associated PR in this Sprint!

**Comment by bassosimone** [comment]
Moving to beginning of next sprint.

**Comment by bassosimone** [comment]
I am going to close this issue because the changes were merged.

**Comment by cyBerta** [comment]
@bassosimone I think this issue needs to be reopened, the clients need to be adapted as well.

**Comment by bassosimone** [comment]
Sure, thank you!

**Comment by bassosimone** [comment]
We can close this issue again now.
