### ISSUE TITLE
Your application was corrupt

### ISSUE THREAD

**Issue by uratom962** [ooni/probe#1357]
**Describe the bug**
Your application was corrupt by Internet Provider or Government, or Gang stalking. I noticed that because, a few years before I know, I've seen on Ooni Probe, a fake results, like number inside my appartment, or other result with number of my life inside my street, or my age. So, I don't know how to study that, but maybe it's an troll by a good hacker. Or I have an fake eye, and sorry. If you translate my blog to french for english, you can found my old result when I found that. With the old [screenshot](https://tryuoupas.files.wordpress.com/2019/09/screenshot_20190919-074243.png).  This is my old [post](https://tryuoupas.wordpress.com/2019/09/19/internet-censure-espion/) : for OONI PROBE
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
 - Device: Samsung J3 Galaxy
 - OS: Android 5.1
 - Version : 2019

**Additional context**

**Comment by hellais** [comment]
Thanks for running OONI Probe!

It's unclear to me what is the bug you are reporting to us. As this issue is not actionable, I am going to close it.
