### ISSUE TITLE
Investigate how to build probe-cli & probe-desktop on apple silicon

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1360]

**Comment by sarathms** [comment]
Relevant electron blog post: https://www.electronjs.org/blog/apple-silicon

**TL;DR** Electron already supports building and publishing apps for Apple silicon starting from `v11.x`. We have to upgrade.

**Comment by bassosimone** [comment]
For probe-cli, it's straightforward once we use Go 1.16

**Comment by sarathms** [comment]
In conclusion:
* For `probe-cli` we have to upgrade Go from `1.14` to `1.16`
* For `probe-desktop` we have to upgrade Electron from `8.x` to `11.x`

@hellais Do you think we need to investigate more about this?

**Comment by hellais** [comment]
I think this settles it. I believe we have already upgraded to golang 1.16 in probe-cli, but we still have to upgrade electron to the latest.
I filed an issue to upgrade to electron 11.x: https://github.com/ooni/probe/issues/1402
