### ISSUE TITLE
cli: build error: *.mmdb.gz: no matching files found

### ISSUE THREAD

**Issue by ja-pa** [ooni/probe#1379]
Hi,
I'm trying to update the probe-cli package for OpenWrt to version 3.7.0 but it's failing with the following error message.

```
Finding targets
../../internal/engine/resourcesmanager/resourcesmanager.go:47:12: pattern *.mmdb.gz: no matching files found
```
(for more details see https://github.com/openwrt/packages/pull/15059/checks?check_run_id=2057865877#step:5:3334)

It is probably related to https://github.com/ooni/probe-cli/commit/322394fe63a64ca750f93c00b35d6988b553c354
Could you help me how to fix that error? I'm not sure where mmdb.gz should be located (or downloaded from).

**Comment by bassosimone** [comment]
Sure! You need to run `go run ./internal/cmd/getresources` before you run `go build ...`

**Comment by ja-pa** [comment]
Thanks. That fixed the issue.

**Comment by bassosimone** [comment]
My pleasure!
