### ISSUE TITLE
mobile: design UI for signal experiment

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1385]
Following up from https://github.com/ooni/probe/issues/1262, where we exposed DNSCheck and Signal as experimental experiments. We want signal to be a first class citizen of the IM group. This is assigned to @hellais for now. We will triage this issue in out 1:1 later today.

**Comment by hellais** [comment]
This has been done over here: https://github.com/ooni/probe/issues/1386#issuecomment-797669022
