### ISSUE TITLE
desktop: design UI for signal experiment

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1386]
Following up from https://github.com/ooni/probe/issues/1262, where we exposed DNSCheck and Signal as experimental experiments. We want signal to be a first class citizen of the IM group. This is assigned to @hellais for now. We will triage this issue in out 1:1 later today.

**Comment by hellais** [comment]
Here is the icon for the signal test:
![SignalIcon.svg](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/a4cd6e14-69ac-429f-a3cc-7acc0a0d87b5)

Here is the mockup for the test result
![Signal Mockup.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/f3935bcd-bcec-4754-a6d1-52251cb4c54a)
