### ISSUE TITLE
mobile: implement the experimental card

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1388]
Following up from https://github.com/ooni/probe/issues/1262, where we exposed DNSCheck and Signal as experimental experiments. We want signal to be a first class citizen of the IM group. This is assigned to @hellais for now. We will triage this issue in out 1:1 later today.

**Comment by hellais** [comment]
Here are the details for the UI of the experimental test card: https://github.com/ooni/probe/issues/1393
