### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by licaon-kter** [ooni/probe#1392]
F-Droid 2.9.10
AOSP10, Android Settings Dark Mode ON

![wPq6s06ESfKQMpoezj6s0A](https://user-images.githubusercontent.com/2282799/110777608-394d4e80-8259-11eb-9158-b976c79794d6.jpg)

![5eTLpLeERwK1E2PtA5W9vw](https://user-images.githubusercontent.com/2282799/110777616-3a7e7b80-8259-11eb-8f1a-7a85cb2730d9.jpg)

**Comment by lorenzoPrimi** [comment]
The onboarding wasn't supposed to use dark theme, should stay the same. Will fix it soon

**Comment by lorenzoPrimi** [comment]
Fixed in https://github.com/ooni/probe-android/commit/7339bd4ff8ae2a1a34342777b96e38d0f4626f30
