### ISSUE TITLE
Improve how we get informed consent about crash reporting

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1398]
It has been brought up (see for example: https://github.com/ooni/probe/issues/1391), that our onboarding doesn't do a good enough job at ensuring users are aware of the fact we are going to be submitting crash reports.

Therefore we should introduce an additional screen in the onboarding where we only request for the permission to collect crash reports.

This issue is about:
* [x] Creating a mockup for this additional screen
* [ ] Implementing it in mobile
* [ ] Implementing it in desktop

**Comment by hellais** [comment]
Here is a mockup of the additional screen for obtaining informed consent about crash reporting. @agrabeli should review the copy here to be sure it's good.

![Informed consent crash reporting.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/e0b63032-e26f-43ec-969f-93c703378007)

**Comment by hellais** [comment]
The UX side of things is done. Documented the next steps in the following issues:
* https://github.com/ooni/probe/issues/1455
* https://github.com/ooni/probe/issues/1456

**Comment by lorenzoPrimi** [comment]
@hellais is this gonna be the screen 3/4 or 4/4? 
(as I believe there won't be 3 screens anymore but 4)

**Comment by hellais** [comment]
> @hellais is this gonna be the screen 3/4 or 4/4?

It's going to be screen number 3, before the final step of onboarding
