### ISSUE TITLE
Evaluate self hosted crash reporting solutions for mobile

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1400]
We should look into more privacy preserving options for collecting crash reports for iOS and Android, so that we can get rid of google analytics and sentry.

A potential solution could be acra: https://github.com/ooni/probe/issues/1352.

**Comment by lorenzoPrimi** [comment]
Self host sentry https://develop.sentry.dev/self-hosted/

**Comment by lorenzoPrimi** [comment]
Google crashlytics has been removed.

**Comment by hellais** [comment]
We have opted for the time being to not further change the crash reporting tool as we have happily consolidated our crash reporting on the open source tool sentry.

In the future we might choose to self host that https://develop.sentry.dev/self-hosted/, but it's currently too much effort to do so.
