### ISSUE TITLE
URL in the choose websites page should be validated

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1411]
Currently it's possible to initiate a test with an invalid URL (for example missing the http(s):// prefix). We should rather do validation of this in the client and prevent running invalid URLs.
![Screenshot 2021-03-18 at 15 18 38](https://user-images.githubusercontent.com/424620/111641343-5b1c7780-87fd-11eb-8b0d-51bcff415f92.png)

**Comment by sarathms** [comment]
This was done in https://github.com/ooni/probe-desktop/commit/27f3337124d2d8b71b03b2590cc455edb048ffea and released in `v3.4.0`
