### ISSUE TITLE
Possibility to minimize the running activity while a test is running

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#1423]
And gray out the run button until the test has ended

**Comment by hellais** [comment]
We need to think about the UI of this. One idea could be to make the X button become a primary action button and replace the X with a minimize icon.

**Comment by lorenzoPrimi** [comment]
X become minus (-)
Minus button used minimise test
STOP button under the log

Create issue to have progress bar always present in the app.
Tapping on this snack bar opens the running test
