### ISSUE TITLE
netx: investigate refraction-networking/utls (2/n)

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1424]
Following up from https://github.com/ooni/probe-engine/issues/229. We want to determine:

- [ ] how to sync up with the latest version of Go (is it needed?)
- [ ] if we can successfully parrot the latest Firefox (so we can measure pretending to be it)

**Comment by kelmenhorst** [comment]
Further we want to determine:
- [ ] whether to use mimicked or randomized fingerprints

**Comment by bassosimone** [comment]
Will continue the work in https://github.com/ooni/probe/issues/1702
