### ISSUE TITLE
Incorrect progress and ETA reported in probe-cli logs

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1434]
**Describe the bug**
When probe-desktop uses the logs in batch mode, all tests, including the ones that do not need a `max_runtime`, seem to be showing ETA and progress based on `max_runtime` (the default 90s). This seems to be happening with the presence of `nettests.websites_max_runtime` in `confg.json`.

**To Reproduce**
```
ooniprobe run im --batch
```

**Comment by bassosimone** [comment]
Duplicates #1433.

**Comment by bassosimone** [comment]
I'll keep https://github.com/ooni/probe/issues/1433 as the reference issue.
