### ISSUE TITLE
android: crash after updating from Android 10 to Android 11

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1441]
A few users have written to us in private to let us know that the Android app was crashing on startup after a system upgrade for Android 10 to Android 11. The crash disappeared after they cleared user data.

While we investigate the issue, which may sound like incompatibility in the stored preferences or the database, other users should consider performing this step if they experience the same issue.

Many thanks for the users who got in touch with us and shared their solution to the problem! 🤗

**Comment by bact** [comment]
Confirmed the crash.

Android 11, security update 5 March 2021, installed new OONI Probe version, tried to open then crashed.

Updated to Android 11 security update 5 April 2021, still crash.

Clear storage and cache, can run the app.

**Comment by bassosimone** [comment]
@bact thanks for confirming the issue!

**Comment by bassosimone** [comment]
I can confirm the issue myself after updating. Clearing storage and cash fixed the issue.

**Comment by bact** [comment]
The crash at startup can come back again.

After several test runs, the crash can happen again. Once you clear the cache, it will run. Then repeat.

**Comment by bassosimone** [comment]
Thanks for letting us know, @bact!

**Comment by bassosimone** [comment]
We have looked into the open crashes with @lorenzoPrimi: we believe this to be fixed by https://github.com/ooni/probe-android/pull/424. We will nonetheless keep this issue open and check again after the next OONI release.

**Comment by bassosimone** [comment]
I will move this into the next Spring, where we'll likely make a new mobile release.

**Comment by Alex-Esko** [comment]
Simone Basso guided me here via mail

I can confirm the crash after i updated to Android 11.
Clearing storage app-data and cache fixed the issue temporarily.

That was a few weeks ago. But today it would again crash at every start until i again deleted app-data and cache.
I enabled error-log and will wait for the next crash.

OONI 2.11.0 (via F-Droid) running on SM-G970F (Samsung S10e) security patch 2021-04-01.

**Comment by bassosimone** [comment]
@Alex-Esko thank you for confirming! So, this issue should be fixed by https://github.com/ooni/probe-android/pull/424. We are planning on releasing it in the next 1-2 weeks. Thank you for using OONI Probe!

**Comment by hellais** [comment]
This is merged and fixed!
