### ISSUE TITLE
probe-engine: properly map SERVFAIL in web_connectivity test

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1467]
Here is a sample measurements which is failing due to `unknown_failure` and resulting in a blocking key set to NULL: https://explorer.ooni.org/measurement/20210224T120927Z_webconnectivity_MM_136480_n1_N19yEhByExEo13qC?input=https%3A%2F%2Fen.wikipedia.org%2F.

A better thing would be to map this particular type of error to `dns_serv_fail` so that we can consider it, as expected, as a DNS based anomaly.

**Comment by bassosimone** [comment]
done in https://github.com/ooni/probe-cli/pull/521
