### ISSUE TITLE
Display that a proxy is being used in the OONI Probe app

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1500]
Community members mentioned that it would be helpful if there were an icon or something that displayed (inside the OONI Probe app) that a proxy (whether Psiphon or a custom proxy) is being used (similarly to how Telegram shows that). 

They mention:

_"Because if the proxy settings are wrong or SOCKS5 is not available (e.g. Orbot exited), the user will not get a proper error."_

**Comment by lorenzoPrimi** [comment]
- [ ] Make "Error" in test result more descriptive
- [ ] Show modal "Current proxy doesn't work, go to settings and change your proxy settings"
- [ ] Under "running" add badge "with proxy"

**Comment by lorenzoPrimi** [comment]
Only the badge will be added now, the rese will be done with the new golang based API: #1410
