### ISSUE TITLE
Display test results incrementally (while other tests run)

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1501]
Community members in countries that experience pervasive levels of internet censorship (and cannot do anything online without a VPN) expressed that having to wait for OONI Probe to run (without being able to enable their VPN to do something else in the interim) can be very time-consuming and tedious. 

They therefore propose the following:

_One solution could be to split the page into two parts and display the results of the tests at a glance, instead of displaying a complete blank page with one line that is mostly incomprehensible._

Would it be possible to display some results (e.g. performance results, IM results) while longer-running tests (such as Web Connectivity) run?

**Comment by agrabeli** [comment]
I've assigned this ticket to several team members because it sounds like it deserves a longer discussion (and collaboration on several ends).

**Comment by lorenzoPrimi** [comment]
Is this the same as https://github.com/ooni/probe/issues/1423 ?

**Comment by hellais** [comment]
This is already implemented in mobile (via #1423), while on desktop we support displaying the results, but we don't have support for minimising the running test view.

The missing steps for desktop are tracked as part of: https://github.com/ooni/probe/issues/1977, so I think this issue can be closed.
