### ISSUE TITLE
engine: local network error classification

### ISSUE THREAD

**Issue by kelmenhorst** [ooni/probe#1505]
We want to create error wrappers that are operation-specific and classify network errors locally, right after they occurred.

Examples: `ErrDial`, for errors occurring during Dialing, `ErrWrite` for errors occurring during Write, etc.

This change will replace the current `ErrorWrapperDialer` construct which classifies network errors globally for a connection attempt.

This issue further requires that the gained information will be represented in the report file.

**Comment by bassosimone** [comment]
I have documented what we learned about Windows errors at https://github.com/ooni/probe/issues/1571#issuecomment-861249425. As part of this work, we're going to fix way in which Windows errors map to OONI errors.

**Comment by kelmenhorst** [comment]
Update:
We decided that having an operation-specific error type is not expedient. This is because determining the failed operation does not significantly reduce the solution space of possible network errors. 
Examples: 
- Timeout errors can happen during the TLS, or QUIC handshake, or during read(_from)/write(_to) operations.
- "No route to host" error has to be handled by both the `dialer` and the `quidialer` packages. 
The information gain of operation specific error types is therefore low.

Moreover, we learned that the error classification result is used in multiple places in the code to take decisions, not only by archival. Moving the classification code to `archival` therefore lead to semantically problematic dependencies.

**Comment by kelmenhorst** [comment]
How we will move forward with this issue:
We will keep the `errorx.ErrWrapper` construct in place for now.
- [ ] Modify `errorx.ToFailureString`, so that we do not depend on strings to classify errors. This will improve classification for Windows.
- [ ] Introduce local error classifiers for specific errors, moving this part of the classification code from `errorx` to the respective package (e.g. `quicdialer` can be the only place where we expect QUIC errors). With that, we will achieve a higher degree of localization.

**Comment by bassosimone** [comment]
The work described here is now ~done. I will take care of merging the PR and I will see to create follow-up issues as part of next Sprint's planning.

**Comment by bassosimone** [comment]
I just applied the data quality flag because this issue fixes a bunch of cases where otherwise we could not correctly identify many errors on Windows.

**Comment by bassosimone** [comment]
Issue overflowed to Sprint 42. Inflated effort to account for my effort in testing and merging.

**Comment by bassosimone** [comment]
I am going to close this issue now. It was larger than 13, it was probably 21 if we sum the amount of time spent by me and @kelmenhorst working on it.

So I am also going to bump the size of the task.

Finally, we will continue this work here: https://github.com/ooni/probe/issues/1544
