### ISSUE TITLE
web_connectivity lacking DNS control for AAAA queries

### ISSUE THREAD

**Issue by fortuna** [ooni/probe#1538]
**Describe the bug**
The web_connectivity control for DNS only has IPv4 addresses.

**To Reproduce**
This is an example where the experiment has IPv6 responses, but not the control: https://explorer.ooni.org/measurement/20201022T184640Z_webconnectivity_CU_27725_n1_zZuyMmN3UrmI0ng4?input=https%3A%2F%2Fpsiphon.ca%2F

**Expected behavior**
I would like to see AAAA queries in the control too, so that I can validate the returned IPv6 IPs.

**Additional context**
The lack of the control forces me to figure out other means to validate them.

**Comment by bassosimone** [comment]
I am going to optimistically assume we'll not rollback the change that makes all probes use the new webconnectivity TH and close this issue, which is related to the previous TH implementation.
