### ISSUE TITLE
web_connectivity needs DNS Response Code

### ISSUE THREAD

**Issue by fortuna** [ooni/probe#1569]
**Describe the bug**
web_connectivity doesn't provide the DNS Response code (See RCODE on https://www.rfc-editor.org/rfc/rfc1035.html).
We need that to compare the experiment against the control. For example, if both control and experiment return NXDOMAIN, I should be confident that's legit.
However control and the different probe implementations return different failure strings for the same error. It's hard to reverse engineer that.

**To Reproduce**
`voice.yahoo.jajah.com` is a domain that doesn't exist:
```
$ nslookup voice.yahoo.jajah.com
Server:         8.8.8.8
Address:        8.8.8.8#53
** server can't find voice.yahoo.jajah.com: NXDOMAIN
```

You can find measurements for that domain at https://explorer.ooni.org/search?until=2020-11-13&since=2020-10-14&domain=voice.yahoo.jajah.com

Take this, for example:
https://explorer.ooni.org/measurement/20201112T000127Z_webconnectivity_AT_1901_n1_AzrEIUDi13pvwMZz?input=http%3A%2F%2Fvoice.yahoo.jajah.com%2F

Control has `failure = dns_name_error`, while the test has `failure = dns_host_or_service_not_provided_or_not_known`

**Expected behavior**
failure for both control and test should be equal and indicate NXDOMAIN.
Ideally we would have a response_code field with the proper, standard value, as specified by the RFC.

**Additional context**
The code is available from standard libraries in both linux and windows:
- https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE
- https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#return-value
- https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfow#return-value

/cc @bassosimone

**Comment by bassosimone** [comment]
See this measurement: https://explorer.ooni.org/m/20240124132405.469683_IT_webconnectivity_6a383ecbe76d6cd6. If you expand this and head to the `test_keys.queries`, you'd see that we include the `RCODE` now:

<img width="1109" alt="Screenshot 2024-01-24 at 14 25 36" src="https://github.com/ooni/probe/assets/337298/f6e5d3d5-a347-4b7c-a18a-a06b8636c2dd">

You can also see from the screenshot that we include the raw response. Obviously, we can only do that when we are controlling ourselves the resolver. Web Connectivity v0.5 always uses both getaddrinfo and a DNS resolver.

When we're using getaddrinfo, we expose the getaddrinfo return code as an integer:

<img width="480" alt="Screenshot 2024-01-24 at 14 26 53" src="https://github.com/ooni/probe/assets/337298/7c8f4545-ddc3-46f1-b423-680ec960990a">

This addresses the first part of your feature requests. The second part of what you asked for is exposing test helper errors as clearly as possible, which is already described by https://github.com/ooni/probe/issues/2422.

**Comment by fortuna** [comment]
The NXDOMAIN error and the RCODE are definitely helpful, thanks.

In regards to the getaddrinfo error code, while the POSIX code is well defined, the number is not, and it varies from system to system, making it hard to use.

You need to map the number to a POSIX error name in order to be usable consistently. See https://stackoverflow.com/q/19885360/1234111 on how to do it.
