### ISSUE TITLE
android: crash when accessing specific OONI run result

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1706]
**Describe the bug**

You run the OONI run list described below and see a crash when you access the results.

**To Reproduce**

Run this OONI run https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22-%22%2C%22https%3A%2F%2Fgdpcambodia.org%2F%22%2C%22%22%2C%22-%22%2C%22https%3A%2F%2Fcomfrel.org%2F%22%2C%22-%22%2C%22https%3A%2F%2Fwww.adhoccambodia.org%2F%22%2C%22-%22%2C%22https%3A%2F%2Fwww.camboja.net%2F%22%2C%22%22%2C%22-%22%2C%22https%3A%2F%2Fwww.rfa.org%2Fkhmer%2F%22%2C%22-%22%2C%22https%3A%2F%2Fvodkhmer.news%2F%22%2C%22-%22%2C%22https%3A%2F%2Fwww.cambodiadaily.com%2F%22%5D%7D&mv=1.2.0 and then access the results.

**Expected behavior**

To see the results.

**Screenshots**

N/A

**System information (please complete the following information):**
 - Device: Samsung Galaxy S10 SM g973F/DS
 - OS: Android 11
 - Version: OONI Probe Android 3.0.0

**Additional context**

None.

**Comment by misuki74** [comment]
yup, can confirm this works. Doesn't break the app anymore. Thank you.

**Comment by bassosimone** [comment]
Thank you for confirming this! 🤗
