### ISSUE TITLE
android: butterknife is deprecated

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1709]
See https://github.com/JakeWharton/butterknife/commit/574ed28042dc30c14a623f0d36e666ff8008d32c.

We should now use [view binding](https://developer.android.com/topic/libraries/view-binding).

## Component to migrate.

- [x]  `CustomWebsiteActivity`
- [x]  `InfoActivity`
- [x]  `MainActivity`
- [x]  `MeasurementDetailActivity`
- [x]  `OoniRunActivity.java`
- [x]  `OverviewActivity.java`
- [x]  `ResultDetailActivity`
- [x]  `RunningActivity`
- [x]  `TextActivity`
- [x]  `DashboardFragment`
- [x]  `ProgressFragment`
- [x]  `ResultListFragment`
- [x]  `DashFragment`
- [x]  `FacebookMessengerFragment`
- [x]  `HeaderNdtFragment`
- [x]  `HeaderOutcomeFragment`
- [x]  `HttpHeaderFieldManipulationFragment`
- [x]  `HttpInvalidRequestLineFragment`
- [x]  `NdtFragment`
- [x]  `PsiphonFragment`
- [x]  `RiseupVPNFragment`
- [x]  `SignalFragment`
- [x]  `TelegramFragment`
- [x]  `TorFragment`
- [x]  `WebConnectivityFragment`
- [x]  `WhatsappFragment`
- [x]  `Onboarding1Fragment`
- [x]  `Onboarding2Fragment`
- [x]  `Onboarding3Fragment`
- [x]  `OnboardingAutoTestFragment`
- [x]  `OnboardingCrashFragment`
- [x]  `OnboardingDialogPopquizFragment`
- [x]  `OnboardingDialogWarningFragment`
- [x] #2526
- [x]  `ResultHeaderMiddleboxFragment`
- [x]  `ResultHeaderPerformanceFragment`
- [x]  `ResultHeaderTBAFragment`
- [ ] Remove `com.jakewharton:butterknife:+` and any other reference https://github.com/ooni/probe-android/pull/618

**Comment by hellais** [comment]
We have decided to do this incrementally as we touch parts of the code that are using butterknife.

Some work has been done as part of the following PRs:
* https://github.com/ooni/probe-android/pull/502
* https://github.com/ooni/probe-android/pull/511

**Comment by aanorbel** [comment]
## Component to migrate.

- [ ]  `CustomWebsiteActivity`
- [ ]  `InfoActivity`
- [ ]  `MainActivity`
- [ ]  `MeasurementDetailActivity`
- [ ]  `OoniRunActivity.java`
- [ ]  `OverviewActivity.java`
- [ ]  `ResultDetailActivity`
- [ ]  `RunningActivity`
- [ ]  `TextActivity`
- [ ]  `DashboardFragment`
- [ ]  `ProgressFragment`
- [ ]  `ResultListFragment`
- [ ]  `DashFragment`
- [ ]  `FacebookMessengerFragment`
- [ ]  `HeaderNdtFragment`
- [ ]  `HeaderOutcomeFragment`
- [ ]  `HttpHeaderFieldManipulationFragment`
- [ ]  `HttpInvalidRequestLineFragment`
- [ ]  `NdtFragment`
- [ ]  `PsiphonFragment`
- [ ]  `RiseupVPNFragment`
- [ ]  `SignalFragment`
- [ ]  `TelegramFragment`
- [ ]  `TorFragment`
- [ ]  `WebConnectivityFragment`
- [ ]  `WhatsappFragment`
- [ ]  `Onboarding1Fragment`
- [ ]  `Onboarding2Fragment`
- [ ]  `Onboarding3Fragment`
- [ ]  `OnboardingAutoTestFragment`
- [ ]  `OnboardingCrashFragment`
- [ ]  `OnboardingDialogPopquizFragment`
- [ ]  `OnboardingDialogWarningFragment`
- [ ]  `ResultHeaderDetailFragment`
- [ ]  `ResultHeaderMiddleboxFragment`
- [ ]  `ResultHeaderPerformanceFragment`
- [ ]  `ResultHeaderTBAFragment`
