### ISSUE TITLE
ooniprobe: build armv6 binaries

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1753]
These are the sub-activities:

- [x] figure out how to compile for armv6 (more precisely: `armv6l`)
- [x] ensure the compiled binaries work on Raspbian
- [ ] figure out if we can publish these binaries in our Debian repo or whether Raspbian needs a different repo (i.e., whether the same binaries work with _both_ Debian using armv6 - if it ever exists - and Raspbian)

Related links:

1. https://github.com/mdtita/oonionpie
2. https://github.com/masaarnet/Install-OONI-Probe-CLI-on-Raspberry-Pi

**Comment by alimirjamali** [comment]
I can confirm a successful build using the latest Golang release (go1.17.linux-armv6l.tar.gz)

**Comment by bassosimone** [comment]
Since https://github.com/ooni/probe-cli/pull/904, we build ooniprobe for armv6! 🚀

I guess the only remaining step is to publish a Debian package.

**Comment by bassosimone** [comment]
We're now creating Debian packages for linux armel. Unclear if this is enough to also fix https://github.com/ooni/probe/issues/1960.
