### ISSUE TITLE
[Measurement page] Move “Methodology” to copy (so that it’s not a button)

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1755]
Currently each OONI Probe measurement page includes a big "Methodology" button. While I agree that it's important to link to the test methodology from the result page, I don't think it deserves to have an entire button.

Rather, we could use that button for more useful information, such as the raw measurement data (which is currently hidden in the measurement page menu). 

I therefore propose that we **edit the copy to reference the methodology** (and relevant link), replacing the "Methodology" button with something else (such as raw data).

I follow-up on this here: https://github.com/ooni/probe/issues/1756.

**Comment by lorenzoPrimi** [comment]
Where do you want to move methodology to? Should we leave only the link in the test overview?

**Comment by lorenzoPrimi** [comment]
@agrabeli let me know when the copy is in place so I can add this paragraph on the app
