### ISSUE TITLE
Make “Share result” (previously “Share Explorer URL”) easy to find from the main measurement page

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1757]
Currently the "Share Explorer URL" setting (which I just renamed to "Share result" in the copy) is hidden in the menu of measurement pages, and community members have often expressed that they don't know of its existence.

Given that this seems to be quite an important feature -- as we have seen that our community members need to share OONI measurements (they usually do this by taking screenshots) -- I propose that we **move this setting to the main measurement pages** inside the OONI Probe apps (and remove it from the settings).

Perhaps we could add a button or some icon for it? Or copy? Not sure what would work best from a UX perspective.

**Comment by lorenzoPrimi** [comment]
Share button will be placed on the top right
