### ISSUE TITLE
OONI probe does not show number of website categories enabled in russian language

### ISSUE THREAD

**Issue by kotenok2000** [ooni/probe#1768]
![Снимок экрана (54)](https://user-images.githubusercontent.com/8822292/132008624-f7cbefb1-7ebd-4a43-a24b-51e92f32ff5f.png)
![Снимок экрана (53)](https://user-images.githubusercontent.com/8822292/132008626-dcbf0c34-3ed7-4e10-82e7-a6b788a881f5.png)

**Comment by hellais** [comment]
This has been fixed since the last few releases of probe-desktop.
