### ISSUE TITLE
Add support for automated testing of custom list of URLs

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1783]
Community members have expressed the need for automated testing of a custom list of URLs (as shared, for example, as part of community feedback in the OONI Run usability study: https://ooni.org/post/2020-06-09-ooni-run-usability-study-findings/). This is particularly useful when coordinating with a group of volunteers and encouraging them to test a specific list of websites on a regular basis.

OONI Probe users can now enable automated testing through the app, but they cannot ensure that a specific set of websites is tested regularly every day. 

More recently, other community members have highlighted this need. I guess we probably need to think about this along improvements to OONI Run (https://run.ooni.io/).

**Comment by MutegekiHenry** [comment]
Much needed feature, as a user, I have encountered scenarios where I always have to manually re-run my personal test list in certain intervals. It gets impossible when some intervals fall in the night when am unavailable or I just forget. So automating this will be super handy!

**Comment by hellais** [comment]
This will be handled once we have OONI Run v2 deployed.

**Comment by jbonisteel** [comment]
This will be done as part of Run v2
