### ISSUE TITLE
Link to OONI Blog & OONI Reports from OONI Probe apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1850]
During the October 2021 OONI Community Meeting, a community member highlighted the need to provide updates to OONI Probe users through the OONI Probe apps.

To this end, we could link to the following via the OONI Probe apps:

- [x] OONI Blog: https://ooni.org/blog/
- [x] OONI Reports: https://ooni.org/reports/

From a UX perspective, what's the best way to include these in OONI Probe?

**Comment by hellais** [comment]
My suggestion would be to add this to the about page as an inline link part of the copy.

Implementing this is a matter of:
* Updating the master copy spreadsheet
* Running the translation scripts to sync the copy with the app assets and transifex
* Getting the new strings translated
* Publishing a new release
