### ISSUE TITLE
spec: improve specification of errors

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1852]
We should restructure https://github.com/ooni/spec/blob/master/data-formats/df-007-errors.md to list errors in a table. We should discuss errors emitted by legacy probes separately, to reduce confusion.

**Comment by SrijanSriv** [comment]
@bassosimone I would like to change the presentation on this spec sheet. Let me know if there is an update to be added here.

More importantly, I noticed that there is a `PL/MK` type of error. Since legacy probe will have a separate table(if not a separate file entirely which is unlikely), which section should such a common error go to?

**Comment by bassosimone** [comment]
@SrijanSriv thank you for offering to do this work! 🤗 

> Since legacy probe will have a separate table(if not a separate file entirely which is unlikely),

I agree that a separate table is better than a separate file.

> which section should such a common error go to?

I think a good rule of thumb could be to have a table for current errors (i.e., `PE`) and a separate table for legacy errors (i.e., `PL/MK`).

I also think it may make sense to preserve which kind of probe generates which error. That is, to keep a column saying that a given error is, say, generated by `PL` and `PE`.

What do you think?

Thanks again!

**Comment by SrijanSriv** [comment]
> I think a good rule of thumb could be to have a table for current errors (i.e., PE) and a separate table for legacy errors (i.e., PL/MK).

Right! I was on the same track but I imagined mixed errors might not be legacy errors completely. Good to know.
And while I have you here, Happy Holidays :tada:

**Comment by bassosimone** [comment]
Thank you, same!

**Comment by bassosimone** [comment]
Done!
