### ISSUE TITLE
cli: use go-libtor when available

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1866]
This issue is about adapting the CLI build process to use go-libtor when available by changing the relevant places in which we start tor inside of `ooniprobe` and `miniooni`. It's one of the follow-ups of https://github.com/ooni/ooni.org/issues/764#issuecomment-948648080. Other follow-ups are more low-level and include generating the correct headers for all platforms, etc.

This issue depends on https://github.com/ooni/probe/issues/1867

**Comment by hellais** [comment]
It's now possible to use go-libtor when it's available. We switch between using go-libtor or searching for the tor binary in the path by using build constraints. The branch that integrates this work is the following: https://github.com/ooni/probe-cli/pull/614
