### ISSUE TITLE
measurements coming from the future

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1868]
There are a few measurements coming from the future. We have an issue addressing this problem on the probe side: https://github.com/ooni/probe/issues/1781. Now we also have an issue describing the problem as a whole.

**Comment by hellais** [comment]
We have addressed this in the backend by flagging measurements coming from the future with the failure flag.

I guess we can consider this issue closed?

**Comment by hellais** [comment]
As discussed with @bassosimone this can be considered done as we have implemented the following inside of pipeline: https://github.com/ooni/pipeline/pull/368.
