### ISSUE TITLE
mobile: stop automated-testing if the battery level is less than 20%

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#1896]
I think this is reasonable and necessary.

**Comment by lorenzoPrimi** [comment]
@xhdix there is no automated test if the phone is not charging.

**Comment by xhdix** [comment]
@lorenzoPrimi unless the user change it in the app settings?
https://github.com/ooni/probe-android/blob/2dd3734ca44737227f2dd69fae51536053ef4e1f/app/src/main/res/xml/preferences_global.xml#L34


(I only charge my phone for a few **hours** and use it for **days**.)

**Comment by lorenzoPrimi** [comment]
Correct, if you disable that option the test won't take in consideration the battery level.

There are many advanced settings like the one you proposed and data limit that will be implemented in the future. 
There was a discussion here https://github.com/ooni/probe/issues/916
and I guess should be resumed

**Comment by bassosimone** [comment]
@lorenzoPrimi if there's a way to disable testing with battery < 20% automatically, maybe we can just implement it? It seems reasonable to stop testing at that point, since most phones suggest low power mode when this happens.

**Comment by lorenzoPrimi** [comment]
@bassosimone 
I can add a method that doesn't start a test if the battery is < 20%, but I can't add a method that "stops" a test if the battery goes from 21 to 20

**Comment by bassosimone** [comment]
> I can add a method that doesn't start a test if the battery is < 20%, but I can't add a method that "stops" a test if the battery goes from 21 to 20

I think it's fine to just not start a test with low battery, thank you!
