### ISSUE TITLE
android: crash after clean install w/ default settings using Android 12

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1911]
This is a special case of https://github.com/ooni/probe/issues/1897. I've had a subsequent exchange with the user that reported https://github.com/ooni/probe/issues/1897 to us. It seems the app is _still_ crashing after a clean install. After that, the app instead works as intended. The presence of an "Error" test in the results suggests there's something wrong when we start tests.

**Comment by aanorbel** [comment]
@bassosimone , I have been unable to reproduce this bug on my devices.
App works properly on **Google Pixel 3a** running Android 12, Google Pixel 2 Emulator running android 12.

I may need more insight to be able to reproduce and fix this bug.

**Comment by bassosimone** [comment]
We discussed this with @aanorbel and we concluded that, albeit we cannot reproduce, it still seems healthy to take a look around the place where we think the failure could be to proactively make sure the code is more robust.
