### ISSUE TITLE
Add new default bridge to OONI tests

### ISSUE THREAD

**Issue by cohosh** [ooni/probe#1915]
We have a new default bridge in Tor Browser:
```
obfs4 185.100.85.3:443 5B403DFE34F4872EB027059CECAE30B0C864B3A2 cert=bWUdFUe8io9U6JkSLoGAvSAUDcB779/shovCYmYAQb/pW/iEAMZtO/lCd94OokOF909TPA iat-mode=2
```

Can we add this to the OONI Tor tests?

**Comment by hellais** [comment]
@FedericoCeratto do you know which of these two tor-targets.json files need to be editted and where the deployment needs to happen: https://github.com/ooni/sysadmin/search?q=obfs4?

**Comment by bassosimone** [comment]
The work done by @hellais in https://github.com/ooni/sysadmin/pull/495 should in principle add this bridge, however I just manually checked the output of https://bridges.torproject.org/moat/circumvention/builtin and I did not see such a bridge. So, I think this is a good moment to summon https://github.com/meskio and double check our procedure here. To summarize/recap:

1. The PR at https://github.com/ooni/sysadmin/pull/495 fetches bridges from https://bridges.torproject.org/moat/circumvention/builtin and writes the files served by the OONI API to OONI probes;

2. Our understanding is that the https://bridges.torproject.org/moat/circumvention/builtin API serves bridges included in Tor Browser;

3. So, I would have expected to see the bridge that @cohosh mentioned above inside https://bridges.torproject.org/moat/circumvention/builtin's output

4. Now I am wondering whether (a) the above bridge is not part of Tor Browser anymore or (b) some of our assumptions are wrong.
