### ISSUE TITLE
[Android] No indication that a proxy is being used 

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#1919]
When enabling a Custom Proxy (SOCKS5) or Psiphon there is no indication that a proxy is being used.

It seems that this is implemented here: https://github.com/ooni/probe-android/pull/442

Affected version: `ooniprobe-android, 3.4.1 FDroid`

**Comment by hellais** [comment]
Could you share a screenshot of the running test page?

You should see an badge indicating that the proxy is in use, as in the screenshot below:
![Screenshot 2021-12-17 at 14 33 24](https://user-images.githubusercontent.com/424620/146552282-aea5dbde-a1c6-4885-9112-a0307d309c30.png)

**Comment by anadahz** [comment]
![tm cleaned](https://user-images.githubusercontent.com/4969544/146560985-8e51913b-b9ff-437c-b5e4-1d0cfef32be5.jpeg)
![wc cleaned](https://user-images.githubusercontent.com/4969544/146560992-c8841932-62a5-473b-a64d-6168203e98e2.jpeg)

**Comment by aanorbel** [comment]
After properly investigating the problem, here is a more accurate description. 

Badge indicating that the proxy is in use is not displaying properly in **dark mode** on the app. 
Affected versions. **Full Release** , **FDroid Release** .... others

**Comment by hellais** [comment]
This has been fixed and is ready to be shipped in the new release.
