### ISSUE TITLE
run,ios,android: support URLs including a path

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1921]
Currently ooni/run does not accept a URL like https://github.com/ooni/run/pull/81. This is annoying because we cannot direct mobile phones to test URLs having a path. We should fix ooni/run first. I already did this in https://github.com/ooni/run/pull/81. Then I discovered the mobile apps are not able to use the URL produced by such an enhanced version of ooni/run. This issue is about tracking this problem and making sure that we can generate the URLs on ooni/run and use them on _at least_ Android but possibly also iOS.

**Comment by xhdix** [comment]
The previous structure of the OONI link was as follows:
```json
{
    "urls": ["https://www.example.com/", "https://www.example.org/", "https://www.example.edu/"]
}
```
But now it is like this:
```json
{
    "urls": [{
            "url": "https://www.example.com/"
        }, {
            "url": "https://www.example.org/"
        }, {
            "url": "https://www.example.edu/"
        }
    ]
}
```

**Comment by hellais** [comment]
The root cause of this was actually not inside of the apps, but rather inside of ooni/run itself which was generating invalid URLs (see: ooni/run#100).

A fix for this has been implemented and deployed, so we can consider this issue as solved.

**Comment by bassosimone** [comment]
Yes, thank you! I am going to create a separate issue for the iOS app crashing with the unexpected URL.

**Comment by bassosimone** [comment]
Here: https://github.com/ooni/probe/issues/1978
