### ISSUE TITLE
Fix copy formatting on crash reporting page

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1934]
During the OONI Partner Training 2021, participants mentioned that on **Apple SE iPhone**, the copy "We do our best not to publish your..." -- is cut off on the page accepting crash reporting. This needs to be fixed (if it hasn't already).

**Comment by hellais** [comment]
This has been fixed here: https://github.com/ooni/probe-ios/commit/8f3fcf90b286e7e9ffee18c4b8ea223f2f3470e4
