### ISSUE TITLE
Display list of websites before performing testing

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1935]
During the OONI Partner Training, participants mentioned that it would be useful if the OONI Probe app displayed the list of websites that they are about to test, before the testing is performed. 

This would allow users to **pre-screen** what they are about to test and potentially allow them to regenerate the list of sites. It would also enable them to **"disable" websites** that they don't feel comfortable testing. 

Many participants mentioned that it's unclear to them what categories of websites are being tested, nor whether those websites have been randomly selected.

This tickets is associated with https://github.com/ooni/probe/issues/1929.

**Comment by hellais** [comment]
We could implement this with a button in the choose websites section, where the user can tap on "Load from test list". When they tap on this button it will fetch the testing list and populate the custom list with backend provided URLs. At this point the user will be able to view and edit the sites they are about to test before running it.
