### ISSUE TITLE
Display total "Time remaining counter" instead of single timer for single test

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1936]
During the OONI Partner Training, participants mentioned that it would be useful if OONI Probe displayed a total "Time remaining counter" instead of relying on the single timer for the single test. This would help with understanding how much more time the tests should run as a whole.

Other participants also mentioned that from the UI of the OONI Probe app, it's unclear if the remaining testing time pertains to all tests in total, or to the specific test currently running. This suggests that we need to make relevant UX improvements.

**Comment by hellais** [comment]
This is related to: https://github.com/ooni/probe/issues/2021
