### ISSUE TITLE
Fix potential max runtime bug

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1940]
During the OONI Partner Training, a participant mentioned that although the app says that the max runtime is set to 90 seconds, it actually took 120 seconds to run. This may be a bug worth looking into to.

**Comment by hellais** [comment]
This is because the max runtime works by stopping scheduling any new tests once the timeout has been reached. That means that any still pending website test will need to run until the end and is the reason why it's never going to be exactly 90 seconds.
