### ISSUE TITLE
Add estimated runtime in OONI Probe CLI

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1943]
During the OONI Partner Training, participants mentioned that OONI Probe CLI doesn't include an estimated runtime (unlike the OONI Probe mobile and desktop apps, which do). It would be useful if this could be added to OONI Probe CLI.

**Comment by hellais** [comment]
OONI Probe CLI supports displaying the estimated runtime already.
![Screenshot 2022-01-19 at 16.47.09.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/2db8af18-a656-4f4a-b220-24ae35fcec2c)

Closing as invalid.
