### ISSUE TITLE
chore: import DoH servers from DNSCrypt/dnscrypt-resolvers

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1969]
This issue is about ensuring that the default static list of inputs for `dnscheck` included in [inputloader.go](https://github.com/ooni/probe-cli/blob/master/internal/engine/inputloader.go) includes all the servers mentioned at  https://github.com/DNSCrypt/dnscrypt-resolvers. We'll consider this task done when we'll have ensured we test all the servers mentioned in there.

**Comment by yeganathan18** [comment]
@bassosimone a little more information would be great since the repository contains a bunch of [servers](https://dnscrypt.info/public-servers/) and which ones should be added.

**Comment by bassosimone** [comment]
I _think_ we will support all the servers that support DoH. So, for the first iteration I recommend adding them.

**Comment by yeganathan18** [comment]
@bassosimone How to identify that a particular DoH server comes under `https`, `dot`, and any other protocol? Since I could find only the addresses (example: `dns.cloudflare.com`) and not the protocol for the same.

**Comment by bassosimone** [comment]
Hey @yeganathan18,

Thanks for asking clarifying questions!

> How to identify that a particular DoH server comes under https, dot, and any other protocol?

It seems that the website only lists DoH (i.e., DNS over HTTPS) resolvers. Thus, it's unclear to me whether they are also valid DoT (DNS over TLS) resolvers or cleartext DNS over TCP/UDP (collectively, DoH53) resolver.

I would say we focus mostly on DoH and possibly on DoT, ignoring other protocols. To this end, I explain below how to check whether a candidate resolver works as intended using `miniooni` and the `dnscheck` experiment.

> Also, after adding those servers how to make sure that it is working as expected? any specific tests?

Yes, so, given a candidate such as `adfree.usableprivacy.net`, you can test this domain for DoH with:

```
./miniooni -i https://adfree.usableprivacy.net dnscheck
```

Likewise, you can test for DoT with:

```
./miniooni -i dot://adfree.usableprivacy.net dnscheck
```

What `dnscheck` basically does, given an input URL, is this algorithm:

1. _bootstrap_, figure out IP addresses for the given domain (e.g., adfree.usableprivacy.net) using the system resolver;

2. it attempts a _lookup_ of `example.com` for each IP address resolved in the previous step using the protocol implied by the URL scheme (i.e., DoT is implied by using `dot://` and DoH is implied by using `https://`).

I'd like to encourage you to read more about dnscheck by reading the related [spec](https://github.com/ooni/spec/blob/master/nettests/ts-028-dnscheck.md#expected-output).

The _expected_ result should be that you're able to resolve the domain name to IP addresses and that you are able to perform a query with each IP address lookup. Then, maybe, if you don't have IPv6, like me, you will see that when you are using an IPv6 address, you are not able to use it to issue a query. To conclude, I would say we can say "it's working" if for the IPv4 addresses results we see there is no failure and we can issue a query for `example.com` and receive a reply.

**Comment by bassosimone** [comment]
Done!
