### ISSUE TITLE
desktop: download script for tor/torbrowser binaries fails because of stale URLs

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#1972]
The script `scripts/download-tor.js` uses hardcoded version numbers like `11.0.1` to construct the download links like `https://dist.torproject.org/torbrowser/${tor_browser_version}/tor-win64-${tor_binary_version}.zip`. The issue is that these links are not permanent. When newer releases are made, older ones seem to be removed from the repository. This in turn [breaks the build process](https://github.com/ooni/probe-desktop/runs/4531897910?check_suite_focus=true#step:9:94).

**To Reproduce**

```
$ yarn run download:tor
```

**Expected behavior**

It would be good to have a way to either use permanent links to the pre-built signed binaries, or make the script detemine the latest version(s) every time it runs.

**Comment by bassosimone** [comment]
Duplicates https://github.com/ooni/probe/issues/2028
