### ISSUE TITLE
tor: obfs4 handshake: ntor AUTH mismatch

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#1986]
**Describe the bug**

The 3.14.0-alpha.1 `miniooni` binary produces errors like this when running the `tor` experiment:

```
[      5.868423] <info> [ 51.4%] tor: access <endpoint>/obfs4: handshake: ntor AUTH mismatch:
  Derived: ca6172aa878f060de11829977745e805ce7de574092772b593761e98532a5a4a
  Received:5fba457b41d6b8294688bdaa7d247020137d174245ced1c01750f586b7ad6d57.
```

It's useful to know that the `release/3.13` branch does not show this issue.

**To Reproduce**

Just use 3.14.0-alpha.1 binaries.

**Expected behavior**

This error should not occur. I have no idea why it's occurring.

I can see that the `release/3.13` branch does not have this issue.

**Screenshots**

N/A

**System information (please complete the following information):**

This does not seem to be relevant.

**Additional context**

I'm doing QA of the upcoming 3.14 release.

We updated dependencies in preparation for the 3.14 release (among them `obfs4`).

**Comment by ainghazal** [comment]
it seems to me this is a side effect of yawning replacing the elligator2 implementation (that made it possible for a trivially distinguishable handshake) https://gitlab.com/yawning/obfs4/-/commit/393aca86cc3b1a5263018c10f87ece09ac3fd5ed

whether such failures are expected I'm not able to tell though.

**Comment by ainghazal** [comment]
I can confirm that the auth errors can be bisected to [393aca8](https://gitlab.com/yawning/obfs4/-/commit/393aca86cc3b1a5263018c10f87ece09ac3fd5ed). locally pinning the obfs4 dep to [e330d1b7](https://gitlab.com/yawning/obfs4/-/commit/e330d1b7024b4ab04f7d96cc1afc61325744fafc), over the `release/3.13` branch, the error doesn't show.

**Comment by ainghazal** [comment]
The client is aborting the connection, as expected by [step 6. of the spec](https://github.com/Yawning/obfs4/blob/master/doc/obfs4-spec.txt#L175). It looks like some times the AUTH computation doesn't match what server sends (my uneducated guess is that the server representative on old implementations does not always generate a valid key after the change to the correct elligator2 implementation).

In principle I had assumed backward compatibility would be in both directions, but the [README](https://gitlab.com/yawning/obfs4/-/tree/master/internal) only speaks of the representatives created by the **new** implementation being correctly decoded by existing implementations, not the other way around. It's probably wise to ask yawning if what we're seeing is expected or not (one way or another, bridge operators should be urged to upgrade asap, having trivial distinguishers out there is not nice).

```
Representatives created by this implementation will correctly be decoded
by existing implementations.  Public keys created by this implementation
be it via the modified scalar basepoint multiply or via decoding a
representative will be somewhat non-standard, but will interoperate with
a standard X25519 scalar-multiply.

As the representative to public key transform should be identical,
this change is fully-backward compatible (though the non-upgraded side
of the connection will still be trivially distinguishable from random).
```

**Comment by bassosimone** [comment]
I have temporarily downgraded `obfs4` in https://github.com/ooni/probe-cli/commit/f5e10e06e392eea1919d03d49014fbca1afe79cd for the `release/3.14` branch. We'll continue investigating this topic with @ainghazal and hopefully we'll fix it for the master branch.

**Comment by ainghazal** [comment]
Tor and Tails are aware of the problem. They discussed it in yesterday's meeting:

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40804#note_2779576

```
This issue is actually likely to be fairly complicated and it will require some investigation to fix properly. The team is working on it but it will take some time.
```

Let's keep an eye on that. I will curate the subset of "known good" bridges so that we can perhaps upgrade the obfs4 dependency but restrict ourselves to the problematic ones.

FWIW, my current understanding of the problem is that the problematic bridges, that fail with a stable frequency, are the ones that are not still upgraded, since they might be using representatives that are not understood as correct by the fixed code. And that _might_ be the right thing to do, I'm not sure if it's being argued that any other form of compat is desirable.

**Comment by bassosimone** [comment]
@ainghazal Thanks a lot for the update!

**Comment by ainghazal** [comment]
Tor is asking bridges to update; there's a new docker image that should hopefully make the process smoother. I guess the timeframe would for us since we'd be un-pinning for the next release.

**Comment by bassosimone** [comment]
So, @meskio, I did the following:

1. I verified that we're using the last version of yawning/obfs4.git

2. I run the `tor` experiment 16 times: only two bridges failed more than once and the table below summarizes the number of mismatch errors I observed for them
 
bridge | #mismatches | #attempts
-- | -- | --
38.229.33.83:80 | 13 | 16
38.229.1.78:80 | 10 | 16

3. both bridges are included into the results returned by https://bridges.torproject.org/moat/circumvention/builtin

**Comment by meskio** [comment]
Thanks for the info, I'll check what is happening with those bridges.

**Comment by bassosimone** [comment]
Thanks @meskio!

**Comment by bassosimone** [comment]
Since we still have some mismatches with a couple of bridges, I'm moving this issue over to release/3.16.

**Comment by bassosimone** [comment]
So, I have run ~10 tests today without seeing any AUTH mismatch. I have also updated the spec to mention this potential data quality issue. We can now close this issue as resolved. Thanks @meskio and @ainghazal!
