### ISSUE TITLE
quicping: experimental test that pings servers over QUIC

### ISSUE THREAD

**Issue by kelmenhorst** [ooni/probe#1994]
This issue is about developing an experiment that pings servers over QUIC. We consider a quic ping to be a single QUIC Initial packet (with no TLS handshake payload) which elicits a response from the target. 
This issue will be resolved when we have implemented such an experiment in `probe-cli/internal/engine/experiment` and tested its functionality.

There are two motivations for this issue:

1. We want to use quicping for testing the availability of UDP endpoints that leverage QUIC.
Since UDP has no acknowledgement mechanism, we cannot use raw UDP packets, without any application layer protocol, to test arbitrary UDP endpoints. The scope of quicping in regards to UDP availability is of course limited to UDP endpoints that support QUIC.

2. We want to use quicping to observe HTTP/3 / QUIC blocking in a more sophisticated way.
While OONI Probe can already detect HTTP/3 blocking, it is challenging to interpret the data as to what type of censorship was used.
Here's (one of the reasons) why: QUIC integrates TLS 1.3 encryption into the connection handshake. While this encryption by design is a security advantage of the protocol, it can be a challenge in terms of censorship measurement purposes: If the QUIC handshake with an HTTP/3 host fails, we cannot determine why it fails. Is the UDP endpoint blocked? Did the censor target the QUIC connection? Or is TLS censorship, e.g. SNI blocking, applied to QUIC traffic? 
While the challenge of differentiating UDP endpoint blocking and QUIC blocking will remain, we expect quicping to help us distinguish TLS censorship from UDP and QUIC blocking.

We aim for quicping to work like this:
- We create a QUIC Initial packet with random payload (i.e. no TLS handshake payload) and set the QUIC version to a version that the target server will not accept.
- We create a UDP socket and send the QUIC ping packet. If the server receives our packet, it will respond with a [Version Negotiation](https://www.rfc-editor.org/rfc/rfc9000.html#name-version-negotiation-packet) packet.
- If we receive the Version Negotiation response we know that a) the UDP endpoint is available and b) QUIC connection parameters are not targeted by censorship.

**Comment by bassosimone** [comment]
This work has now been completed, thanks @kelmenhorst !
