### ISSUE TITLE
oonireport: upload offline report files to OONI

### ISSUE THREAD

**Issue by kelmenhorst** [ooni/probe#2003]
This issue is about writing a Main for uploading offline-generated report files to OONI servers. We'll consider this issue resolved when we integrated such Main in `probe-cli/internal/cmd/oonireport` and tested its functionality. 

The oonireport client should run similar to this: `oonireport upload <file>`.

With oonireport we want to have a tool that can upload locally generated report files to OONI servers, any time _after_ the measurement. This may be necessary when OONI services are (temporarily) unavailable/blocked or when there is another reason to run a network test without the collector enabled.

**Comment by hellais** [comment]
It might be worth considering to write this code in such a way that it can also be used eventually to implement re-upload of not uploaded measurements in probe-cli, see: https://github.com/ooni/probe/issues/950.

**Comment by bassosimone** [comment]
Done in https://github.com/ooni/probe-cli/pull/682
