### ISSUE TITLE
httpx: clarify how BaseURL and URLPath combine

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2010]
This issue is about improving the documentation of `httpx` to clarify how BaseURL and URLPath combine. _En passant_, it may be needed to slightly adapt the code, in case the semantics is not the intended one (more on this below). We'll consider this issue resolved when we'll have documented the correct semantics and tested it's working as intended.

The correct/expected semantics is the following. Given a BaseURL `https://example.com/example` and an URLPath of `/foo/bar`, the code in `httpx` _should_ access `https://example.com/example/foo/bar`.

So, (1) if there's not one already, we need a test that _ensures_ we're behaving as described above and (2) the documentation of the `APIClientTemplate` should be very clear about how BaseURL and URLPath combine.

Especially if we need to change the implementation, then we should also ensure we're not breaking any other part of the codebase that is making use of the `httpx` package by running tests and manual code inspection.

**Comment by yeganathan18** [comment]
If the issue is still up, I would like to work on 🛠

**Comment by bassosimone** [comment]
Yes, please!

**Comment by bassosimone** [comment]
Done, thanks @yeganathan18!
