### ISSUE TITLE
android: cannot move app to SD-Card

### ISSUE THREAD

**Issue by niccokunzmann** [ooni/probe#2019]
## Expected Behavior

When I open the Apps settings of Android,
I select the app OONI Probe
I select the Storage option
Then, I would like to be able to move the app to the SD card

## Actual Behavior

Rigtht now, the apps seems only to be able to reside in the Internal Storage.

## Motivation

The app is quite big - several hundred megabytes - I do not have so much space on the Internal Storage. I would like to keep the app but move it to the SD-card.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 3.5.0 from F-Droid
  - Platform: Android 6
  - Subsystem:

**Comment by aanorbel** [comment]
The system delivers the [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED) broadcast before the external storage is mounted to the device. If your application is installed on the external storage, it can never receive this broadcast. This means the app will stop working properly(Automated test runs will be heavily impacted).

Android developer guides advice against allowing external storage of apps with `ACTION_BOOT_COMPLETED` permission. https://developer.android.com/guide/topics/data/install-location#ShouldNot

**Comment by aanorbel** [comment]
After various tries in code changes to allow the app to be moved to external storage, I think its best not to do so. Further explanations as to why this is not advised is found here https://android.stackexchange.com/tags/app2sd/info
