### ISSUE TITLE
fix background color in the experimental test group animation

### ISSUE THREAD

**Issue by hellais** [ooni/probe#2038]
When in dark mode the background color of the experimental test group is wrong.

We should make it transparent or find a way to make it look nice when in dark mode too.

See attached screenshot:
![Screenshot 2022-02-21 at 12 08 27](https://user-images.githubusercontent.com/424620/155305591-d9378963-cc33-4927-963f-845bca63966f.png)

**Comment by aanorbel** [comment]
Problem also exists in iOS
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-21 at 14 49 05](https://user-images.githubusercontent.com/17911892/159275318-dc4556cf-c881-4ef3-8300-414a2e9b1960.png)
