### ISSUE TITLE
probe-mobile: App crashes when users try to upload failed tests

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#2041]
A user reported that their OONI Probe app crashes every time they try to upload old tests. 

This suggests that the measurement upload functionality is not working properly, and should be investigated in order to ship a bug fix.

**Comment by aanorbel** [comment]
After trying to reproduce the errors around this, i looked into 
https://sentry.io/organizations/ooni/issues/2204928208/events/dc43f1712d7f48e18caa9050e542b777/tags/release/?project=5619989

Where I tested on the versions reported having the bug and was able to reproduce the error but did not crash the app. 
This excludes the error above from being able to cause the crash. 

Versions tested. 
- `2.11.0+75` - most crash of the above error from this version.
- `3.5.0`
- `latest`

**Comment by hellais** [comment]
Do we have enough information to reproduce the issue or troubleshoot it? If not, I suggest closing the issue.

**Comment by aanorbel** [comment]
Cannot be reproduced.
