### ISSUE TITLE
torProgressRegexp looks wrong but nevertheless mostly works

### ISSUE THREAD

**Issue by Em4E** [ooni/probe#2060]
https://github.com/ooni/probe-cli/blob/85664f1e31de0844f444af7c690a57628ff79ff7/internal/engine/experiment/torsf/torsf.go#L200-L201
```go
var torProgressRegexp = regexp.MustCompile(
	`^[A-Za-z0-9.: ]+ \[notice\] Bootstrapped [0-9]+% \([a-zA-z]+\): [A-Za-z0-9 ]+$`)
```

I was confused how the regex fragment `[a-zA-z]+` was matching strings with an underscore, like `conn_pt` and `onehop_create`. Look closely: the second `z`, which you would expect to be uppercase, is actually lowercase. The underscore character `_` (ASCII 95) lies between `A` (ASCII 65) and `z` (ASCII 122), which is why the regex works for its intended purpose, despite containing an evident typo.

I think `[a-zA-Z_]+` would express the intention more clearly.

**Comment by bassosimone** [comment]
Thanks a lot!

**Comment by ParitoshKabra** [comment]
can i change this small issue ?

**Comment by ParitoshKabra** [comment]
@bassosimone

**Comment by bassosimone** [comment]
Sure!

**Comment by ParitoshKabra** [comment]
Are `^` and ` also supposed to be matched anywhere? This code supports that also so I had the confusion @bassosimone  😅 ?

**Comment by ParitoshKabra** [comment]
Also for testing this out, how can I include this module from somewhere in the `tutorial/experiment/chapter01`, so that I can test regex accordingly for the logs

**Comment by bassosimone** [comment]
Done!
