### ISSUE TITLE
cli: Cannot build with Go 1.18

### ISSUE THREAD

**Issue by jefferyto** [ooni/probe#2066]
We (at the OpenWrt packages feed) recently updated to Go 1.18 and are updating the ooniprobe (probe-cli) package (https://github.com/openwrt/packages/pull/18268). We are seeing this error though when building v3.14.1:

```
# github.com/ooni/psiphon/tunnel-core/oovendor/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/ooni/psiphon/tunnel-core@v0.0.0-20220121102537-7fc0bcd97c5f/oovendor/quic-go/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```

Psiphon recently updated their copy of quic-go with 1.18 support (https://github.com/Psiphon-Labs/psiphon-tunnel-core/commit/86379faa8a2d6c757fe256e4a2fcc85f8c66eb63) but it is only on their master branch. I ran [update.bash](https://github.com/ooni/psiphon/blob/7fc0bcd97c5fecd9a8db0c1c01a10c51e5377a40/update.bash) in ooni/psiphon but because it checks out their staging-client branch, it did not pick up the updated code.

Are you able to ask the developers at Psiphon to update their staging-client branch? (It appears none of their GitHub repos have issues enabled.) Is there some other way to update quic-go in ooni/psiphon?

**Comment by bassosimone** [comment]
Thanks, yes, I will ask!

**Comment by bassosimone** [comment]
@jefferyto got a confirmation that they will merge `master` into `staging-client` soon. When this happens, I'll cut a point release to ensure you folks can build ooniprobe again. Thanks a lot!

**Comment by bassosimone** [comment]
@jefferyto okay, so I have pushed changes to ensure `master` works with Go 1.18. Also, I have tagged https://github.com/ooni/probe-cli/releases/tag/v3.14.2 that backported those changes. Thank you for letting us know!
