### ISSUE TITLE
Unable to view data for uploaded measurements. 

### ISSUE THREAD

**Issue by aanorbel** [ooni/probe#2140]
**Describe the bug**
Unable to view data for uploaded measurements. 

**Cause**

Accessing ```https://api.ooni.io/api/v1/measurements?report_id=<any-id>``` returns an unexpected response `502` from the server as seen below.

```html
<html>

<head><title>502 Bad Gateway</title></head>

<body>

<center><h1>502 Bad Gateway</h1></center>

<hr><center>nginx/1.18.0</center>

</body>

``` 

**To Reproduce**

- API level 
Access https://api.ooni.io/api/v1/measurements?report_id=20200813T210755Z_AS30722_k9rrM53GPiEyjfGD5kxvNy9F6FFvOBYedSOATjSmIDPReh6UcO  from the browser and the error appears.

- App-level
 Open a measurement detail older than a week and view DATA. Blank page appears after the app tries to fetch the data from the backend.

**Expected behaviour**

App Fetches data from the API and displays it to the user.

**Screenshots**

| Android      | iOS |
| ----------- | ----------- |
| ![Screenshot_20220612_221552](https://user-images.githubusercontent.com/17911892/173253952-642bd9e8-0388-46af-b255-dcc60a8100e9.png)      | ![photo_2022-06-12 22 17 35](https://user-images.githubusercontent.com/17911892/173253963-f29dfc18-337f-4c97-8a1a-9a0de00026bd.jpeg)       |

**System information (please complete the following information):**

- Device:  [iPhoneX, Huawei P30]
 - OS: [OS15.5, Android 10]
 - OONI Probe version: [3.6.1]

**Comment by aanorbel** [comment]
This failure also results to a failing CI builds and this PR trying to resolve the failing CI https://github.com/ooni/probe-ios/pull/489 , failing tests (https://github.com/ooni/probe-ios/blob/master/OONIProbeUnitTests/APITest.m#L33-L71 & https://github.com/ooni/probe-android/blob/master/app/src/test/java/org/openobservatory/ooniprobe/client/OONIAPIClientTest.java#L36-L92)

**Comment by FedericoCeratto** [comment]
Probes should use /api/v1/raw_measurement for this. Related to https://github.com/ooni/probe/issues/2146

**Comment by bassosimone** [comment]
Thanks for clarifying, @FedericoCeratto !
