### ISSUE TITLE
measurexlite: refactoring the dns implementation

### ISSUE THREAD

**Issue by DecFox** [ooni/probe#2208]
This issue is about changing the current DNS implemention in `measurexlite`. This involves two refactors:

1. We are currently storing dns results inside a map split by the `query` type. We want to simplify this by introducing a single buffer channel and leave the filtering (if required) as a post-processing step.
2. We want to simplify the construction mechanism for the DNS resolver which means initializing resolvers using non-anonymous functions (instead of the anonymous functions we use right now)

**Comment by bassosimone** [comment]
Done!
