### ISSUE TITLE
data quality: investigate increasing percentage of failures

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2260]
<img width="1255" alt="Screenshot 2022-09-06 at 15 30 42" src="https://user-images.githubusercontent.com/337298/188648142-1b976c5d-5610-401f-9a21-966d5a2750b8.png">

**Comment by hellais** [comment]
https://jupyter.ooni.org/notebooks/notebooks/2022%20%5Bfederico%5D%20test%20helper%20failure%20rate.ipynb

**Comment by hellais** [comment]
This failure was related to the rotation of test helpers.

**Comment by bassosimone** [comment]
We know the reason for the failure, so we can close this issue.
