### ISSUE TITLE
probe-desktop: Ensure Test Options settings apply as part of automated testing

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#2265]
To enable community members to determine *which* OONI Probe tests they want to have run automatically, we need to add support to OONI Probe Desktop to ensure that the **Test Options settings (configured by the user) apply as part of automated runs too** (in addition to manual runs). 

This is already supported in OONI Probe Mobile:

* Android: https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/PerformanceSuite.java#L34
* iOS: https://github.com/ooni/probe-ios/blob/master/ooniprobe/Test/Suite/CircumventionSuite.m#L14

This ticket depends on https://github.com/ooni/probe/issues/2267 being implemented first.

**Comment by hellais** [comment]
Implementation will follow as part of: https://github.com/ooni/probe/issues/2267
