### ISSUE TITLE
Add copy in Test Options screen to mention that test settings apply to both manual and automated runs 

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#2268]
As a follow-up to https://github.com/ooni/probe/issues/2265 and https://github.com/ooni/probe/issues/2266, we need to communicate to users that the **test settings** that they configure (e.g. disabling WhatsApp and Psiphon tests) via the Test Options settings of the OONI Probe app **apply to both manual and automated runs**. 

To this end, we could add a string in the Test Options screen (under the list of test categories), which says:

```
What you configure through the above test settings (e.g. disabling the WhatsApp test) will apply to tests run manually, as well as to tests run automatically (when automated testing is enabled). 
```
@majakomel adding the above to OONI Probe Desktop first depends on https://github.com/ooni/probe/issues/2267 and https://github.com/ooni/probe/issues/2265.

**Comment by aanorbel** [comment]
https://github.com/ooni/probe-ios/pull/501 and https://github.com/ooni/probe-android/pull/543 are 2 PR linked to this issue which resolved the issue on mobile.
