### ISSUE TITLE
www.jsf.mil: ssl_unknown_authority

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2329]
Measurements for http://www.jsf.mil/ fail with `ssl_unknown_authority`. As such, this issue is similar to https://github.com/ooni/probe/issues/2280 and https://github.com/ooni/probe/issues/1475.

[This measurement](https://explorer.ooni.org/measurement/20220930T083429Z_webconnectivity_IT_30722_n1_GQTQQsSUaXy058uH?input=http%3A%2F%2Fwww.jsf.mil) includes the `ssl_unknown_authority` failure along with interesting DNS failures in the system resolver and the UDP resolver (which are the same resolver on my system because of Vodafone Rete Sicura).

Additionally, it's worth noting that `http://www.jsf.mil/` is not working as intended and only `https://www.jsf.mil/` can be browsed, as confirmed by the [this measurement](https://explorer.ooni.org/measurement/20220930T083429Z_webconnectivity_IT_30722_n1_GQTQQsSUaXy058uH?input=http%3A%2F%2Fwww.jsf.mil)'s control results. Therefore, it would be more correct to change the test lists URL.

H/T @Arky for spotting this issue!

**Comment by arky** [comment]
I think the issue is that certain intermediates certificates are not handled in the code. Perhaps using alternative packages should plug the gap. 
 https://pkg.go.dev/filippo.io/intermediates

You can check the full list of Root certificates shipped by Firefox here: https://ccadb-public.secure.force.com/mozilla/PublicAllIntermediateCerts

**Comment by arky** [comment]
Browsers implement AIA fetching to handle missing intermediate certificates, full discussion [here](https://www.thesslstore.com/blog/aia-fetching/)

**Comment by bassosimone** [comment]
We [can measure the website now](https://explorer.ooni.org/m/20240125174137.408120_IT_webconnectivity_c171e6e03d93d63a) using Web Connectivity v0.5.

**Comment by bassosimone** [comment]
I think we're done here. I've also opened https://github.com/citizenlab/test-lists/pull/1623 to update the test lists.

**Comment by arky** [comment]
Thank you! @bassosimone I might need to retest this will new version at some point.
