### ISSUE TITLE
Android OONI Notification Constantly wakes up mobile screen.

### ISSUE THREAD

**Issue by arky** [ooni/probe#2330]
Android application constantly wakes up screen by updating notification. If the screen is turned off, ooni notifications constantly wake the device. This is annoying UX and also might drain the battery.

The solution/workaround I use to disable receiving notification in Android notification settings.  Perhaps this behavior needs to be optimized.

Steps to reproduce the behavior.

Ooni  on Android notifications constantly wake up mobile screen while running tests. 
Here is the testcase
Start running ooni tests (something that runs for a long time in the background)
Turn off the mobile screen.
The mobile screen constantly wakes up with active notifications about running tests.

**Expected behavior**

The expected behavior is avoid such constant notification when the device screen is turned off. 
**System information (please complete the following information):**

- Device: Android One / Nokia HMD
 - OS: 11
 - OONI Probe version: Latest build 

**Additional context**

**Comment by arky** [comment]
@aanorbel Am still facing this issue on Android devices. I have constantly disable notifications from ooni probe.

**Comment by aanorbel** [comment]
After running multiple tests, Its clear that the behavior of the notification is inconsistent across various devices and android versions.

- @arky 's device constantly wakes up
- Android 11+ devices don't show notifications when tests are being run [`Samsung Galaxy S21`, `Pixel 4 XL`].
- Android 10 device runs with notification shown and doesn't wake up the screen when the device is locked.
