### ISSUE TITLE
probe-cli: further the development of boilerplate tool 

### ISSUE THREAD

**Issue by kelmenhorst** [ooni/probe#2347]
The boilerplate command automatically generates experiment code. Developing this tool further will help rewriting experiments such as telegram, whatsapp and tor in the step-by-step style. 
The further development consists of the following points: 
- [ ] synchronize the template files in boilerplate with the fixes made in `internal/experiment/webconnectivity`
- [ ] develop telegram based on boilerplate
- [ ] consider automatic generation of tests

**Comment by kelmenhorst** [comment]
- [ ]  We want to extend boilerplate with an HTTP/3 flow template.

**Comment by bassosimone** [comment]
We are not going to use boilerplate for Web Connectivity v0.5. Rather, we're going to use dslx. I am going to close this issue since there has been a change of plans. We're going to create a new issue for the new line of work.
