### ISSUE TITLE
probe-cli: migrate database away from ooniprobe

### ISSUE THREAD

**Issue by DecFox** [ooni/probe#2352]
We want to migrate `cmd/oonirun/internal/database` away to `internal` and have a database abstraction. This allows us to have a standard database implementation.
This is part of the ooniprobe refactor: https://github.com/ooni/probe/issues/2351

**Comment by bassosimone** [comment]
@DecFox can we close this issue or are you planning to attach more pull requests to it?

**Comment by DecFox** [comment]
Done! We can close this issue now.
