### ISSUE TITLE
OONI Data Online Service for Researchers

### ISSUE THREAD

**Issue by arky** [ooni/probe#2385]
**Describe the bug**

One interesting way to drive the adoption of OONI data in research is remove the barrier of downloading the data. Perhaps in future a service could be launched where all the OONI data is hosted on SPARK  (or some other solution ) instance where research could run either SQL queries without the challenge of searching and downloading the data.

**To Reproduce**

Ability to query and analysis full data base using SQL query and advanced processing without programming experience.

**Expected behavior**

* Regular database dump imported into SPARK server 
* Allow users to run queries and do tasking 
* 
**Screenshots**

**System information (please complete the following information):**

- Device: [e.g., iPhone6]
 - OS: [e.g., iOS8.1]
 - OONI Probe version: [e.g., 3.11.0]

**Additional context**

**Comment by hellais** [comment]
This actually exists. If you have interest in getting accessing to a jupyter instance which has access to the research database, please write to me arturo@ooni.org and include:
1. Purpose of your research project
2. For how long you would need access to the platform
3. desired username
