### ISSUE TITLE
Initial Setup Fail

### ISSUE THREAD

**Issue by fakhamatia** [ooni/probe#2403]
**Describe the bug**

Show error after `ooniprobe autorun start`
`⨯ failure in main command   error=autorun: not implemented on this platform`

**To Reproduce**

1-`ooniprobe autorun start`
2-Answer to questions
3-After `Can we send crash reports to OONI?` show error (or after `Do you want to change the default settings?` if choose no) 

**Expected behavior**

Sow Result and finish setup

**System information (please complete the following information):**

 - OS: Ubuntu 20.04.4
 - OONI Probe version: 3.16.7

**Comment by bassosimone** [comment]
Thanks for reporting this issue! The `ooniprobe autorun start` command is only implemented on macOS. I think there is a way for us to avoid including the commands on systems that do not support it, so to avoid confusion.

**Comment by fakhamatia** [comment]
So how can set autorun on linux?

**Comment by bassosimone** [comment]
If you're using the Debian package, autorun is already implemented. If you're not using the Debian package, we don't have a way to enable autorun. I _suppose_ we could implement a command that writes a systemd unit.
