### ISSUE TITLE
Status information is hidden in dark mode

### ISSUE THREAD

**Issue by morachimo** [ooni/probe#2423]
**Describe the bug**

Status information is hidden in dark mode.

**To Reproduce**

1. Activate Dark Mode on iOS
2. Click on “Run” button, or, alternatively
3. Click on a “OONI Run” link (e.g. https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22https%3A%2F%2Frun.ooni.io%2Fnettest%3Ftn%3Dweb_connectivity%26ta%3D%257B%2522urls%2522%253A%255B%2522https%253A%252F%252Ftechcrunch.com%252F%2522%255D%257D%26mv%3D1.2.0%2527%2520class%3D%2527ooni-run-button%22%5D%7D&mv=1.2.0)

**Expected behavior**

Status information should be easily readable for users. However, because of the color choices for the text, the information is hidden with the background.

**Screenshots**

| Light Mode | Dark Mode |
|---|---|
|  ![IMG_3256](https://user-images.githubusercontent.com/3606242/223790107-7b187276-5f68-440d-8b43-d25615273878.PNG) |  ![IMG_3253](https://user-images.githubusercontent.com/3606242/223790169-5d82dbdc-0aa3-4255-adb4-f562ac670625.PNG) |
| Light Mode | Dark Mode |
| ![IMG_3255](https://user-images.githubusercontent.com/3606242/223790131-d6e038a2-a679-4354-80fa-1f3e1d4fcf78.PNG) | ![IMG_3254](https://user-images.githubusercontent.com/3606242/223790186-19e9de89-f1f8-486d-98dd-d9ae1617b096.PNG) |

**System information (please complete the following information):**

- Device: iPhone12
 - OS: iOS 16.3.1
 - OONI Probe version: 3.7.3

**Additional context**

I've seen versions of this bug in other platforms (e.g. #1392, #1499) with partial fixes. There's a good chance this is replicated in other screens, so maybe a more holistic approach is needed.

**Comment by aanorbel** [comment]
@morachimo  Thanks for reporting this issue. We are currently looking into it.
