### ISSUE TITLE
[UX] OONI Web Probe: URL Limit (0 for no limit)

### ISSUE THREAD

**Issue by arky** [ooni/probe#2438]
Perhaps rewriting this "URL Limit (0 for no limit)" as 'Run all tests" would make more sense for lay users.

![image](https://user-images.githubusercontent.com/808895/226449758-b8e0b2f4-0d8e-4308-8d3b-a293e92c92de.png)

The current text  is programmatically correct but very technical description for a simple task. 

**To Reproduce**

Go to https://probe-web.ooni.org/ 

Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**

- Device: [e.g., iPhone6]
 - OS: [e.g., iOS8.1]
 - OONI Probe version: [e.g., 3.11.0]

**Additional context**

**Comment by agrabeli** [comment]
Thanks @arky for the feedback! I agree that "URL Limit" is potentially confusing, and thanks for pointing this out.

Given though that OONI Probe Web only runs 1 test, I think we won't be changing the copy to "Run all tests". The goal of this "URL Limit" feature is to limit your testing to a specific number of websites (e.g 10 websites), as opposed to testing all websites in each run.

That said, I am thinking that given that OONI Probe Web doesn't test many websites in each run anyway, perhaps we can **remove this setting** entirely. I personally can't imagine a scenario where I'd want to test a specific number of websites, particularly if I can't determine which websites those are. @hellais what do you think? Should we remove this setting? That would also help reduce confusion.

**Comment by hellais** [comment]
This setting only applies to tests which include URLs. It's orthogonal to what settings you might have for other tests. For example if you have disabled certain tests, setting this to 0 will not make you run all tests.

As a result I think the text as it is now is correct. I think maybe we can come up with a better UI for this and we are working on it as part of the OONI Run v2 improvements.

As a result I think this ticket should be closed.
