### ISSUE TITLE
OONI Android Shows Website Error Page 

### ISSUE THREAD

**Issue by arky** [ooni/probe#2468]
**Describe the bug**

After installing the Android app. The results pane shows an error page.  Given that there hasn't been any tests run, you shouldn't show an error page as seen in the screenshot
![OONI-Results-Error-Page](https://user-images.githubusercontent.com/808895/236275566-1c50ddbd-8cb5-41de-aaa2-99a6c6a1c21f.png)

**To Reproduce**

1. Install OONI Experimental APK from github build page
2. Finish the onboarding and go to results pane. 
3. You will see the failed result page just before you run the test for the first time.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**

- Device: [e.g., iPhone6]
 - OS: [e.g., iOS8.1]
 - OONI Probe version: [e.g., 3.11.0]

**Additional context**

**Comment by aanorbel** [comment]
@arky , this is the default behavior of the app at this time. Once the test start running as seen on the screenshot, the state will appear as failed then updated subsequently to reflect the final state after the test is ran.

@bassosimone , I think we should include an initial state to avoid any confusion between tests that are still being run and tests which have run till completion and failed.

**Comment by bassosimone** [comment]
@aanorbel I agree
