### ISSUE TITLE
mobile: inconsistent handling of web_connectivity OONI-Run-v1 link without URLs

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2514]
**Describe the bug**

When given an OONI Run v1 link not containing any URLs (e.g., https://run.ooni.io/nettest?tn=web_connectivity&mv=2.0.0), the Android app fails with no input, while the iOS app runs nettests from the test lists.

The same happens for empty input (e.g., https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%5D%7D&mv=2.0.0).

**To Reproduce**

Just run the above OONI Run v1 link with both apps.

**Expected behavior**

_If_ we accept the assumption that OONI Run (v1 or v2) is a superset of running OONI Probe from the command line, then running the above link _should_ be equivalent to running `./miniooni web_connectivity`, which, _in turn_, means running URLs from the test list. Thus, in my opinion, the iOS app behavior is more correct than the Android app behavior.

**Screenshots**

N/A

**System information (please complete the following information):**

- Device: not relevant
 - OS: not relevant
 - OONI Probe version: https://github.com/ooni/probe-android/commit/11ec90fe4b19ac7da35767700979ad154a6c4ba6 and https://github.com/ooni/probe-ios/commit/8e59ca2238be6a4923bccf37a775adf1a024ac16

**Additional context**

N/A

**Comment by aanorbel** [comment]
I think the root cause here is that code path to handle the URL don't process the arguments in the same way.  while i think this should be corrected, i don't think it should block the current release.

**Comment by bassosimone** [comment]
Yes, I think we should tackle this problem after we have released for both iOS and Android.
