### ISSUE TITLE
Torsf example code results in broken pipe

### ISSUE THREAD

**Issue by imw** [ooni/probe#2523]
**Describe the bug**

When following the torsf net test tutorial, following the instructions results in a broken pipe.

**To Reproduce**
In probe-cli/internal/tutorial execute:
`go1.20.6 run ./experiment/torsf/chapter01 | jq`

**Expected behavior**

Output of the running experiment, concluding with pretty-printed experiment results.

**Screenshots**
![image](https://github.com/ooni/probe/assets/675213/15badea7-f411-4d14-bfa3-4443a82c5ca1)

**System information (please complete the following information):**

- Device: Thinkpad T25
 - OS: Debian 12 
 - OONI Probe version: n/a

**Additional context**

Fixup prepared [here](https://github.com/imw/probe-cli/tree/tutorial-output-fixup/internal/tutorial)

**Comment by bassosimone** [comment]
Fixed by merging https://github.com/ooni/probe-cli/pull/1193
