### ISSUE TITLE
Support go1.21

### ISSUE THREAD

**Issue by chenrui333** [ooni/probe#2585]
👋 right now there is some build issue with go1.21 due to outdated `github.com/Psiphon-Labs/psiphon-tunnel-core` dependency. error build log as below:

```
  go: downloading github.com/Psiphon-Labs/qtls-go1-20 v0.0.0-20230608214729-dd57d6787acf
  # github.com/Psiphon-Labs/quic-go/internal/qtls
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!psiphon-!labs/quic-go@v0.0.0-20230626192210-73f29effc9da/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/Psiphon-Labs/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

relates to https://github.com/Homebrew/homebrew-core/pull/151911

**Comment by bassosimone** [comment]
Thank you for pointing out this issue! In the interest of consolidating issues, I've referred to this issue into https://github.com/ooni/probe/issues/2548 and I am now closing this issue and keep the other one.

BTW, regarding _why_ Psiphon has not updated, I provided additional details at https://github.com/ooni/probe/issues/2548#issuecomment-1750034815.
