### ISSUE TITLE
probe-mobile: ooni run v2 questions for review of mobile app

### ISSUE THREAD

**Issue by hellais** [ooni/probe#2653]
* There are inconsistencies in how the pulldown for refresh works, we should check if that's ok
* Auto update of ooni run v2 links, how often should this happen

**Comment by aanorbel** [comment]
@jbonisteel , we need to discuss on how to fine-tune various UI that are inconsistent. Also deciding on how often updates should run would be helpful. Currently, auto-update is scheduled to run every 24 hrs.

**Comment by jbonisteel** [comment]
We will change the frequency of auto-updates so it runs every hour

**Comment by jbonisteel** [comment]
I am closing this issue for now, because it duplicates others, follow up work is tracked elsewhere
