### ISSUE TITLE
probe-desktop: Error invoking remote method 'list-results'

### ISSUE THREAD

**Issue by majakomel** [ooni/probe#2683]
**Describe the bug**
reported on Slack: https://openobservatory.slack.com/archives/C37L2J403/p1707549067365529?thread_ts=1706272035.082269&cid=C37L2J403
When I try to run the ooni probe, this error message appears and the Windows Defender blocking warning says blocking parts of the application. When checking this part, it appears that the application was detected by Microsoft as a Trojan.

**Screenshots**
![Captura de tela 2024-02-10 040856](https://github.com/ooni/probe/assets/3431279/8955dacf-3f15-4f47-b939-04dc23a4d0e9)
![Captura de tela 2024-02-10 041505](https://github.com/ooni/probe/assets/3431279/c1fb5d76-fa15-47c5-8898-6f6954928075)

**Log Files**
[renderer.log](https://github.com/ooni/probe/files/14236958/renderer.log)
[main.old.log](https://github.com/ooni/probe/files/14236959/main.old.log)
[main.log](https://github.com/ooni/probe/files/14236960/main.log)

**Comment by bassosimone** [comment]
The `ENOENT` error suggests `bin\ooniprobe.exe` does not exist. Could you check whether that's the case?
