### ISSUE TITLE
Feature request: set the number of tests for a customised test list in OONI Probe Mobile

### ISSUE THREAD

**Issue by sloncocs** [ooni/probe#2719]
For rapid response purposes, we often need to run **multiple tests** of the same list of websites. 

It would be much easier to run such tests if it would be possible to **set a number of tests** required for the given test list. 

E.g., media A, B, C are reported to be blocked in country N.

**What we do now:** 

1. Create an OONI Run link with URLs for A, B, C. 
2. Share OONI Run link with other OONI Probe users.
3. Users click the link, open the test 
4. Users click Run and wait till the end of the test
5. Once the test ends users click 'repeat' button and wait till the end of the test again 

Depending on the number of URLs and connection speed, the process can take many minutes. Most people run one test and close the app.

**What we could do:** 

1. Create an OONI Run link with URLs for A, B, C. 
2. Share OONI Run link with other OONI Probe users.
3. Users click the link, open the test 
4. User sets how many times they want to run this test 
5. OONI Probe runs the test the needed number of times in the background mode

**Comment by jbonisteel** [comment]
@sloncocs Run v2 enabled automatic testing of OONI Run links. So as long as users don't disable automatic testing, links will be tested automatically, multiple times, up to the date of the link expiry. So while a user doesn't dictate how many times the link is tested, it will happen multiple times. 

It might make sense to help test Run v2 and see if there is still any of this feedback that could apply, or if there is part of this feedback that could become an improvement for a future iteration of Run v2
