### ISSUE TITLE
The interface of the application doesn't adapt to large fonts 

### ISSUE THREAD

**Issue by sloncocs** [ooni/probe#2749]
**Describe the bug**
The interface of the application doesn't adapt to large fonts.
 
**To Reproduce**
Set the fonts to large and open the application. 

**Expected behavior**
The interface should be adaptive to the new size of the fonts. 

**Screenshots**
Example shared by the user: 
![Screenshot_20240610-141645](https://github.com/ooni/probe/assets/16296135/38b1ef70-f021-428e-8898-eab2ab1a5312)

**System information (please complete the following information):**

- Device: Pixel 6
 - OS: Calyx
 - OONI Probe version: 3.8.8

**Additional context**

**Comment by knghtbrd** [comment]
Adding myself to the issue. Happy to answer questions, test beta apks, etc. Have no experience building said apks, though I might even have all or nearly all the reqs installed already. The rest are a package manager away—I just assume y'all have better things to do than babysit a n00b if I have issues. 😉

**Comment by jbonisteel** [comment]
@aanorbel I imagine all platforms would have this issue. I imagine this would be easier to sort out once we have the multi-platform app ready?

**Comment by jbonisteel** [comment]
This should be better now, it is probably hard to get it perfect in all cases but this should be better. We have also been testing accessibility features in the new multi-platform app which will launch some time in 2025
