### ISSUE TITLE
Update Tor dirauths

### ISSUE THREAD

**Issue by meskio** [ooni/probe#2785]
Some directory authorities in the OONI test are outdated. Like moria1 has changed it's ports or faravar has changed it's IP. The up to date list of dirauths can be found at: https://gitlab.torproject.org/tpo/core/tor/-/blob/main/src/app/config/auth_dirs.inc

**Comment by DecFox** [comment]
Thanks for reporting this! We have updated the directory authorities in our servers and it is now in sync with the latest list.
