### ISSUE TITLE
Unable to submit measurement

### ISSUE THREAD

**Issue by Lanius-collaris** [ooni/probe#2786]
**Describe the bug**

Unable to submit measurement, but miniooni doesn't print any error and prints Measurement URL.

**To Reproduce**

Run a webconnectivity experiment.

**Expected behavior**

Can access the Measurement URL or miniooni prints error

**System information (please complete the following information):**

- Device: x86_64 PC
 - OS: fedora 40
 - OONI Probe version: miniooni 3.23.0-alpha

**Additional context**

Weird drop
https://explorer.ooni.org/chart/mat?since=2024-06-28&until=2024-06-30&time_grain=hour&axis_x=measurement_start_day&test_name=web_connectivity
https://explorer.ooni.org/chart/mat?since=2024-08-03&until=2024-08-05&time_grain=hour&axis_x=measurement_start_day&test_name=web_connectivity

**Comment by Lanius-collaris** [comment]
CC @ainghazal @sloncocs

**Comment by jbonisteel** [comment]
@Lanius-collaris we had a backend outage during that time where you see the weird drop on the explorer chart. I suspect this issue was caused by that outage. Can you confirm if things are working as expected now?
