### ISSUE TITLE
Redirecting report output to STDOUT

### ISSUE THREAD

**Issue by 0xPoly** [ooni/probe#415]
While working on [network meter](https://github.com/measurement-kit/network-meter) during the ooni mini-hackathon in Rome, we attempted to redirect the output of the report to STDOUT to be more easily parsed.

Running `ooniprobe -i some.deck -o -`  creates report files called `-.yamloo`.  `ooniprobe -i some.deck -o /dev/stdout` tries to create `/dev/stdout.yamloo` and fails due to lack of permissions.

Perhaps ooniprobe can detect the `-` option and redirect report output to STDOUT, or offer a way to specify file names while not adding the `.yamloo` extension.

**Comment by 0xPoly** [comment]
Talking to @bassosimone, we discussed how forcing you to write files to disk significantly reduces your plausible deniability. In network meter, we plan to bundle OONI by default - so if there are no disk traces it would be difficult to prove that you had run OONI and not just used any of the other measurement tools (like speed test).

**Comment by bassosimone** [comment]
@0xPoly I think `-o-` is better than `-o/dev/stdout` because the former makes sense also on Windows operating systems while the latter is more UNIX specific. (Also there is prior art regarding `-o-`; see for example `curl`, `wget`, and `tar`).

**Comment by hellais** [comment]
I like this a lot and it makes a lot of sense to support this. The only question I have is how to handle writing to standard out when you run a test deck.

In that we would have to take care of the following things either:

* handle buffering

* running of tests should happen sequentially when such flag is set

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #18](https://github.com/ooni/probe-legacy/issues/18) via [**ZenHub**](https://www.zenhub.com/)
