### ISSUE TITLE
ooniprobe in a browser?

### ISSUE THREAD

**Issue by d33tah** [ooni/probe#471]
Is there an implementation of oonprobe that would work in a browser, enabling censorship tests without installing any extra software? If not, would it make sense to create something like that?

**Comment by hellais** [comment]
Hi @d33tah this is a very good suggestion. Somebody did start making a version of ooniprobe for chrome, but I think it's not very much complete at this stage: https://github.com/m-lab/chrooniprobe.

It seems like the chrome dart API would support what we need (https://www.dartdocs.org/documentation/chrome/0.8.0/chrome.sockets/ChromeSocketsTcp-class.html, https://www.dartdocs.org/documentation/chrome/0.8.0/chrome.sockets/ChromeSocketsUdp-class.html), however given the fact that we are already implementing a library for running ooniprobe tests in C++ called [MeasurementKit](https://github.com/measurement-kit/measurement-kit), it probably makes more sense to orient energies towards implementing it as a [NativeClient](https://developer.chrome.com/native-client) for Chrome and using the [Mozilla build system](https://developer.mozilla.org/en-US/Add-ons/Creating_Custom_Firefox_Extensions_with_the_Mozilla_Build_System).
I don't have any experience working with either of those, but it would be great to start out by making a feasibility study of those to figure out how do-able it is.

**Comment by d33tah** [comment]
@hellais: so in other words: not unless we resort to native code? Would a stripped-down AJAX-only version make any sense?

**Comment by hellais** [comment]
@d33tah the problem with AJAX is that due to CORS you can't fetch arbitrary resources. There is an approach that allows you to learn something by loading favicon images and registering error handlers for them called Encore (http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p653.pdf), but it's very limited in what sites it can work for (they need to have a favicon) and the amount of data you can get from doing so.

**Comment by bassosimone** [comment]
Closing in favour of https://github.com/ooni/run/issues/19, which references this issue.
