### ISSUE TITLE
Expain the user configured options and what options should a user use/edit to opt-out from measurements

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#499]
Additionally we should document all privacy options in `ooniprobe.conf` file.

Relevant [discussion](https://github.com/TheTorProject/ooni-spec/pull/57#discussion_r62266791).

**Comment by hellais** [comment]
For reference, this is actually just about explaining that if the uses opts-out of geoip resolution we will not be able to strip their IP address from the HTTP response body (or headers) since we don't know their public IP address.
