### ISSUE TITLE
Offer an option to disable logging

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#501]
By default ooni-probe produces **high** amounts of log lines in `ooniprobe.log`.
An option to disable ooni-probe should be introduced in both `ooniprobe.conf` and command line options of ooni-probe.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #17](https://github.com/ooni/probe-legacy/issues/17) via [**ZenHub**](https://www.zenhub.com/)
