### ISSUE TITLE
Improvements to logging

### ISSUE THREAD

**Issue by hellais** [ooni/probe#502]
In discussing logging issues @anadahz it seems like ooniprobe generates too much logging information that is especially bad when running it on a raspberry pi.

I am going to propose that as part of reducing the amount of logs ooniprobe generates we do the following:
- [ ] Separate the logging to file from writing messages to the console (there are certain bits of information that are not needed in the log and are only useful to a user running ooniprobe)
- [x] Introduce log levels to separate critical logging from non critical logging
- [x] Add option to disable logging entirely (https://github.com/TheTorProject/ooni-probe/issues/501)
- [x] Add support for differentiating between standard error and standard output

**Comment by anadahz** [comment]
After discussion with @hellais I 'll add to this list:
-  Add support for STDERR logging to file
-  Ensure that logging applies to all ooni-probe components (oonideckgen, oonireport, ooniprobe, ooniresources)

**Comment by bassosimone** [comment]
Regarding logging, see also #415.

**Comment by hellais** [comment]
@anadahz what do you mean exactly by "Add support for STDERR logging to file"?

**Comment by anadahz** [comment]
@hellais 
Currently ooniprobe logging does not differentiate messages printed in stdout (screen output) and stderr (error messages output to the screen). It will be really useful and save a vast amount of disk space if the error log msgs could be save in a separate file rather than one log file.

Perhaps this is already implemented in:
`Add support for differentiating between standard error and standard output`

**Comment by hellais** [comment]
Hum, well what I have added support for in 109fffc864d946ad83d20a74c66639500960c5e8 is loglevels. This means you can set the loglevel to be, say, WARNING or ERROR and the logfile will only have in it error level messages.

Moreover now there is a distinction between stderr and stdout, in the sense that error messages are printed to the standard error output stream, while other messages are printed to the standard output.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #20](https://github.com/ooni/probe-legacy/issues/20) via [**ZenHub**](https://www.zenhub.com/)
