### ISSUE TITLE
s/ConfigParser/configparser/ in setup.py

### ISSUE THREAD

**Issue by oblivia-simplex** [ooni/probe#522]
Python 3.5.1, at least, expects the configparser module to be spelled without capital letters. This might be a recent change (I've seen the module spelled in CamelCase in a few places online). In any case, the problem can be fixed by changing line 93 to 

from configparser import SafeConfigParser

in setup.py

**Comment by hellais** [comment]
Thanks for the heads up, though there are still quite a few things we need to change in ooniprobe in order to support python 3.x. I am going to create a label python 3 so we can keep track of all the changes required to add support for it.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #21](https://github.com/ooni/probe-legacy/issues/21) via [**ZenHub**](https://www.zenhub.com/)
