### ISSUE TITLE
Add support for passing a custom resolver to the web_connectivity test

### ISSUE THREAD

**Issue by hellais** [ooni/probe#528]
Currently the web_connectivity test will only use the system resolver. This means that if the system of the user is configured to use a resolver that is not the canonical one you may not be detecting the presence of DNS based blocking.

One thing to take into account, though, is that if you are to pass a DNS resolver to perform the queries with the DNS client there will be inconsistencies with the resolver that is used by the HTTP client that instead will use the system resolver.

This came out of the discussion in https://github.com/TheTorProject/ooni-probe/issues/524

**Comment by hellais** [comment]
@bassosimone what do you think of this +1 or -1?

**Comment by bassosimone** [comment]
I would not override the resolver. Yet, it makes sense to perform a DoH and a DoT resolution with well known providers to (1) provide another data point for comparison and (2) opportunistically assess whether DoH and DoT work in that specific country.

I know this means exchanging more data but DNS queries are generally small and, especially for DoH, we have long running connections so we don't need to TLS handshake. Also, we can implement long running TSL connections for DoT when we dive deeper into this topic.

Also, if we're concerned with minimizing the data usage, I'd rather compress the data we submit than be stingy and not use some extra data for useful measurements.

I have created an issue for this idea I just proposed in this comment: https://github.com/ooni/probe-engine/issues/275.

For me, this issue should be closed.

**Comment by bassosimone** [comment]
I am going to mark this issue as WONTFIX. We don't want to allow for a custom resolver, rather we want to have more resolvers to determine whether there is also DNS blocking in place. Using a custom resolver is not good because it would make it more complicated to understand the results.
