### ISSUE TITLE
Add generic account for users that wish to submit bug reports anonymously

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#555]
A generic Github account should be made for users that would like to contribute and submit pull requests and issues without the need of subscribing to Github.
An account similar to Torproject Trac's [cypherpunks multi-user account](https://trac.torproject.org/projects/tor/wiki/WikiStart#UnofficialDocumentation).

**Comment by hellais** [comment]
People can email us bug reports to bugs@openobservatory.org.

We don't have plans to create an anonymous account on github.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ooni/probe/issues/555#issuecomment-555416086

It wouldn't even be possible, even if GH ToS allowed this, which it doesn't.
