### ISSUE TITLE
Unify tests with measurement-kit

### ISSUE THREAD

**Issue by willscott** [ooni/probe#558]
[Measurement Kit](https://github.com/measurement-kit/measurement-kit) Parallels many of the python tests implemented in Ooni-probe, but it's C code base allows it to span both desktop and mobile platforms. In the interest of having a single implementation of tests - both for consistency of what reports mean and to reduce the overhead in changing things - it would be great to migrate ooni-probe to use these tests.

There are several work items remaining in MK that we would like before this migration occurs
- [x] measurement-kit implementation of `http-header-field-manipulation` (https://github.com/measurement-kit/measurement-kit/issues/692)
- [x] bouncer communication (https://github.com/measurement-kit/measurement-kit/issues/693)
- [x] support for cloud-fronted backends (https://github.com/measurement-kit/measurement-kit/issues/694)

**Comment by hellais** [comment]
cc @bassosimone

**Comment by hellais** [comment]
These are now all done.
