### ISSUE TITLE
[EPIC] Refactoring of the ooniprobe task scheduler

### ISSUE THREAD

**Issue by hellais** [ooni/probe#563]
The current implementation of the scheduler has quite a bit of issues, that are hard to debug and I think this is due to the fact that it's poorly designed.

Some background information on why certain design choices were made in making these schedulers and why it turned out to be so complex.
1. I wanted a scheduler that had a fixed number of tasks running at any given time, but I also didn't want to have to spam the queue with all the tasks that have to be run. I wanted in particular to be able to schedule a python iterable (so for example something that reads the inputs from a file handle) and the scheduler should take care of consuming it at the right speed.
2. I wanted to be able to enforce a maximum amount of time for which a certain task should take and if it takes it longer it should be terminated.
3. I also wanted the scheduler to take care of handling retries independently from the exception that was raised.

I think these 3 special requirements are a bit in violation of the separation of concern principle and it probably makes more sense to have them being taken care of by the director or some other component.

I will write in this ticket the things I don't like with the current scheduler and propose a path towards refactoring it and making improvements to it.
### Critical issues
- The `_fillSlots()` method (https://github.com/TheTorProject/ooni-probe/blob/master/ooni/managers.py#L55) is called recursively that leads to using up the maximum stack depth allowed by python quite quickly if you have particularly high measurement concurrency, paired with measurements that are realised very quickly and a large input count.
- If an exception is raised between the acquisition of the task scheduling lock (https://github.com/TheTorProject/ooni-probe/blob/master/ooni/managers.py#L60) and the release of the task scheduling lock (https://github.com/TheTorProject/ooni-probe/blob/master/ooni/managers.py#L70) there is the possibility of starvation.
### Important issues
- The `TaskManager` and `Task` classes are very confusing because they have an interface that is basically the same, but they actually do pretty different things. I think it would be best to simplify these and aim for a more lightweight `Task` object.

Moreover while we are it with refactoring this it would also be very nice to have the scheduler be adaptive. By this I mean that the concurrency should not be something that is fixed and defined by the user, but should scale up or down depending on the speed and reliability of the network of the user.

In terms of how this can be achieved I think that doing an implementation that uses a `DeferredQueue` instead of our own custom queue managing code be ideal.
This stackoverflow answer has some example code on how something like this can be achieved: http://stackoverflow.com/a/2862440.

I believe these problems are related to what is reported inside of https://github.com/TheTorProject/ooni-probe/issues/541

**Comment by hellais** [comment]
Note: I have a unittest that reproduces one of the problems with the scheduler: https://github.com/TheTorProject/ooni-probe/blob/fix/scheduler/ooni/tests/test_nettest.py#L502

When a very low timeout for measurements is set (0.4 seconds) and the concurrency is set to a high enough value (30) the scheduler ends up stalling due to a maximum stack depth exception.

**Comment by bassosimone** [comment]
> I think these 3 special requirements are a bit in violation of the separation of concern principle

Can you further elaborate on this, please?

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #31](https://github.com/ooni/probe-legacy/issues/31) via [**ZenHub**](https://www.zenhub.com/)
