### ISSUE TITLE
Add examples and documentation for v2 decks

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#595]
This task is about generating documentation regarding the new deck syntax that will include relevant examples on how to use, create and modify ooniprobe v2 decks.

**Comment by hellais** [comment]
Some random notes on this topic:

Things to document in the v2 deck format:
- The common datastructure
  - name
  - description
  - schedule (is specified in cron format)
  - tasks is a list of ooni related tests
  - the task list will have key ooni
They looks like this:

```
tasks:
- ooni:
    test_name: http_invalid_request_line
    option1: value1
```

(Test name is always present and is a name of the tests)

Another important thing to mention is how to specify annotations and a custom collector on a per task basis:

```
annotations: {'annotation_key': 'something'}
```
Or custom collector:
```
collector: 'httpo://foo.onion'
```

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #54](https://github.com/ooni/probe-legacy/issues/54) via [**ZenHub**](https://www.zenhub.com/)
