### ISSUE TITLE
Be able to set time for scheduler through web-ui (2.x)

### ISSUE THREAD

**Issue by kaerumy** [ooni/probe#609]
We've learned from recent workshop in South East Asia, that in come countries like Myanmar and Cambodia that people turn off the power for entire office (or building) after working hours.

This is easily changed in crontab for older versions. A way to set repeating tasks via web-UI or console would be welcome.

**Comment by hellais** [comment]
Thanks for this feature request, I agree it would be a useful feature to have.

Though keep in mind that if the power is down or no network is available the scheduled deck will run the next time power is available or network connectivity is restored. That is to say the scheduler works more similarly to anacron, than regular cron.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #25](https://github.com/ooni/probe-legacy/issues/25) via [**ZenHub**](https://www.zenhub.com/)
