### ISSUE TITLE
Include more tor specific tests inside of default deck

### ISSUE THREAD

**Issue by hellais** [ooni/probe#614]
It would be great if we began shipping as part of the default enabled decks test that check for reachability of Tor and Tor bridges.

I would say we should include:
- [x] Test for vanilla tor (1)
- [ ] Test for bridge reachability with the tor browser bundle bridges (2)
- [ ] Test for bridge reachability with ooni specific bridges (3)

(1) Is fairly easy to do. (2) and (3) would require that we also have something in place that runs the test conditionally on whether or not the required pluggable transport software is installed (i.e. obfs4proxy) and (3) in particular would require that we get some dedicated bridges from the BridgeDB team (cc @isislovecruft).

**Comment by anadahz** [comment]
@hellais great idea.
I will be also adding to this default deck the meek fronted requests test.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #52](https://github.com/ooni/probe-legacy/issues/52) via [**ZenHub**](https://www.zenhub.com/)
