### ISSUE TITLE
Improvements to the vanilla tor test

### ISSUE THREAD

**Issue by hellais** [ooni/probe#615]
It would be great if the vanilla tor test did more than just use the Tor daemon but also:
- [ ] Checked for reachability of the bridge authorities by doing just a TCP connect
- [ ] Attempted variations of the tor SSL handshake to see which ones work and which ones don't

**Comment by hellais** [comment]
Closing this in favour of: ooni/probe#803

**Comment by bassosimone** [comment]
Oh, well, maybe a new issue is better, since reopening this old issue confuses Zenhub
