### ISSUE TITLE
smear load generated by scheduler

### ISSUE THREAD

**Issue by darkk** [ooni/probe#630]
New `croniter`-based scheduler ticks in UTC and runs `@daily` tasks at 0:00.

That may hammer low-traffic websites in lists as the lists are not shuffled on load.

Load smearing should satisfy following requirements:
- [x] prompt run after first installation
- [x] survive reboot & daemon restart in a sane way
- [x] be aware of the fact that the probe is not running 24/7

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #27](https://github.com/ooni/probe-legacy/issues/27) via [**ZenHub**](https://www.zenhub.com/)
