### ISSUE TITLE
web connectivity test input without http(s):// prefix

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#639]
Web connectivity test url option should either append http:// if no http(s):// is being supplied 
or inform the user that the test is not going to work for a given input (URL) that has no http(s):// prefix.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #28](https://github.com/ooni/probe-legacy/issues/28) via [**ZenHub**](https://www.zenhub.com/)
