### ISSUE TITLE
ooniprobe-agent: crashes under grsec: MemoryError in ctypes

### ISSUE THREAD

**Issue by pabs3** [ooni/probe#687]
### Description

ooniprobe-agent crashes under grsec with a MemoryError in the ctypes code

### Steps to Reproduce

1. Install Debian stretch
2. Install linux-image-4.8.0-1-grsec-amd64 4.8.7-1+grsec201611102210+1
3. Reboot into the new kernel
4. Install ooniprobe 2.0.1-2

**Expected behavior:** ooniprobe systemd service starts as per normal

**Actual behavior:** ooniprobe systemd service crashes

### Versions

**How did you install ooniprobe**

Debian packages

**What version of ooniprobe are you running?**

2.0.1-2

**What operating system are you running and what version is it?**

Debian stretch (8) with systemd

### Details

    systemd[1]: Starting Probe for Open Observatory for Network Interference...
    ooniprobe-agent[726]: Traceback (most recent call last):
    ooniprobe-agent[726]:   File "/usr/bin/ooniprobe-agent", line 11, in <module>
    ooniprobe-agent[726]:     load_entry_point('ooniprobe==2.0.1', 'console_scripts', 'ooniprobe-agent')()
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    ooniprobe-agent[726]:     return get_distribution(dist).load_entry_point(group, name)
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    ooniprobe-agent[726]:     return ep.load()
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2268, in load
    ooniprobe-agent[726]:     return self.resolve()
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2274, in resolve
    ooniprobe-agent[726]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/ooni/scripts/ooniprobe_agent.py", line 9, in <module>
    ooniprobe-agent[726]:     from twisted.scripts import twistd
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 13, in <module>
    ooniprobe-agent[726]:     from twisted.application import app
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 17, in <module>
    ooniprobe-agent[726]:     from twisted import copyright, plugin, logger
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/plugin.py", line 36, in <module>
    ooniprobe-agent[726]:     from twisted.python.modules import getModule
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 75, in <module>
    ooniprobe-agent[726]:     from twisted.python.filepath import FilePath, UnlistableError
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/python/filepath.py", line 38, in <module>
    ooniprobe-agent[726]:     from twisted.python.win32 import ERROR_FILE_NOT_FOUND, ERROR_PATH_NOT_FOUND
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/python/win32.py", line 172, in <module>
    ooniprobe-agent[726]:     formatError = _ErrorFormatter.fromEnvironment().formatError
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/dist-packages/twisted/python/win32.py", line 132, in fromEnvironment
    ooniprobe-agent[726]:     from ctypes import WinError
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/ctypes/__init__.py", line 552, in <module>
    ooniprobe-agent[726]:     _reset_cache()
    ooniprobe-agent[726]:   File "/usr/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    ooniprobe-agent[726]:     CFUNCTYPE(c_int)(lambda: None)
    ooniprobe-agent[726]: MemoryError
    systemd[1]: ooniprobe.service: Control process exited, code=exited status=1
    systemd[1]: Failed to start Probe for Open Observatory for Network Interference.
    systemd[1]: ooniprobe.service: Unit entered failed state.
    systemd[1]: ooniprobe.service: Failed with result 'exit-code'.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #37](https://github.com/ooni/probe-legacy/issues/37) via [**ZenHub**](https://www.zenhub.com/)
