### ISSUE TITLE
Test progress does not update dynamically

### ISSUE THREAD

**Issue by hellais** [ooni/probe#728]
As notes by @bassosimone in https://github.com/TheTorProject/ooni-probe/pull/719 in the web UI the test progress does not update dynamically, but it required you to refresh in order to see the updated progress.

There are various ways to implement this going from COMET to websockets. I think this is a general problem with the design of the Web UI.

**Comment by sirjamesgray** [comment]
also, the progress of tests is difficult to visualize. it needs to be improved so users can know when to kill the process in terminal.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #45](https://github.com/ooni/probe-legacy/issues/45) via [**ZenHub**](https://www.zenhub.com/)
