### ISSUE TITLE
Scheduler should allow for tasks that require no other tasks run at the same time

### ISSUE THREAD

**Issue by irl** [ooni/probe#740]
Some PATHspider tests make changes to system-wide configuration in order to generate the required traffic, e.g. the ECN test requires modifying a sysctl flag. If other tests are running during that test and there is path impairment to ECN, other tests may give false positives in their results as connections they make would be affected by the sysctl change.

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #51](https://github.com/ooni/probe-legacy/issues/51) via [**ZenHub**](https://www.zenhub.com/)
