### ISSUE TITLE
Update psiphon test to the latest version of psiphon

### ISSUE THREAD

**Issue by hellais** [ooni/probe#744]
Currently how we test is psiphon is working is by running the very old (and deprecated) python based test.

We should update to use the latest golang based client and possibly integrate it as part of measurement-kit.

Probably useful and related to this is also:
https://github.com/TheTorProject/ooni-probe/issues/653

**Comment by hellais** [comment]
Here is some feedback from Psiphon on how we can do this:

*Can you give us an up to date config file (we are using an old one and I believe that is not relevant anymore)?*

> The config file is obsolete and won’t work. We can make you a new one with modern config, although you need only make these changes to the one in that response to make it work:

```
4c4,5
<     "RemoteServerListUrl" : "https://s3.amazonaws.com/7l18-7ycd-gmnt/server_list",
---
>     "RemoteServerListDownloadFilename" : "server_list_compressed",
>     "RemoteServerListUrl" : "https://s3.amazonaws.com/7l18-7ycd-gmnt/server_list_compressed",
```

*What do we need to do to make this test more complete?*

> Test each obfuscation protocol, for one. By default, the client will try all protocols. To pin the client run to a single protocol, set the TunnelProtocol config value. The list of protocols along with other config documentation is here: https://godoc.org/github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon#Config.

*How do we compile psiphon as a library for iOS and Android?*

> Docs are under iOS/Android here: https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/master/MobileLibrary

> Or get an official build: https://github.com/Psiphon-Labs/psiphon-tunnel-core/releases

*How big is the library?*

> ~10MB

*Can you give us instructions for how to build client in Go? How do we link this with a C++ library?*

> Doc for building command line client: https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/master/ConsoleClient
> You can spawn this as a subprocess and consume its output. We do that on Windows. Or you can make it a library you link to, as we do on Android and iOS. We understand that Go now has support for building a static library that can be linked to C/C++, but have not done that.
> For libraries, we have a wrapper to simplify the interface: https://github.com/Psiphon-Labs/psiphon-tunnel-core/blob/master/MobileLibrary/psi/psi.go.

*How should a minimal set of psiphon functionality look like in a test?*
- eg. download list of servers?
- server select?
- try to connect?
- try to access site(s)?

> Run the client with the given config and no local data it it will bootstrap: download list of servers, select one to connect to, connect to it. Those tests could be combined into one step. To tunnel through the client, connect to its local SOCKS or HTTP proxy. You have the option of fixing the listening ports using the config params LocalSocksProxyPort and LocalHttpProxyPort, or monitor the output to see what ports are selected and reported.

> You can also monitor the output for the log `{"data":{"count":1},"noticeType":"Tunnels","showUser":false,"timestamp":"2017-07-19T15:38:11Z"}`, which shows that a tunnel has been successfully established. All the output is JSON so it can be parsed.

**Comment by hellais** [comment]
Moving this into the Measurement board so we don't forget to close when it's fully integrated.

**Comment by bassosimone** [comment]
I am going to close this issue, because:

1. I have moved the most relevant bit of information from the above conversation to https://github.com/ooni/probe-engine/issues/130

2. We already have https://github.com/ooni/probe-engine/issues/89 as top level issue
