### ISSUE TITLE
Add support for installing ooniprobe on windows

### ISSUE THREAD

**Issue by hellais** [ooni/probe#745]
It would be great if we could also support windows platforms.

I believe in particular what would need to happen is https://github.com/TheTorProject/ooni-probe/issues/654 and possible also more.

I have zero to none windows experience so it would be good to have more information on how it's best to do this.

I hear pyinstaller is a good way to go, but maybe py2exe is better.

**Comment by 0o0will0o0** [comment]
I second this issue, more computers are on Windows than Linux, and Python doesn't run on certain restricted computers. If you could make a standalone executable that doesn't need installation of any kind, it would be an enormus bump in usability, and userbase.

**Comment by hellais** [comment]
We now have a beta of the next generation OONI Probe app: https://github.com/ooni/probe-cli/releases/tag/v3.0.0-beta.1 & https://github.com/ooni/probe-desktop/releases/tag/v3.0.0-beta.1
