### ISSUE TITLE
How to get the category of the blocked website from terminal.

### ISSUE THREAD

**Issue by PravalikaRao** [ooni/probe#755]
I want to know the category of the blocked website like sports, technology, government etc., which is needed for my current research project. I have observed that it is specified when we run "list of globally accessed websites" in the web connectivity section in net tests in ooniprobe explorer.

**How can I upload my desired file of URLs in the OONI explorer that is in the user interface of OONI?**

![screenshotfrom2017-05-0513-01-34](https://cloud.githubusercontent.com/assets/26156720/25760046/00a55042-31a3-11e7-8a61-0ff283d92101.jpg)

In the above image, we can notice that there is no option for a user to enter their desired file for the test.

**I want the desired output as below for each URL which is blocked.**

![screenshotfrom2017-05-0514-00-08](https://cloud.githubusercontent.com/assets/26156720/25760100/2ef7088c-31a3-11e7-91ed-8145c62acef5.jpg)

**`Is there any possible way to get categories from terminal??`**

**Comment by hellais** [comment]
This is now possible with the next generation probe-cli: https://github.com/ooni/probe-cli/releases/tag/v3.0.0-beta.1.

Note: this is still just a beta.
