### ISSUE TITLE
How to properly cite OONI data

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#781]
This ticket is about the relevant citation style of OONI data.

**Comment by bassosimone** [comment]
I have no idea, @anadahz. Do you have a specific proposal?

**Comment by bassosimone** [comment]
I'm going to close this. Please, @anadahz, re-open if you have a specific proposal.

**Comment by anadahz** [comment]
@bassosimone Permalinks to OONI reports is perhaps a good idea.
