### ISSUE TITLE
This project could use a help-wanted or easy-pickings tag

### ISSUE THREAD

**Issue by danielquinn** [ooni/probe#791]
### Description

I just discovered this project today and thought it might be fun/interesting to get involved.  I have past experience working for the RIPE NCC and a lot of Python background, but I find myself looking for guidance regarding where I might be most useful, where I could start to get my bearings on the project, etc.

To help with this, I suggest you introduce tags for `help-wanted` and so-called `easy-pickings`.  The former will give people an idea of where they might be most useful, and the latter will be a gateway for new contributors.

**Comment by hellais** [comment]
Thanks for your interest in OONI, we actually have the easy label in this repo: https://github.com/TheTorProject/ooni-probe/labels/easy.

That said we are working in rewriting OONI Probe in golang to support windows and macos in a new desktop app.

If you want to get involved and contribute, the best thing would be to reach out to us on slack (or IRC) https://slack.openobservatory.org and we can give you some pointers.
