### ISSUE TITLE
 Every time I run only ooniprobe it fails

### ISSUE THREAD

**Issue by Baccount** [ooni/probe#793]
I ran ooniprobe using this command
`ooniprobe -i /usr/local/share/ooniprobe/current.deck`
When I visit http://2lzg3f4r3eapfi6j.onion/ I get this error `{"error": 405}`

Error message
Report ID: 20180510T231502Z_AS22773_nI1z1SG5zmHtgeWtEqStFytpCUM1qTwodV31sfZbefNuSlqrB0
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
[!] Lookup ​http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.

**Comment by hellais** [comment]
@Baccount can you clarify where you installed ooniprobe from and what is the content of `current.deck`. I don't see that onion as part of the OONI backends, so maybe you are running an outdated version of ooniprobe.

**Comment by Baccount** [comment]
I installed ooniprobe visa Brew, and I re-ran the command 
`ooniprobe -i /usr/local/share/ooniprobe/current.deck` and it seams to work correctly now. Thanks

**Comment by Baccount** [comment]
I still get this error after the test finishes.
```
Report ID: 20180728T005343Z_AS22773_lXxlxwe8nTsdiq7ZEzRVz05tPbpYIImszsys1lZmHumVP5G4P0
[!] Lookup http://2lzg3f4r3eapfi6j.onion/ failed. Retrying.
Error performing HTTP request: http://www.acdi-cida.gc.ca
```

**Comment by hellais** [comment]
Issue moved to [ooni/probe-legacy #41](https://github.com/ooni/probe-legacy/issues/41) via [**ZenHub**](https://www.zenhub.com/)
