### ISSUE TITLE
Handle concurrent Run Link tests gracefully

### ISSUE THREAD

**Issue by blazman** [ooni/probe#797]
Presently (using Android App) when one runs a https://run.ooni.io link probe while a previous run.ooni.io custom test is running, it ignores the newer one and completes the original one. However it doesn't provide any notice that the new one will not be run and the new one shows up in Past Tests as 'No results'. Preferably this should be handled more gracefully - the best result would be queuing the new test to be run once the first one completes. If not, at least giving a notice that a new test can't be run until the previous one is complete.

**Comment by hellais** [comment]
cc @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
@blazman can you provide more info? actually if you attempt to open an ooni run link while a test is in progress the run button is substituted by a spinning wheel making it impossible to press run before the  current one is completed.

**Comment by blazman** [comment]
@lorenzoPrimi hmm now that you've told me and I've tested it I see you're right. However there is a lag of 1-2 seconds where the 'Run' button is visible so when I first noticed the issue I was pressing the Run button succesfully. Now when I do it I wait a few seconds and the spinning wheel appears.

**Comment by lorenzoPrimi** [comment]
The bug is confirmed and will be fixed in the app v2.0. We'll come up with the most gracefully way to inform the user only one test at the time can be ran

**Comment by hellais** [comment]
Has this been addressed?

**Comment by lorenzoPrimi** [comment]
Definitely. It's a  1.x bug
