### ISSUE TITLE
Add tests for online gambling/betting sites censorship

### ISSUE THREAD

**Issue by stefanb** [ooni/probe#799]
Some countries block those, eg
https://www.bet-at-home.com/
https://www.bwin.com
And possibly others.

**Comment by hellais** [comment]
The list of websites to check for blocking are determined through the [citizenlab/test-lists](https://github.com/citizenlab/test-lists).

The global list, which is tested in every country, already contains some gambling websites: https://github.com/citizenlab/test-lists/blob/master/lists/global.csv, but if you think some important ones are missing you should file a pull request to that repository.
