### ISSUE TITLE
Add support for re-running any previously run test

### ISSUE THREAD

**Issue by hellais** [ooni/probe#801]
Currently in probe-mobile you can only re-run tests that have failed.

We should add support for re-running also non failed tests.

**Comment by hellais** [comment]
This is the relevant iOS ticket: https://github.com/ooni/probe-ios/issues/99

**Comment by lorenzoPrimi** [comment]
@elioqoshi we need some kind of UX for this if we want to include it in 2.1
Also, do we want to re run a single url or the entire set of urls of a test?

**Comment by hellais** [comment]
I think that especially in the case of OONI Run links it would be useful to be able to re-run a full set.

My concern with re-running individual results is that the user is going to end up with many websites results with a single entry.

Maybe what we can do is put a the rerun measurement inside of the result set as the first item. @lorenzoPrimi how doable do you think that is?

**Comment by lorenzoPrimi** [comment]
So be possible to re running only a set of websites, not a single one right?
This is easy to do, for the UX part I leave it to @elioqoshi 
But "linking" two sets needs some db structure

**Comment by elioqoshi** [comment]
I'd also suggest to re-run test set rather than single tests. The latter would not be even called "re-run" because you are basically just re-running a part of it. So semantically speaking, "re-run" should include all of the measurements in that test set

Eventually something like this could suffice:
![image](https://user-images.githubusercontent.com/5436686/52525045-116b1580-2ca4-11e9-883f-32dd509da214.png)


A confirmation dialog could be also shown (similar to when it asks to re-run a failed test).

**Comment by lorenzoPrimi** [comment]
Re-run is for websites, other test don't really matters in this context

**Comment by elioqoshi** [comment]
You sure? cc @hellais ?

But yeah,. the same pattern but on a Test Summary screen of a Websites test

**Comment by hellais** [comment]
@lorenzoPrimi is right. If you want to re-run an IM test or any test other than the websites one, you can just do it from the dashboard screen. The only test we currently have where it's relevant to support re-run (because the URLs tested change and are random) is the websites one.

**Comment by hellais** [comment]
I think this is a very important thing to support. It's especially useful for OONI Run links.

As part of this cycle I am going to finalise the mockups @elioqoshi shared and prepare it for the next sprint.

@lorenzoPrimi what do you think the development effort requires for this is? Can you add an effort estimate to this card?

**Comment by hellais** [comment]
I see you already estimated it as S, perhaps we want to already do this as part of the next sprint?

**Comment by lorenzoPrimi** [comment]
@hellais So for this card we should add a re run button in the website detail pages that rerun a website test with the same exact list.
Do we want to show a modal to the user before re running it? What's the copy?

**Comment by hellais** [comment]
> Do we want to show a modal to the user before re running it? What's the copy?

Yes I think we should show a modal saying:

You are about re-test 235 websites
[ Cancel ] [ Run ]

Where 235 is dynamic

Use the above text as placeholder and we can also get @agrabeli to look at it.
