### ISSUE TITLE
Design the circumvention tool tests in the OONI Probe apps

### ISSUE THREAD

**Issue by hellais** [ooni/probe#804]
In probe-legacy we had a series of tests that checked to see if circumvention tools were working or not (ex. `vanilla_tor`, `bridge_reachability`, `psiphon`, etc.), yet we haven't started porting or adding these to the new OONI Probe mobile and desktop apps.

This epic is used going to be used to track progress on implementing circumvention tool related tests to the apps.

In general to support circumvention tools at all we need to prepare the UIs of the apps to include a card for circumvention tool testing.

UI related tasks are:

* [x] Pick an icon and color for the circumvention tool tests
* [x] Define what settings (if any) we are going to expose
* [x] Define what "summary level" information is going to be exposed in the result listing view (ex. "2 apps tested 3 blocked")
* [x] Define what the other test details views are going to show to end users (this will probably change a lot depending on the type of test in question)

In terms of implementation, any new circumvention tool implementation will follow roughly this procedure:
* We document what the test aims to achieve as an `ooni/spec` (see: https://github.com/ooni/spec#new-proposal-process)
* We implement the test inside of measurement-kit
* If necessary, we make changes to https://github.com/ooni/orchestra in order to give out testing addresses (ex. https://github.com/ooni/orchestra/issues/51)
* The above UI tasks are completed and they are implemented as new views in probe-android, probe-ios & probe-desktop
* We ship this as part of a new app release 🚀 

Some tests we already have plans on implementing are:
* [Vanilla Tor](https://github.com/ooni/probe/issues/803)
* [Psiphon](https://github.com/ooni/probe/issues/744) (https://github.com/measurement-kit/measurement-kit/issues/1425)
* [tcp_connect based bridge reachability](https://github.com/ooni/probe/issues/802)

Other relevant issues include:
* https://github.com/ooni/spec/issues/109

**Comment by holantonela** [comment]
Hi! Starting to work on this ticket.

https://xd.adobe.com/view/583a7c33-770d-4b66-7677-3c081e178609-2e0b/

- The color we used for Circumvention tools data in Explorer revamp was Pink 6 `#e64980`. I think it is good, and we should keep it. Elio also left an icon for this test. I'm using it. Should we add it to https://design.ooni.io/icons/?
- I've worked on Probe Desktop, but the same approach will apply for Mobiles. 
- I'm looking at which data we have available [here](https://explorer.ooni.org/measurement/20191128T145358Z_AS134056_bfSYXbbO0G5aczuNhndremCDczZCZEBgj2g3HqYwTcIGXAvtNi). Is there anything else we should add? Do we have different results depending on the test (vanilla vs Psiphon vs bridges?

What else is needed? If this is ok then I'll move to Explorer to work on how we will visualize it.

**Comment by hellais** [comment]
This is a great start!

> Should we add it to https://design.ooni.io/icons/?

Yes. I filed an issue for it in the design-system: https://github.com/ooni/design-system/issues/72

> I'm looking at which data we have available here. Is there anything else we should add? Do we have different results depending on the test (vanilla vs Psiphon vs bridges)

Yes the data changes slightly depending on the type of test. I am not 100% sure what is the data currently available as the output of the psiphon test (@bassosimone can say more about this), but basing it on the old existing psiphon test (see: https://github.com/ooni/spec/blob/master/nettests/ts-015-psiphon.md), I would say as a minimum we can say the data to expose in the details view (that is the view you see when you click on the row of the circumvention tool tested, example: Psiphon):

* Success: `true` or `false`. Did the test determine that psiphon worked well or not?
* Bootstrap time: how long did it take for the circumvention tool to bootstrap a connection (may not be set in case the tool is blocked)
* Failure: this will be a string which will mention the reason for failure or the point in time in which the test failed to bootstrap. This information is a bit more technical, but we should still offer it in some way in the UI.

In the future once we do: https://github.com/ooni/probe-engine/issues/91, we will also have all the metadata that is present inside of the NDT test for each circumvention tool too (ex. download_speed, upload_speed, etc.).

@bassosimone am I missing something? Is there other information from the output of the psiphon test we would like to include in the UI?

**Comment by bassosimone** [comment]
@hellais @holantonela new Psiphon will have the same data format as before.

**Comment by hellais** [comment]
@holantonela 
> What else is needed? 

I am looking at the mocks you provided.

![Screenshot 2019-11-29 at 15 30 29](https://user-images.githubusercontent.com/424620/69875471-848a5a80-12bd-11ea-9e8f-b9468e4c0528.png)

Can you add to the mock scrolling of the innermost container should be handled?

That is to say if the navbar should be fixed and where the scrollbar for the inner section should go.

**Comment by holantonela** [comment]
Yes. You can also click on the prototype. If you feel it, we can add at fade-out at the top, but I don't think it is really needed.

https://xd.adobe.com/view/583a7c33-770d-4b66-7677-3c081e178609-2e0b/

![Test List@2x](https://user-images.githubusercontent.com/7602174/69878041-885cb380-12a2-11ea-8f7d-20fd2fe15a91.png)

![Test List – 1@2x](https://user-images.githubusercontent.com/7602174/69878040-885cb380-12a2-11ea-9f91-8ee9b301f984.png)

**Comment by hellais** [comment]
I will make some mockups for:

* Test results details view
* Test results overview
* Settings page

And also implement a animated loader

**Comment by hellais** [comment]
@sarathms here are some mockups for these.

Test results overview:
https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/6533b774-e302-417a-9b92-944ccf8d790a/Test-List-3

Test results detail:
https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/9f400cf9-8fa1-496a-b44b-6ede9d6c5419/Circumvention-test-details

Measurement result details OK (Psiphon)
https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/d9ba3b78-095d-43b7-9460-ad5674d254e6/Circumvention-test-details-1

Measurement result BLOCKED (Tor)
https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/2006ba2d-4f0c-4a65-bbcf-3b9b852348c9/Circumvention-test-details-2

I didn't have the circumvention test group icon handy, so I just used the IM test icons (or performance) as placeholders, but it should be apparent which icon needs to go where.

@holantonela had already mocked up the settings page. Here it is: https://xd.adobe.com/view/583a7c33-770d-4b66-7677-3c081e178609-2e0b/screen/87dfdfc7-d01b-4cd0-a7b4-adc46791b504/Circumvention-Configure

**Comment by hellais** [comment]
I would say all the work that needed to be done here is done. We should document any future work as new issues. Closing.
