### ISSUE TITLE
ETA of individual tests is not taken into account when re-running them (or via OONI Run)

### ISSUE THREAD

**Issue by hellais** [ooni/probe#805]
Currently the ETA of tests is that of a whole suite (ex. instant messagging = facebook + telegram + whatsapp). This means that if a user runs (via OONI Run or by re-running the test) a single test, they will have an ETA which is that of the suite and not just that of a single test.

**Comment by xanscale** [comment]
check ETA and progress bar

**Comment by lorenzoPrimi** [comment]
@hellais so should we do this in 2.0 or 2.1?
@xanscale don't forget this applies to oonirun, rerun single test and run test suite with some test deactivated.
New times:
PERFORMANCE_TIME 90 = 45 + 45
MIDDLEBOXES_TIME 15 = http invalid request line 10 + http header field 5
INSTANTMESSAGING_TIME 30 = 10 + 10 + 10

**Comment by lorenzoPrimi** [comment]
Fixed in iOS https://github.com/ooni/probe-ios/commit/cc3e46f5f9102a7ae3ef1c9f4a6f0e5655376c4d
Fixed in Android https://github.com/ooni/probe-android/commit/04deda230de328d74d8479a2d470577f3d72ee40

(I can't close this issue btw)
