### ISSUE TITLE
Auto delete old test json

### ISSUE THREAD

**Issue by gabelula** [ooni/probe#810]
We need to come up with an algorithm to delete old json tests when this is published on the explorer.
- [x] Implementation in android
- [x] Implementation in iOS

**Comment by hellais** [comment]
Even without #816 it's still possible to do this now with the current API.

How this would work is that the mobile app needs to save two bits of information: `input` & `report_id`. 

With these two bits of information you can query the API at:

`https://api.ooni.io/api/v1/measurements?report_id=$REPORT_ID&input=$INPUT`
(Note: INPUT only needs to be provided if the `report_id` is missing)

You will then get back a list keyed in `results`, where the first item in list (this list must have only 1 element unless there is a duplicate report_id) is the measurement you want to retrieve.

Example: https://api.ooni.io/api/v1/measurements?report_id=20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH

The value of the `measurement_url` if retrieved will give you the JSON content of the measurement.

This operation should be done only when the user taps of the `Show Data` button and the JSON can be deleted automatically from the device 24h after it has been submitted successfully.

Important bits to keep in mind are:

1. We need to ensure that the measurement has been processed by the pipeline (maybe before deleting we should check the api with the `/api/v1/measurements` query)

2. We need to ensure there was not an error in uploading the measurement

**Comment by lorenzoPrimi** [comment]
So when should we verify that every measurement (still with a JSON file) is already uploaded and delete the JSON? At every app start?

**Comment by hellais** [comment]
> So when should we verify that every measurement (still with a JSON file) is already uploaded and delete the JSON? At every app start?

Can we do it more frequently than that? Maybe every app start and when they navigate to the test result listing?

Is there a way to ensure that this check is done in the background and it doesn't affect the responsiveness of the app?

How will this perform if we have hundreds of measurements that need to be checked (and for each of them we need to do 2 web request to check them)?

**Comment by hellais** [comment]
> Everything will be done in background with no impact.

Ok that's perfect.

I guess we should just be careful to keep track of this state inside of the DB or app to avoid breaking when some action is done while the download is in the background (and possible race conditions).

> I have no answer to your last question I guess the app shouldn't start 200 requests in parallel, maybe is better to process them one by one so it doesn't affect much the bandwidth ?

Perhaps a good thing to do would be to have a thread pool with some level of concurrency in it (< 10), so that you will have at most N concurrent requests outgoing.

**Comment by lorenzoPrimi** [comment]
So to recap:
- Create a function that for every measurement with a json file to disk, calls the /measurements api and if  `measurement_url` exists, delete the json.
- This function can run up to 10 concurrent threads
- This function will be ran every app opening and when the app navigate to a specific test details screen
- When pressing the `Raw data` button, if the local json exists show the local json, otherwise call that url and show `measurement_url`

**Comment by lorenzoPrimi** [comment]
@hellais when I call `api/v1/measurements` and that measurement is in the explorer, should I save the `measurement_url` in the database?
In brief what will be the procedure when tapping on `Show Data` and there is no `json` saved in the app, meaning that has been deleted? 
Calling the api and retrieving the url every time or having the url already in the db?

**Comment by bassosimone** [comment]
> Calling the api and retrieving the url every time or having the url already in the db?

No. Redo the query every time. When OOID will be implemented, it will be a different, more simple query, and getting a measurement would be less toil.

**Comment by hellais** [comment]
Yes exactly, what @bassosimone says is accurate.

The only source of truth should be the `report_id, input` tuple. 

The measurement_urls if you check the path they specify the `temp-` prefix which indicates that they are going to change and are not to be considered a permalink.

**Comment by lorenzoPrimi** [comment]
Closed by:
https://github.com/ooni/probe-ios/pull/292
https://github.com/ooni/probe-ios/pull/293
https://github.com/ooni/probe-ios/pull/295
https://github.com/ooni/probe-ios/pull/297
https://github.com/ooni/probe-ios/pull/300
And(roid)
https://github.com/ooni/probe-android/pull/244
https://github.com/ooni/probe-android/pull/246
https://github.com/ooni/probe-android/pull/249
https://github.com/ooni/probe-android/pull/250
