### ISSUE TITLE
Log file too big

### ISSUE THREAD

**Issue by gabelula** [ooni/probe#811]
What to do with the log files when they get really big.

**Comment by bassosimone** [comment]
I don’t understand the issue. Is the problem that too much disk space is consumed by different logs? How about recycling the name of the log file or deleting it after a few tests? (This seems to me an app specific policy question for which I don’t see how a mechanism built into MK could help)

**Comment by hellais** [comment]
I agree with @bassosimone, I think log rotation should be handled in a platform specific way.

This is also related to: https://github.com/ooni/probe-cli/issues/24.

**Comment by lorenzoPrimi** [comment]
@bassosimone This is an issue you pointed out in Mexico City, basically logs are useful and if there are a lot of them stored there is a lot of space taken by them.
So when should delete a log file for a specific test? After a day, a week, a month, never?

**Comment by bassosimone** [comment]
I believe three days is fine.

**Comment by elioqoshi** [comment]
Could we have a setting for this in "Advanced" to set the number of days after which logs get deleted and the user sets that themselves (with the default 3 days)?

Or would that be an unreasonable effort/benefit ratio?

**Comment by lorenzoPrimi** [comment]
Or maybe not having the auto delete feature at all and having a label saying how many MB logs takes and a Clean all button?

**Comment by elioqoshi** [comment]
Sure, that seems reasonable as well.

**Comment by bassosimone** [comment]
@lorenzoPrimi is this still icebox?

**Comment by lorenzoPrimi** [comment]
I would leave this after "Clean submitted reports"

**Comment by lorenzoPrimi** [comment]
For now we'll remove logs of submitted (and published) reports. This ticket will remain open to study what is the best way to remove old/unnecessary logs

**Comment by lorenzoPrimi** [comment]
Closed by https://github.com/ooni/probe-ios/pull/299
and https://github.com/ooni/probe-android/pull/249
