### ISSUE TITLE
Reminder notification to run a test

### ISSUE THREAD

**Issue by gabelula** [ooni/probe#812]
Tap on reminder notification to run a test.

**Comment by elioqoshi** [comment]
How would this play out? Would the test be started right away? Would a modal menu ask the user first whether they want to run that test (similar to opening up a OONI Run link)?

**Comment by lorenzoPrimi** [comment]
I guess like it worked in 1.x so local push notification every day at 18:00 (time customizable) so remind the user to run tests.
Sounds me like my fitness app that reminds me to do some push ups! :D 
@hellais @agrabeli was one of you who proposed to reintroduce this feature?

**Comment by hellais** [comment]
I guess this is kind of a workaround for the fact that users can't opt in to automatic testing anymore on Android.

I am not super convinced by the fact that this is a good idea especially in light of the fact that we will have in the future a very similar feature (via orchestration) and we may end up confusing users by implementing this one before then.

**Comment by lorenzoPrimi** [comment]
I agree, also because in 2.2 I would like to push user to enable push notification to trigger users in particular areas to run test when needed

**Comment by lorenzoPrimi** [comment]
Closing as is not relevant anymore

**Comment by elioqoshi** [comment]
> Closing as is not relevant anymore

@lorenzoPrimi What is the context again for this?

**Comment by lorenzoPrimi** [comment]
@elioqoshi remind users once a day to run tests
