### ISSUE TITLE
Configure fastlane deliver to automatically upload screenshots

### ISSUE THREAD

**Issue by gabelula** [ooni/probe#815]

**Comment by lorenzoPrimi** [comment]
iOS ticket : https://github.com/ooni/probe-ios/issues/150

**Comment by lorenzoPrimi** [comment]
Android ticket: https://github.com/ooni/probe-android/issues/125

**Comment by lorenzoPrimi** [comment]
Already included in https://github.com/ooni/probe/issues/903
