### ISSUE TITLE
Being able to share a link to the ooni explorer

### ISSUE THREAD

**Issue by gabelula** [ooni/probe#816]
Sharing a ooni explorer link instead of a screenshot

**Comment by hellais** [comment]
This is dependant on the data processing pipeline (or speed layer) processing measurements at less than hourly speed.

**Comment by gabelula** [comment]
ok. Getting it out of 2.1.

**Comment by darkk** [comment]
> the data processing pipeline

Or on OONI Collector stamping OOID on the measurement (that is kinda independent task).

**Comment by hellais** [comment]
> Or on OONI Collector stamping OOID on the measurement (that is kinda independent task).

Right. I would say *and* though, since we should not have a sharing feature in the apps if it still takes several hours for the shared link to become "live"

**Comment by elioqoshi** [comment]
> Right. I would say and though, since we should not have a sharing feature in the apps if it still takes several hours for the shared link to become "live"

Can't we have a "parking" page which tells the users that this measurement is still being processed when that's the case? That would make it independent from how fast the processing pipeline runs as @darkk suggested. If that's the case, it could make sense for 2.1

**Comment by hellais** [comment]
> Can't we have a "parking" page which tells the users that this measurement is still being processed when that's the case?

We could do that, but I guess this would have to be implemented in OONI Explorer, which is currently being revamped and I am not sure it's worth investing effort in developing new features for something which is going to have a new version out soon.

**Comment by lorenzoPrimi** [comment]
I guess this one depends on the new OONI explorer, we might want to publish it with the new version of the explorer. When should be released?

**Comment by hellais** [comment]
Another challenge with the "parked" page is that given the current architecture of the data processing pipeline and how measurements are exposed by the API, we don't really have a way of distinguishing between a measurement that has been uploaded, but is still being processed by the pipeline vs a measurement that does not exist.

**Comment by hellais** [comment]
> I guess this one depends on the new OONI explorer, we might want to publish it with the new version of the explorer. When should be released?

Yes exactly.

We are aiming to have a beta out by April 2019: https://github.com/ooni/explorer/milestone/1.

I added an issue for this here: https://github.com/ooni/explorer/issues/49.

**Comment by darkk** [comment]
> we don't really have a way of distinguishing between a measurement that has been uploaded

OOID carries submission timestamp by design, so it's a way to estimate the distinction between these two cases.

**Comment by hellais** [comment]
> OOID carries submission timestamp by design, so it's a way to estimate the distinction between these two cases.

True, this can be useful to spot cases in which the requested measurement is for sure not valid (if it's a measurement from the future), but not too spot cases in which it may be valid (the timestamp is consistent), yet it's actually isn't (because no measurement was actually submitted at that time).

To recap, I think that requirements to this happening are:
* [ ] OONI Explorer next is rolled out (at least in beta stage), this is a hard dependency to this
* [ ] OOID is implemented and working (see: https://github.com/ooni/pipeline/issues/48)
* [ ] There is a speed layer that deals with measurements as they are coming in (XXX file a ticket for this). This is not a strict requirement, but it would be a nice thing to have

**Comment by hellais** [comment]
This has been implemented in the latest version of OONI Probe mobile even without the ooid.

The workaround is that we will show an alert if the measurement is not yet available in OONI Explorer, but still allow the user to copy the link.
