### ISSUE TITLE
Add support for sending email to support

### ISSUE THREAD

**Issue by hellais** [ooni/probe#819]
We should expose functionality (in the setting?) for sending an email to support@ooni to report bugs and get help using the app.

It should work in this way:

Item Send email in `Setting` page, before `About`
The key string will be `Settings.SendEmail.Label`
Icon : https://material.io/tools/icons/?icon=live_help&style=baseline
Tapping on the row will open the mail composer prepopulated with
`To:`  bugs@openobservatory.org
`Subject:` [bug-report] OONI Probe Android/iOS 2.x.y
`Body:` Device model: Samsung Galaxy / iPhone X (add as many details as you can)
Error string `Settings.SendEmail.Error` = `No email clients configured on your device` 

- [ ] Implementation in android
- [ ] Implementation in iOS

**Comment by elioqoshi** [comment]
Thanks, that looks fine to me. @lorenzoPrimi @xanscale let me know if you need help with this based on the description @holantonela gave.

**Comment by elioqoshi** [comment]
@lorenzoPrimi I'd suggest: https://material.io/tools/icons/?icon=live_help&style=baseline

**Comment by lorenzoPrimi** [comment]
So to recap:
Item Send email in `Setting` page, before `About`
The key string will be `Settings.SendEmail.Label`
Icon : https://material.io/tools/icons/?icon=live_help&style=baseline
Tapping on the row will open the mail composer prepopulated with
`To:`  contact@openobservatory.org
`Subject:` [bug-report] OONI Probe 2.x.y

**Comment by lorenzoPrimi** [comment]
@elioqoshi I tried to use that icon without luck, I don't know how to make it same size as the others, after exporting it, can you insert it into an xd file?
![simulator screen shot - iphone 8 - 2019-01-29 at 16 15 59](https://user-images.githubusercontent.com/1616097/51897388-37113880-23e1-11e9-9a0f-580598a775a2.png)

**Comment by lorenzoPrimi** [comment]
@hellais maybe we want to add the user device model in the body?

**Comment by elioqoshi** [comment]
@lorenzoPrimi can you send me one of the other icons so I can take that as base for the sizing?

**Comment by lorenzoPrimi** [comment]
@elioqoshi at the moment I only have pdf (ios )or xml (android). Check the icons in the xd file, I exported them from there

**Comment by hellais** [comment]
> maybe we want to add the user device model in the body?

Yes that would be a good idea.

**Comment by elioqoshi** [comment]
@lorenzoPrimi is this clear to go?

**Comment by lorenzoPrimi** [comment]
@elioqoshi yes, I modified the first message to have all information there

**Comment by lorenzoPrimi** [comment]
iOS Done, there is a bug in the latest iOS you can't customize font and color of the title in the nav bar:
https://stackoverflow.com/questions/52522308/change-title-color-of-navigation-bar-in-mfmailcomposeviewcontroller-in-ios-12-no

![img_6503](https://user-images.githubusercontent.com/1616097/52633131-0dcecd00-2ef6-11e9-974c-20e7d6bee8b0.PNG)

**Comment by lorenzoPrimi** [comment]
In Android there are maybe too much information I would strip a lot of them @xanscale 
![7296832719422492829](https://user-images.githubusercontent.com/1616097/52634945-18d82c00-2efb-11e9-854a-59a3807bb569.png)

Pull request: https://github.com/ooni/probe-android/pull/193

**Comment by elioqoshi** [comment]
> iOS Done, there is a bug in the latest iOS you can't customize font and color of the title in the nav bar

Not a huge deal since it's not something users will faces every day. Let's keep it in mind to fix it when it's possible.

**Comment by xanscale** [comment]
@lorenzoPrimi @hellais @bassosimone @elioqoshi 

which of the following data we want to keep in mail ? all ?

BOARD: blueline
BOOTLOADER: b1c1-0.1-5155331
BRAND: google
DEVICE: blueline
DISPLAY: PQ2A.190205.001
FINGERPRINT: google/blueline/blueline:9/PQ2A.190205.001/5163636:user/release-keys
HARDWARE: blueline
HOST: wprf6.hot.corp.google.com
ID: PQ2A.190205.001
MANUFACTURER: Google
MODEL: Pixel 3
PRODUCT: blueline
TAGS: release-keys
TIME: 1543987901000
TYPE: user
USER: android-build
RADIO_VERSION: g845-00009-181130-B-5157073

**Comment by lorenzoPrimi** [comment]
For me keep only MANUFACTURER and MODEL, don't think we are interested in the other things

**Comment by hellais** [comment]
I think `TIME` could also be a useful element to submit.

Are `MANUFACTURER` and `MODEL`, specific enough? Maybe there is something like the US version of the Pixel 3 which has a completely different CPU or something like that.

Myabe `HARDWARE`, `DEVICE`, `BOARD` are also useful to have?

**Comment by lorenzoPrimi** [comment]
Ok I let the last word to @xanscale 
I would leave for sure `MANUFACTURER` and `MODEL`
`HARDWARE`, `DEVICE`, and `BOARD` only if they tell us something we don't know. but they seems to be all the same
`TIME ` is useless if it's the current time IMHO

**Comment by hellais** [comment]
TIME is useful, because the system clock may be very off (think many days)
and this could lead to bugs.

Il giorno 4 marzo 2019 @ 15:12:28, Lorenzo Primiterra (
notifications@github.com) ha scritto:

**Comment by xanscale** [comment]
A volte ad un nome commerciale unico corrispondono più device con caratteristiche diverse. Ad esempio i Samsung Galaxy S in base alla zona vengono commercializzati con il processore Snapdragon o con Exinos.

MODEL é il nome commerciale
Uno tra BOARD, DEVICE e HARDWARE é il nome univoco

Sarebbe da provare con un telefono non pixel

**Comment by lorenzoPrimi** [comment]
I will try my nexus later

**Comment by lorenzoPrimi** [comment]
Same thing. We will test on different devices and then we'll decide what to keep.
`MANUFACTURER`, `MODEL` and `TIME ` for sure
And one between `HARDWARE`, `DEVICE`, `BOARD` if useful.

**Comment by elioqoshi** [comment]
Is spending time on testing necessary? Any downsides of having 1 or 2 more fields just in case?

**Comment by lorenzoPrimi** [comment]
As there is no hurry to approve this PR and this code is done, we can wait to get hands on more device and check which fields to keep and which one to remove
