### ISSUE TITLE
Change string used for viewing logs

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#824]
Rather than "View log", which is long, I'd say "Log >" that occupies less space and visually gives the information than one can go to the next screen to actually see logs.

This will be also more consistent with the fact that "< Back" allows actually to go back.

![fullsizerender](https://cloud.githubusercontent.com/assets/337298/23562574/49572c48-0043-11e7-8bf4-ca3b5793d30e.jpg)

**Comment by lorenzoPrimi** [comment]
@elioqoshi I transfered this to probe because is relevant to both app, but I would close it as "View Log" is much better than "Log". Your call.

**Comment by elioqoshi** [comment]
View Log is fine as it's not a long label I'd say. But I don't have a strong opinion on this.

Last Log for Jira is using the same:
https://marketplace.atlassian.com/apps/1211604/last-log-for-jira?hosting=server&tab=overview

**Comment by lorenzoPrimi** [comment]
Furthermore there is no such thing as `>` icon in iOS.
