### ISSUE TITLE
Detect when the user changes network

### ISSUE THREAD

**Issue by hellais** [ooni/probe#828]
It would be useful to detect in the mobile apps when a user changes network (either from 3g to wifi or vice-versa as well as from one wifi hotspot to another).

When they do change network (and a test is running) we should do one of two things:

* Interrupt the currently running test and possibly close it (question: should we mark the test as aborted in some way)
* Suspend the test and wait some amount of time for them to reconnect to the wifi hotspot in question

For the closing of the report it may be the case that the network they are connected to does not have data enabled on it (captive portal, roaming, etc.).

Related tickets:

* https://github.com/TheTorProject/ooniprobe-ios/issues/82
* https://github.com/TheTorProject/ooniprobe-android/issues/47

**Comment by elioqoshi** [comment]
Is it possible to cancel tests without breaking anything? i.e discarding any progress made until that point on that test? That feature would also help adding a feature which would Cancel a test, right?

**Comment by bassosimone** [comment]
> Is it possible to cancel tests without breaking anything? i.e discarding any progress made until that point on that test?

It is certainly possible to try to implement in a way that does not behave too badly.

> That feature would also help adding a feature which would Cancel a test, right?

Yes

**Comment by elioqoshi** [comment]
Would this be something we could triage prioritizing in the next releases? From some user frustrations I have heard quite a few times that they would have liked to cancel the test. For that matter, it's also not really documented in the app afaik that a user should not cancel a test by closing the app.

**Comment by lorenzoPrimi** [comment]
@elioqoshi you can discuss the cancel test here: https://github.com/ooni/probe/issues/841

**Comment by lorenzoPrimi** [comment]
Once interrupt test will be implemented in every test we can auto cancel the test if the networks condition are changed

**Comment by hellais** [comment]
This has been implemented.
