### ISSUE TITLE
The app fails silently when it fails to submit measurement results to collector

### ISSUE THREAD

**Issue by hellais** [ooni/probe#829]
Currently if the measurement fails to be submitted to a collector the OONI Probe mobile app fails silently.

That is to say it doesn't report back to the user in any way "hey we failed to submit measurements, you should look into this".

This is very important, especially for users to realise that the OONI collector may be censored in their country and they are not contributing measurements to the OONI data set.

I would implement this as either a toast message and/or an explicit error message in the result view.

**Comment by lorenzoPrimi** [comment]
Is this the same as https://github.com/ooni/probe/issues/838 ?

**Comment by elioqoshi** [comment]
Not sure. @hellais ?

**Comment by hellais** [comment]
I guess #838 could be a solution this issue.

**Comment by elioqoshi** [comment]
Closing this one if the other issue ( #838 ) can track this as well.
