### ISSUE TITLE
Add support for domain fronted collectors

### ISSUE THREAD

**Issue by hellais** [ooni/probe#830]
Measurement-kit since version 0.4.0 support domain fronting aka cloudfronting (see:  https://github.com/measurement-kit/measurement-kit/blob/master/ChangeLog.md#measurementkit-040-alpha-2016-12-07).

We don't however use this feature currently in ooniprobe. I think we should start adding support for it in 1 of 2 ways:

1. Follow the approach of Signal where there is a global setting, that when enabled starts using domain fronting (disabled by default)

2. Adaptively figure out when ooni.io is blocked and flip it on for the user

We can maybe do this in steps first 1 and then 2.

**Comment by elioqoshi** [comment]
Can we triage this? Is this something we want to implement in 2.1 or 2.2?

**Comment by hellais** [comment]
Domain fronting is a bit more complicated to do today than it used to be in 2017. I would suggest we put this into the icebox.

**Comment by hellais** [comment]
Another thing we were discussing with @bassosimone was the possibility of having fallback collector or bouncer addresses, which we update on every new release of the app.

I suspect the curl reworking in MK has affected this too.

**Comment by bassosimone** [comment]
This functionality has been implemented in Sprint 13: https://github.com/ooni/probe-engine/issues/19.
