### ISSUE TITLE
Deprecate ooni browser

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#834]
OONI Browser UI needs to be deprecated or removed

**Comment by elioqoshi** [comment]
Any screenshots? I can't remember right now any in-app browser. How can I see this UI?

**Comment by lorenzoPrimi** [comment]
You can't it's only accessible when receiving a push notification with an URL.
I don't have a screenshot right now but I have the storyboard preview 
<img width="286" alt="schermata 2019-01-17 alle 23 11 40" src="https://user-images.githubusercontent.com/1616097/51331910-4a510980-1aad-11e9-933f-ffd16909cc2d.png">

**Comment by lorenzoPrimi** [comment]
On the title bar the Url is displayed

**Comment by elioqoshi** [comment]
Okay, this also happens in Android? I will need more briefing for this, so whenever you want to start working on this, let me know

**Comment by lorenzoPrimi** [comment]
I guess before start working on this first we need to decide if we still need the browser and for which purposes, as I don't remember it has been used at all

**Comment by hellais** [comment]
I suggest we deprecate it for the time being. In light of the fact that we are going to be using countly we might want some specific UI for that, but let's think of it when the need arises.

Go ahead with removing this code!
