### ISSUE TITLE
Manage not uploaded tests and offer retry upload

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#838]
3 upload buttons:

- Upload All (select everything in the test results and upload all results)
Add not uploaded icon next to the time
<img width="230" alt="1" src="https://user-images.githubusercontent.com/1616097/54103810-c0685180-4408-11e9-8ca6-144d716146ae.png">

- Test Group (all the single measurements done with a single Run option, e.g: both NDT and DASH Streaming)
Add not uploaded icon next to the V or X icon (not as in the screenshot)
<img width="234" alt="2" src="https://user-images.githubusercontent.com/1616097/54103815-c2caab80-4408-11e9-89d6-81aec781cf4b.png">

- Single Measurement Upload (e.g the result of a Web Connectivity Test for 1 URL)
<img width="227" alt="3" src="https://user-images.githubusercontent.com/1616097/54103822-c5c59c00-4408-11e9-827c-fd60dc833873.png">

This popup is shown if pressing on the ? while if pressing on Upload / Upload All starts the process immediately.
<img width="227" alt="popup" src="https://user-images.githubusercontent.com/1616097/54103921-1c32da80-4409-11e9-9fcc-471e2581231d.png">

Settings:
A new setting `Manual Upload` is exposed. If enabled, it will show an additional button on the aforementioned snackbar to upload the results. The user will need to navigate to the specific result in the app and tap the button to upload it. If the Manual Upload setting is disabled however, this snackbar "Upload" button will not appear in the snackbar.
<img width="227" alt="settings" src="https://user-images.githubusercontent.com/5436686/52438230-1a7bab80-2b19-11e9-8e91-b4ceca027c8a.png">

Users of OONI Probe mobile < 2.1.0, will have a modal on the first app run asking if enabling or not the new feature:
`Modal.ManualUpload.Title`, `Modal.ManualUpload.Paragraph`,  `Modal.ManualUpload.Enable` and`Modal.ManualUpload.Disable`

New users, which have gone through the onboarding in 2.1.0, will have as defaults:

- Automatically publish results: true
- Manually upload results: true

Strings used:
`Settings.Sharing.UploadResults` = `Automatically Publish Results`
`Settings.Sharing.UploadResultsManually` = `Manual result Upload`
`Snackbar.ResultsNotUploaded.Text` = `Not uploaded`
`Snackbar.ResultsNotUploaded.Upload` = `Upload`
`Snackbar.ResultsSomeNotUploaded.Text` = `Some not uploaded`
`Snackbar.ResultsSomeNotUploaded.UploadAll` = `Upload All`
`Modal.ResultsNotUploaded.Title` = `Results not uploaded`
`Modal.ResultsNotUploaded.Paragraph` = `Some of your test results have not been uploaded to OONI servers. If you'd like to contribute to OONI's dataset, please upload them.`
`Modal.ResultsNotUploaded.Button.Upload` = `Upload`
`Modal.ManualUpload.Title`
`Modal.ManualUpload.Paragraph` 
`Modal.ManualUpload.Enable`
`Modal.ManualUpload.Disable`

**Comment by elioqoshi** [comment]
(Kind of) related to: https://github.com/ooni/probe/issues/801

**Comment by elioqoshi** [comment]
@lorenzoPrimi Any additional mockup work needed from my side? Or do you want to do an implementation yourself and we can review afterwards?

**Comment by lorenzoPrimi** [comment]
I guess the old mockups still works for this

**Comment by elioqoshi** [comment]
They do. We can do a review after an initial implementation.

**Comment by elioqoshi** [comment]
@lorenzoPrimi we are aiming 2.1 for this, right?

**Comment by lorenzoPrimi** [comment]
I have no idea as I don't know what is the state of mk on this @bassosimone

**Comment by elioqoshi** [comment]
Related to this: https://github.com/ooni/probe/issues/829

**Comment by lorenzoPrimi** [comment]
@bassosimone can we aim to have this in 2.2?

**Comment by bassosimone** [comment]
https://github.com/measurement-kit/measurement-kit/issues/1682

**Comment by elioqoshi** [comment]
Let's keep this in 2.2 and we all do a meeting looking at what is in 2.1 and 2.2 and triage these.

**Comment by lorenzoPrimi** [comment]
In regarding to this bug https://github.com/ooni/probe-android/issues/188
we should have a function to retry the results not uploaded in android v2.0.0 due to incorrect setting

**Comment by hellais** [comment]
I filed a separate ticket for the UI/UX of this feature: https://github.com/ooni/probe/issues/846.

**Comment by elioqoshi** [comment]
The UX Component for this has been agreed upon: https://github.com/ooni/probe/issues/846

**Comment by lorenzoPrimi** [comment]
in iOS is impossible to differentiate between an app update or first run.
I see two solutions:
1) if the setting about manual upload is null I show the popup (should be the "update" case)
2) if it's first run I usually show the onboarding, in every other case I show the popup about setting
3) If there are any test results I show the popup about settings.

I will try the first approach and if works I'll go with that. Otherwise 2 or 3

**Comment by lorenzoPrimi** [comment]
After a conversation with @xanscale we decided to go for 2 as 1 doesn't work
