### ISSUE TITLE
Remove max runtime setting

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#839]
We can remove it and serve an accurate list of URL or serve the max runtime API side.

**Comment by elioqoshi** [comment]
Would this make sense to be done for 2.1?

**Comment by lorenzoPrimi** [comment]
Not at all, there hasn't been even a discussion !

**Comment by elioqoshi** [comment]
That was also my question related with, to initiate that discussion. Are you saying that you don't think it should be in 2.1?

**Comment by lorenzoPrimi** [comment]
2.1 for sure not, this requres backend work and probably the orchestrate

**Comment by lorenzoPrimi** [comment]
@hellais I guess this issue doesn't make sense anymore

**Comment by hellais** [comment]
Ok closing.
