### ISSUE TITLE
Instant messaging - Telegram link

### ISSUE THREAD

**Issue by marcoslater** [ooni/probe#840]
The hyperlink ”Telegram” in the description of the instant messaging test is invalid.

Clicking it currently sends the user to `https://ooni.ionettest/telegram/`

**Comment by lorenzoPrimi** [comment]
@agrabeli I guess this is more of a copy issue

**Comment by hellais** [comment]
We should use this as an opportunity to also update all the links to the canonical ooni.org link version.

**Comment by lorenzoPrimi** [comment]
I fixed on transifex this string where was not updated.
@hellais  I think if we update the links in the copy we'll have to manually change them in every translation in transifex, do we really want to do it ourselves?

**Comment by hellais** [comment]
>  I think if we update the links in the copy we'll have to manually change them in every translation in transifex, do we really want to do it ourselves?

I suppose translators can do this too, no?

**Comment by lorenzoPrimi** [comment]
They will have to do it manually, link every link. 
We risk to have some links in a language and some other in another.
Either we are willing to accept this risk and proceed or we look for a quick find/replace function without having them to intervene

**Comment by hellais** [comment]
Ok, I suppose this is not that urgent and we probably don't want to break all translations. I created an issue for it though so we don't forget to do it at some point: https://github.com/ooni/probe/issues/978.

**Comment by lorenzoPrimi** [comment]
Ok we can close this as that link is now fixed
