### ISSUE TITLE
Possibility to cancel a running experiment

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#841]
As discussed in https://github.com/ooni/probe/issues/828
We want the possibility to cancel a running test.

@bassosimone what do you mean by "in a way that does not behave too badly" ?

**Comment by bassosimone** [comment]
@hellais this is a very complex issue that requires to do work on MK and to write a bunch of tests to make sure we're interrupting tests in a robust enough way. It feels like XXL task to me.

**Comment by hellais** [comment]
I would like to better understand what the scope of the problem is on the MK side. Can we perhaps schedule to have a discussion about this during one of the weekly backend/measurement meetings?

**Comment by bassosimone** [comment]
@hellais yes, I have scheduled a discussion on this topic for 2020-02-18.

**Comment by bassosimone** [comment]
@lorenzoPrimi I have read the code and it seems to me there is already machinery in place to stop a running experiment. So, on an experimental basis, I suggest that you implement the feature in the Android app. You need to call the `interrupt` method of MKAsyncTask. Judging from the code, it should probably be working as intended, but we need testing to be more confident.

**Comment by bassosimone** [comment]
I am going to create a follow-up issue with a precise description of what needs to be done.

**Comment by bassosimone** [comment]
Done https://github.com/ooni/probe/issues/1026. @lorenzoPrimi feel free to edit/move the issue.
