### ISSUE TITLE
Markdown link visible in the French Translation (Android) 

### ISSUE THREAD

**Issue by notagoodidea** [ooni/probe#842]
On Android 8 with Ooni Probe 2.0.1 

On the information screen about the parameters of Ooni Probe after the welcome quizz, the markdown link to the data-policy is not converted to an actual link (see picture). I have not tested in another locale neither in another mobile os, unfortunately.

![capture _2019-02-04-22-36-47](https://user-images.githubusercontent.com/22628160/52239465-d9905680-28ce-11e9-899c-105526b2d294.png)

If the issue is beginner-friendly solvable, I'm motivated to try to solve it.

**Comment by notagoodidea** [comment]
Error in the translation file found, on my way to correct and push it to ooni/translation. Sorry for the useless issue!

**Comment by hellais** [comment]
Good call! Thanks for spotting this.

While it is the case that we publish our translations on github.com/ooni/translations, where the translation work actually happens is on transifex.

What you say reminded me that we should probably put a link to that in the Readme.md of ooni/translations to avoid confusions.

If you would like to help out with the french translation you should sign up for a transifex account and request to join the OONI team here: https://www.transifex.com/otf/ooniprobe/dashboard/.

**Comment by notagoodidea** [comment]
@hellais Thanks ! Yep, I understood that after looking around last night. I asked to join the team and I got some messages from the Localization Lab. They told me that the correction was applied yesterday, thanks to whom done it!

**Comment by elioqoshi** [comment]
@notagoodidea Thanks for your help!
