### ISSUE TITLE
Accessibility in the apps

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#845]
As @hellais stated in the "Dynamic font" issue https://github.com/ooni/probe-ios/issues/231 Accessibility is a complex topic and there are many things to take into consideration, not only dynamic font.
Opening this ticket to keep track of accessibility issues to be implemented in the apps

**Comment by elioqoshi** [comment]
Not sure why @hellais needs to be assigned to this. This is more UX than anything else.

I could give the whole app an Accessibility Review and we could gather the results here.

**Comment by lorenzoPrimi** [comment]
Because he suggested the accessibility review so I guess he knows more than me on what features are needed. Great you assigned yourself as well!

**Comment by elioqoshi** [comment]
I will work on getting a quick review of a few pages so we have an idea where we are.

**Comment by elioqoshi** [comment]
[OONI Android App_TestReport.pdf](https://github.com/ooni/probe/files/2879528/OONI.Android.App_TestReport.pdf)

I worked with an Accessibility Researcher last week to come up with a quick review of the 2 most used screens on the Probe Android app (Dashboard and Test Results). Quite a few issues came up which indicate that the app is difficult (to say the least) to use for users with screenreaders. There are also some low-hanging fruit for users using keyboard which we could fix without too much efforts from what I can see.

I'd suggest to move on with a more extensive accessibility review (also on iOS) and gather the findings for them to be ready for us to address when we have a chance (post 2.1?). 

@holantonela curious to have your input on this

**Comment by holantonela** [comment]
hey, very nice review.

I'm thinking about how we can incorporate accessibility guidelines when we are handing off prototypes to developers.

Some standards are straightforward to follow, and if you are using MD, most of it is covered. But, we could provide instructions for the specific behavior we want on readers, for example. Things like focus order, linear navigation rules, accessibility text could be designed, and we could document developers about it.

I tried to find guidelines about how to do it during the handoff, but I just found checklists to fix things.

Maybe, Using notes in layers? Using layer names as Alt for example? Make a to-do list in this kind of issues? What do you think? 

Thanks for sharing!

**Comment by elioqoshi** [comment]
Thanks @holantonela for the feedback!

I only recently started exploring accessibility as a topic so I'm quite the beginner, but having the layer names be alt descriptions is a good start indeed.

I went ahead and started coordinating a full a11y review of all pages in the Android app. I expect it should be ready in 2 weeks or so, so we can have a deeper look later once we have some breathing space and time to dedicate to this.

**Comment by elioqoshi** [comment]
This is finished earlier than expected. Attached here:
[OONI Android App_TestReport_04-Mar-2019.pdf](https://github.com/ooni/probe/files/2927513/OONI.Android.App_TestReport_04-Mar-2019.pdf)

Each page includes a thorough review of the Android app with video by the tester I worked with. 

@lorenzoPrimi these are a lot of changes. Should we create a check-list for all pages what needs fixing based on this report? Would you like to triage it at some point so we can decide when we should start working on this (I'd guess 2.2 or 2.3)?

**Comment by lorenzoPrimi** [comment]
Sure, if you want you can start making a checklist here, no need to open other github issues.
I guess it would be better to have a call to explain some of them to me and @xanscale (better in 2 weeks so I will be in a most confortable timezone)

**Comment by elioqoshi** [comment]
Will do. Let's schedule a call in 2 weeks then.

**Comment by elioqoshi** [comment]
Folks, here is also the iOS accessibility report listing all the problems identified.

[OONI Probe iOS accessibility report.pdf](https://github.com/ooni/probe/files/3004983/OONI.Probe.iOS.accessibility.report.pdf)

@lorenzoPrimi do you want to have a call to go over these?

**Comment by hellais** [comment]
The app has moved very much forward since then so it's unclear if these are still relevant. @lorenzoPrimi should we close this issue?

**Comment by lorenzoPrimi** [comment]
I think so

**Comment by hellais** [comment]
Ok let's close it and re-open one when we are ready to work on it.
