### ISSUE TITLE
Define UI and UX for uploading not uploaded measurements

### ISSUE THREAD

**Issue by hellais** [ooni/probe#846]
It is possible that the measurement upload will fail (or that the user did not want to upload measurements at the time to save bandwidth or other reasons) and hence we should offer the possibility inside of the app to upload not uploaded measurements.

The implementation of this specified in: https://github.com/ooni/probe/issues/838

It would be great if @elioqoshi @holantonela could help us define a UI for handling this scenario.

I think the upload of not uploaded measurements should be possible on a per-result basis, but most importantly it should be possible to upload all the measurements.

One aspect which is especially important is ensuring that the meaning of the *Publish results*, *Sharing* setting option is understood.

For example if a user does the following:
1. Has configured their app to not publish results
2. Runs some tests and they are not uploaded
3. Goes to the result listing and no "Upload all results" button appears (because the "Publish results" setting is still false)
4. Changes their mind about publish results and enables it in the settings
5. They go to the result listing and they can now upload the previously not uploadable results (because they changed the setting)

How can we ensure that it's clear that the meaning of the flag is *Publish results* is at the moment in which the upload is offerred and can apply also retroactively to measurements?

Is it a bad idea to make the flag apply retroactively?

Can we make the default be that it doesn't apply retroactively, but that still it's possible for a user to override it by making some setting changes?

I personally think that just showing a modal when the *Publish results* option is flipped on saying "previously not uploaded measurements will now be uploadable" is the way to go, but I would also like to hear what @elioqoshi and @holantonela think about this.

**Comment by elioqoshi** [comment]
@hellais I think a good base to build on this are the old mockups which included uploading failed or not uploaded tests. They would definitely need to be refined now that we will actually implement it, but is there something specific which you think might not work in the mockups?

> How can we ensure that it's clear that the meaning of the flag is _Publish results_ is at the moment in which the upload is offerred and can apply also retroactively to measurements?
> Is it a bad idea to make the flag apply retroactively?

I'd think it would be surprising. I'd suspect anything like this would be surprising for a user. However, from what I have seen in other apps, wording it like "Sync Results" might imply doing that also retroactively and the user expecting that as well. I mean, if you have in some app 'Sync Contacts' enabled, you expect it to be synced right away, not only for the new contacts you add. Would a wording alike "Sync Results" work for us?

>Can we make the default be that it doesn't apply retroactively, but that still it's possible for a user to override it by making some setting changes?

If we stick with "Publish Results" we could also offer another toggle setting which expands when "Publish Results" gets enabled: "Publish past Results" which is off by default and the user would need to toggle that on as well.

**Comment by elioqoshi** [comment]
For reference, the pattern in the initial mockups:
![image](https://user-images.githubusercontent.com/5436686/52401041-10c65980-2ac1-11e9-962f-275f31352f1e.png)

**Comment by hellais** [comment]
> If we stick with "Publish Results" we could also offer another toggle setting which expands when "Publish Results" gets enabled: "Publish past Results" which is off by default and the user would need to toggle that on as well.

The issue is that the meaning of the flag over time (as in what the flag was set to in the past) is not something that we were collecting in the app, so we cannot go back in time and figure out what the setting was then.

**Comment by hellais** [comment]
I think I have an idea for how we could make this work.

How about when the "Publish results" flag is set to `false` (i.e. Don't publish results) and the user tap on it to enable it, the app asks "Would you like to publish previously unpublished results too?", if they say "No" then we will not offer to upload historical measurements, if they tap "yes" then we will offer to do that.

If the user toggles between the two states again, we will ask this question again, making it possible for them to change their mind in the future, by simply disabling "Publish results" and re-enabling it again.

For users that had the app prior to us introducing this feature, we should by default not offer to upload older measurements, but encourage them to toggle the option on and off (and say yes to the modal) for them to be able to upload historical measurements.

Does this make sense?

**Comment by elioqoshi** [comment]
> The issue is that the meaning of the flag over time (as in what the flag was set to in the past) is not something that we were collecting in the app, so we cannot go back in time and figure out what the setting was then.

Why would that be relevant? If someone toggles on "Publish Past Results" any past results not uploaded, would be uploaded. It is not required to know what setting they had at that point of time in the past.

**Comment by elioqoshi** [comment]
> I think I have an idea for how we could make this work.

That works as well but I'm not sure what the advantage over the pattern I proposed is. I'd prefer to have the option exposed at all times rather than nest it in a modal if we can avoid it.

**Comment by hellais** [comment]
> Why would that be relevant? If someone toggles on "Publish Past Results" any past results not uploaded, would be uploaded. It is not required to know what setting they had at that point of time in the past.

What you say here, though, contradicts your previous statement:

> I'd think it would be surprising. I'd suspect anything like this would be surprising for a user.

**Comment by elioqoshi** [comment]
I don't see why, let me illustrate:

![image](https://user-images.githubusercontent.com/5436686/52432054-c74e2c80-2b09-11e9-871e-65f0e981c54c.png)

So basically this would separate the retroactive uploading into another toggle. We could additional also add some description text underneath,

**Comment by elioqoshi** [comment]
After having a chat we decided this is the way we are moving forward:

If a measurement is not uploaded, it will show at ALL times a snackbar indicating that the results of that/these measurement(s) is/are not uploaded.

Further, we offer 2 Toggles in the Settings:
1. `Automatically Publish Results` (currently `Publish Results` ) which will automatically allow the app to attempt uploading any measurement results after the test completion. If it's disabled it won't even attempt to upload a completed test measurement results>
2. `Manual Upload`. If enabled, it will show an additional button on the aforementioned snackbar to upload the results. The user will need to navigate to the specific result in the app and tap the button to upload it. If the Manual Upload setting is disabled however, this snackbar "Upload" button will not appear in the snackbar.

Users can mix these 2 settings to have customized behaviour for uploading of results depending on their use case.

Mockup of the Setting Screen (different state examples):

![image](https://user-images.githubusercontent.com/5436686/52438230-1a7bab80-2b19-11e9-8e91-b4ceca027c8a.png)

Also:

> Moreover current OONI Probe Android users that upgrade to 2.1.0, should have the settings set to:
> • Automatically publish results: true
> • Manual upload: false
> New users that go through the onboarding will have both of them set to true. This way the current behaviour is preserved for existing users and there are no surprises. We should also send a push notification to users that have unuploaded measurements (and don’t have the manual upload setting on) telling them they should enable this option and offer them to enable it in a modal.

**Comment by holantonela** [comment]
Some thoughts:

1. Having an opt-in per measurement like what mentioned [here]( https://user-images.githubusercontent.com/5436686/52401041-10c65980-2ac1-11e9-962f-275f31352f1e.png ) will make it difficult for users to upload retroactive probes in vast quantities. Instead, it will give better control to users about what they want to share and what not. So, what does make a user to share a result or not?

2. The general sharing setting seems the best option for this flow. I also agree that if I'm opting in on sharing results now, it doesn't make explicit that I want to share my past results. It shouldn't affect my data retroactively by default. What if before effectively sharing, we show users a preview of what they are uploading, as a verification step?

Let's walk through a real user story: I ran Probe in Egypt last month, I didn't share because of x. I left Egypt, and now I want to share those results. But just those results, not the results I'm getting now. As a user, can I see a list of my measurements and select what I want to share and what not?

Is a useful feature, we should be sure that users are understanding what they are doing and not sharing data that they will regret.

**Comment by elioqoshi** [comment]
>     1. Having an opt-in per measurement like what mentioned [here](https://user-images.githubusercontent.com/5436686/52401041-10c65980-2ac1-11e9-962f-275f31352f1e.png) will make it difficult for users to upload retroactive probes in vast quantities. Instead, it will give better control to users about what they want to share and what not. So, what does make a user to share a result or not?

Antonela, to my understanding, we will also have an ```Upload All``` option to upload all tests from the past (not right now in the mockups)

> Let's walk through a real user story: I ran Probe in Egypt last month, I didn't share because of x. I left Egypt, and now I want to share those results. But just those results, not the results I'm getting now. As a user, can I see a list of my measurements and select what I want to share and what not?

Yes, all measurements which haven't been uploaded will be marked as such. The user could Upload them manually afterwards (if they have the Setting ```Manual Upload``` enabled).

So there will be 3 levels of upload selections ( @hellais please correct me If I'm wrong):
- Single Measurement Upload (e.g the result of a Web Connectivity Test for 1 URL)
- Test Group (all the single measurements done with a single Run option, e.g: both NDT and DASH Streaming)
- Upload All (select everything in the test results and upload all results)

Maybe in the future we could have a selection feature so specific test results selected (long tap) could be uploaded.

Hope that is clear. We had a call ourselves to explain this better as it might not be easy to grasp in written form.

**Comment by lorenzoPrimi** [comment]
What @elioqoshi said it's correct, enabling sharing result now won't affect at all past results, every measurement is uploaded in the moment it's finished.
With the manual upload they can choose which measurement to upload, or all of them.

I'm gonna prepare the copy based on the mockups so we can check if something's missing.

**Comment by lorenzoPrimi** [comment]
To change:
`Settings.Sharing.UploadResults` = `Publish Results`
becomes `AutomaticallyPublish Results`

New strings:
`Settings.Sharing.UploadResultsManually` = `Manually Upload of Results`

Already in the copy:
`Snackbar.ResultsNotUploaded.Text` = `Not uploaded`
`Snackbar.ResultsNotUploaded.Upload` = `Upload`
`Snackbar.ResultsSomeNotUploaded.Text` = `Some not uploaded`
`Snackbar.ResultsSomeNotUploaded.UploadAll` = `Upload All`
`Modal.ResultsNotUploaded.Title` = `Results not uploaded`
`Modal.ResultsNotUploaded.Paragraph` = `Some of your test results have not been uploaded to OONI servers. If you'd like to contribute to OONI's dataset, please upload them.`
`Modal.ResultsNotUploaded.Button.Upload` = `Upload`

To remove
`Modal.ResultsNotUploaded.Button.Cancel` = `Cancel`

**Comment by hellais** [comment]
Yes what @elioqoshi says is correct.

A minor nitpick:
> So there will be 3 levels of upload selections ( @hellais please correct me If I'm wrong):

There will actually only be two:

> * Test Group (all the single measurements done with a single Run option, e.g: both NDT and DASH Streaming)
> * Upload All (select everything in the test results and upload all results)

It's easier to treat the whole test group block as whole as it's all run at the same time and I don't see in which occasion it may be desirable to support uploading only a single URL entry (not to mention the effort required to tap through all those screens).

To recap how the rollout of this feature will work is:

Users of OONI Probe mobile < 2.1.0, will have by default the following settings (assuming they had shared results on):

* Automatically publish results: true
* Manually upload results: false

New users, which have gone through the onboarding in 2.1.0, will have as defaults:

* Automatically publish results: true
* Manually upload results: true

We will also send a push notification to old users telling them that this option will allow them to upload their un-uploaded measurements and that they may want to enable it.

I think the points raised by @holantonela capture the spirit and purpose of this type of setting logic pretty well.

By separating:

"What happens when I run a test to my measurements" (i.e. do my measurements get uploaded automatically when the test finishes running)
from
"Can I manually choose to upload my old measurements if they failed or I didn't want to upload them in the past" (i.e. should we show the upload button at all for old measurements)

We are both putting in place a safeguard for old users from accidentally uploading measurements they didn't want to upload (the default for them is manual upload: false), but at the same time exposing this feature in the settings.

@lorenzoPrimi the strings are good I would just suggest to tweak the copy for:

`Settings.Sharing.UploadResultsManually`
to
 `Manual Result Upload`

To clarify that we are talking about enabling some extra feature and that it's not in contradiction with the automatic option.

**Comment by lorenzoPrimi** [comment]
@elioqoshi be sure to close this when the UX is finalized and update https://github.com/ooni/probe/issues/838

**Comment by elioqoshi** [comment]
@lorenzoPrimi I don't think any other visual UX component is needed here unless I missed something. Closing.

**Comment by lorenzoPrimi** [comment]
Ok I will try to summarise everything as this post has been too long.
Copy has already been updated as my last post stated.

@hellais @holantonela I don't understand why differentiate users who installed a fresh app from user who updated to 2.1.0:

`Manually Upload Results` only shows the label `Not Uploaded` and offer the option to upload, it doesn't do anything without a few taps of the user. If the user doesn't open the settings he will never see this Button.
if your concern if about the `Upload all` button, that button presents a confirmation popup before being executed so I don't see the problem.

**Comment by lorenzoPrimi** [comment]
@elioqoshi a few more questions: 
- what does the `?` Just a popup with some info about the upload manually?
<img width="453" alt="Screenshot 2019-03-11 at 14 13 26" src="https://user-images.githubusercontent.com/1616097/54103570-de818200-4407-11e9-9c93-312886d7acbd.png">

- Should this popup appear every time we press upload or upload all?
<img width="227" alt="popup" src="https://user-images.githubusercontent.com/1616097/54103549-cc9fdf00-4407-11e9-9f1b-f3a57685eaaa.png">

**Comment by lorenzoPrimi** [comment]
After a little brainstorming with @hellais we came up with the solution that user who upgrades the app will get a modal at the app opening explaining that there is a new `Manual upload` settings, what this setting does and two buttons `Enable` `Disable` to choose from. 
@agrabeli can you write the copy? 
Thanks

**Comment by elioqoshi** [comment]
> what does the ? Just a popup with some info about the upload manually?

My initial idea was to show that modal dialog when the user taps the question mark icon. Tapping on Upload / Upload All doesn't show it and move ahead right away with Uploading.

That UX pattern is over a year old and might some reconsidering now in production, but I think it's still okay (especially since users will be unable to even have an upload button there if they disabled manual uploads in their settings.)

> After a little brainstorming with @hellais we came up with the solution that user who upgrades the app will get a modal at the app opening explaining that there is a new Manual upload settings, what this setting does and two buttons Enable Disable to choose from.

I like it. Let's keep it `No, thanks` and `Enable` though. `No, thanks` does no action and `Enable` does. This gives the user more reassurance if they don't want to touch anything. Enable and Disable both would make them feel as if both options would change something.

Regarding the Modal copy, I'd think of something like

> ### Enable Manual Upload?
> OONI can allow you to manually upload selected past measurements. You can change this option in the Settings later.

for reference:
https://uxplanet.org/5-essential-ux-rules-for-dialog-design-4de258c22116

(reopening this issue until resolved)

**Comment by lorenzoPrimi** [comment]
> My initial idea was to show that modal dialog when the user taps the question mark icon. Tapping on Upload / Upload All doesn't show it and move ahead right away with Uploading.

So that popup is shown if pressing on the `?`while `Upload` / `Upload All` starts the process immediately?

**Comment by elioqoshi** [comment]
> So that popup is shown if pressing on the `?` while Upload / Upload All starts the process immediately?

Exactly.

**Comment by agrabeli** [comment]
@lorenzoPrimi I like @elioqoshi's suggestions. I'd propose the following copy for the modal:

**Enable Manual Upload?**

A new setting has been added for manually uploading past measurements that haven't been published. You can change this option in the Settings later.

"No, thanks"

"Enable"

**Comment by agrabeli** [comment]
@elioqoshi Do modals on iOS have titles? Is a mockup of the modal available?

**Comment by lorenzoPrimi** [comment]
I see
`Modal.ManualUpload.Paragraph`,  `Modal.ManualUpload.Enable` and`Modal.ManualUpload.Disable`
added to the copy.

**Comment by agrabeli** [comment]
@lorenzoPrimi Yes, I have added those strings. As you'll see, (on second thought) I propose the following copy for the modal:

A new setting has been added for manually uploading past measurements that haven't been published. Do you want to enable Manual Result Upload?

(assuming that we're not including a title)

**Comment by lorenzoPrimi** [comment]
Everything has been summarized here: https://github.com/ooni/probe/issues/838
@elioqoshi  as long as what you read is what you want you can close this one

**Comment by elioqoshi** [comment]
@agrabeli iOS modals have titles as well. Example:
![image](https://user-images.githubusercontent.com/5436686/54113288-3ad4a980-43e8-11e9-8505-bcf120873662.png)

> A new setting has been added

Are we sure we want to phrase it in a way which suggests a time-based event? This is only for users which upgrade, right?

Maybe we could have something more generic? I personally think following could work better:

> ## Enable Manual Upload?
> OONI Probe allows to manually upload past measurements that haven't been published. You can change this option in the Settings later.

More reference on good UX copy is in the Material Design guidelines for dialogs:
https://material.io/design/components/dialogs.html

**Comment by elioqoshi** [comment]
@lorenzoPrimi let's close this when we have a prototype and it's good to go?

**Comment by lorenzoPrimi** [comment]
Ok. 
Waiting for @agrabeli to know when to upload copy to transifex

**Comment by agrabeli** [comment]
Thanks @elioqoshi! How about:

# Enable Manual Upload?

This setting will manually upload past measurements that haven't been published. 

(drawing inspiration from the guidelines you shared)

**Comment by elioqoshi** [comment]
@agrabeli I think that's a bit more ambigous since it sounds like this WILL upload not OFFER the ability to upload measurements.

Also, let's avoid explaining patterns which are already clear (e.g this Setting, this Link, this Screen) as that's redundant.

Sorry for nitpicking, I'd just like us to have a consistent clear tone for the UX copy.

An article about exactly this topic:
https://uxplanet.org/mobile-ux-design-the-right-ways-to-ask-users-for-permissions-6cdd9ab25c27

I'd stick with my suggestion and a small tweak in the 2nd part.

> ### Enable Manual Upload?
> Allow manually uploading past measurements that haven't been published. This can be configured in the Settings.

Do you see something which might not work?

**Comment by lorenzoPrimi** [comment]
@agrabeli I understand that the copy can't be uploaded already. Let me know when is final either here or in the doc.

**Comment by agrabeli** [comment]
@lorenzoPrimi Please use the following copy:

# Enable Manual Upload?

This setting allows you to manually re-upload unpublished measurements.

(I have also updated the strings.)
