### ISSUE TITLE
Ability to access log of a failed test

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe#850]
We received notice that the Performance tests failed in some cases:
https://github.com/ooni/probe-android/issues/196

As the log can be accessed only through the details test results screen of a test, the user cannot access this as they never can get to a detail screen when a test has failed. We would ideally still be able to receive logs from such cases.

Potential Steps forward:
- We should figure out a UX component to access the log of a failed test (possibly in the pop-up?)
- Find the best way to implement the proposed solution for both iOS and Android

This is a rather small but not unimportant issue, so tagging this 2.1

## EDIT:
We will go with a details screen which can be accessed for failed tests:
mockup:

![image](https://user-images.githubusercontent.com/5436686/53866327-9de1cd00-3ff1-11e9-88d3-5560677937ba.png)

**Comment by elioqoshi** [comment]
In Material Design guidelines it's mentioned that
> Dialogs should contain a maximum of two actions.
> If two actions are provided, one must be a confirming action, and the other a dismissing action.

>Rather than adding a third action, an inline expansion can display more information. If more extensive information is needed, provide it prior to entering the dialog.

I don't see how based on that we could show an option to enter the log before the modal is shown.

The only idea I have is to have a pop-up with advanced options, among them showing the log be accessible by long-pressing on that row.

https://material.io/design/components/dialogs.html#actions

cc @holantonela

**Comment by elioqoshi** [comment]
I'd propose this as an easy solution:
![image](https://user-images.githubusercontent.com/5436686/53563458-620fb900-3b54-11e9-893f-9a479d399e46.png)

A kebab icon to access a dropdown which includes "View Logs"

@holantonela @agrabeli what do you think?

**Comment by lorenzoPrimi** [comment]
@elioqoshi won't work for iOS

**Comment by elioqoshi** [comment]
> @elioqoshi won't work for iOS|

Right. Let me do some more research on iOS for this. This pattern has been adopted from the Youtube app, so I'm curious to see how Youtube does it on iOS.
Example from Android:

![image](https://user-images.githubusercontent.com/5436686/53564999-971e0a80-3b58-11e9-87e6-46b120b9c6e7.png width="300px")

**Comment by elioqoshi** [comment]
@lorenzoPrimi seems the Youtube app on iOS uses a similar pattern:
https://itunes.apple.com/us/app/youtube-watch-listen-stream/id544007664?mt=8

**Comment by lorenzoPrimi** [comment]
It's an Android pattern, not iOS standard at all.
They were just too lazy to adapt it for iOS

**Comment by lorenzoPrimi** [comment]
What about a swipe for actions? 
![screen_shot_2015-01-29_at_1 57 30_pm](https://user-images.githubusercontent.com/1616097/53569341-f141be80-3b9e-11e9-9040-938d1efe28de.jpg)

**Comment by elioqoshi** [comment]
I love the swipe for actions pattern, even for other uses apart this, but we need to make sure the user is aware of it (by showing an onboarding of the feature). This is substantially more work though I assume.

**Comment by elioqoshi** [comment]
Or do you mean having swipe actions only on iOS? I think it's a more established pattern in iOS but Android has started using it too (check Gmail or Google Calendar for example)

**Comment by lorenzoPrimi** [comment]
I dont think "show log" is something that should be super visible

**Comment by elioqoshi** [comment]
I agree with that. Do you want to incorporate swiping actions on both Android and iOS? Generally speaking, we can triage it after 2.1 is out as well

**Comment by lorenzoPrimi** [comment]
iOS for sure, Android if we want to keep it hidden we use swipe as well

**Comment by elioqoshi** [comment]
The first time a test is failing, we can trigger a tap target for it on Android to explain that it's swipable.

https://blog.iamsuleiman.com/material-design-onboarding-android-quickstart-tap-target/

**Comment by elioqoshi** [comment]
After the UX Meeting with @holantonela we suggested to actually have a failed test measurement details page so it's consistent with all other pages as well. This might need some more implementation work, but it would solve this problem and we would not add more complexity to the interactions in the apps. 

@lorenzoPrimi @xanscale

**Comment by lorenzoPrimi** [comment]
@elioqoshi can you explain better your idea? it's like removing the forced rerun button and showing details also for the failed tests?

**Comment by elioqoshi** [comment]
@lorenzoPrimi mockup:

![image](https://user-images.githubusercontent.com/5436686/53866327-9de1cd00-3ff1-11e9-88d3-5560677937ba.png)

So we allow the user to get to the details page and they can re-run it from there and also access the log (we will disable viewing the data there for obvious reasons I suppose)

**Comment by lorenzoPrimi** [comment]
`try again` will do the rerun then go back to the previous screen right?

**Comment by elioqoshi** [comment]
> try again will do the rerun then go back to the previous screen right?

Yes

**Comment by holantonela** [comment]
Yeah, this will keep the user flow consistent with the entire app.

Is the yellow because of something in particular? are we using yellow in other error messages? What about a light grey?

**Comment by elioqoshi** [comment]
> Is the yellow because of something in particular? are we using yellow in other error messages? What about a light grey?

We do use Yellow for Errors in other places. Light Gray is used for OONI Run screens (which are tests with less endorsement from us) hence I didn't want to replicate. We could use black I suppose?

**Comment by holantonela** [comment]
got it, go ahead so!

**Comment by lorenzoPrimi** [comment]
@elioqoshi when this is definitive let me know colors and everything or update the top post

**Comment by elioqoshi** [comment]
@lorenzoPrimi this is definitive from my side, but I'd like @hellais to give one more thumbsup

**Comment by lorenzoPrimi** [comment]
@elioqoshi there are a few things I need to know:
The `retry` row doesn't exists anymore, how is that replaced? Which icon and background? Can you make a quick design?
I also need the yellow color code.
---
The new string needed are `Failed` and `You can try to run this test again`.

**Comment by elioqoshi** [comment]
> The retry row doesn't exists anymore, how is that replaced? Which icon and background? Can you make a quick design?

Do you mean `Re-Run` ? It's `Try again` in the mockup I showed. Also not sure what you mean. With this change we would not allow re-runs from the Test Summary anymore.

**Comment by lorenzoPrimi** [comment]
So I need to know how the row in Test Summary will look like

**Comment by elioqoshi** [comment]
> So I need to know how the row in Test Summary will look like

Right. I'd suggest the same of greying it out and having a question mark icon for the status:

![image](https://user-images.githubusercontent.com/5436686/54112650-f1378f00-43e6-11e9-97a2-36d8fd319694.png)

**Comment by hellais** [comment]
Yes this seems like a good pattern to me. I think using yellow is consistent with the failure pattern we use elsewhere.

Maybe in the case of failure we also want to have a secondary button which says "Show log" or mention that they can access the log via the option menu on the top in the copy?

**Comment by elioqoshi** [comment]
> I also need the yellow color code.

yellow5 according to https://design.ooni.io/colors/

> Maybe in the case of failure we also want to have a secondary button which says "Show log" or mention that they can access the log via the option menu on the top in the copy?

Good point. If we have a secondary button to show the log we might want to remove it from the kebab menu though. Or maybe duplicating it is better? I'm not sure.

I'd side with having a button to Show the Logs. I think written instructions on how to use the GUI should be a Plan B

**Comment by lorenzoPrimi** [comment]
Added to the copy
`TestResults.Details.Failed.Title` = `Failed`
`TestResults.Details.Failed.Paragraph = `You can try to run this test again`
`TestResults.Details.Failed.TryAgain = `Try Again`

What to do with these old strings?
`Modal.ReRun.Title` = `Re-run test`
`Modal.ReRun.Paragraph` = `This test has failed. Re-run the test?`

**Comment by elioqoshi** [comment]
> Should we keep them or remove from the copy?

I'd suggest we keep them for now and flag them that they should be removed. Just in case?

> Will this modal be used?

I don't see anywhere where this modal would be used with this new pattern.

**Comment by lorenzoPrimi** [comment]
@elioqoshi last thing needed is the ? icon. Let me know when you update the xd so I can export it from there.

**Comment by elioqoshi** [comment]
@lorenzoPrimi it's a default Material Design icon: https://material.io/tools/icons/?search=help&icon=help&style=baseline

**Comment by lorenzoPrimi** [comment]
I guess it has a bit too much padding in there, I'll try

**Comment by elioqoshi** [comment]
It's fine if it has more padding as well.
