### ISSUE TITLE
Performance tests have inconsistent order of Download and Upload stats

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe#853]
(related to https://github.com/ooni/probe/issues/852 )

In the Test Results, Upload is shown first and in the Test Summary, Download is shown first which is not consistent. In all cases Download should be first and Upload second as Download is the first thing users are interested in most of the time.

![image](https://user-images.githubusercontent.com/5436686/53552565-e1dd5980-3b3b-11e9-9bb9-61b9dc2eb270.png)

![image](https://user-images.githubusercontent.com/5436686/53552568-e4d84a00-3b3b-11e9-85e7-f61b232df2aa.png)

**Comment by lorenzoPrimi** [comment]
So to recap che changes:
- Test results header.
- Test result Performance row
- Performance result header
- NDT result Row

While NDT detail header is correct

**Comment by bassosimone** [comment]
Yes, put download first

**Comment by lorenzoPrimi** [comment]
Done for iOS : https://github.com/ooni/probe-ios/pull/243

**Comment by xanscale** [comment]
Done for Android: https://github.com/ooni/probe-android/commit/8439e7f988e1c26b6815337344078e26e954aed4
