### ISSUE TITLE
Unreachable measurements due to bouncer failure

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#855]
I notice a problem when a measurement fails in this way 
```
Contacting bouncer: https://bouncer.ooni.io
Bouncer error: generic_timeout_error
```
it will never get the callback `status.measurement_done` and that is where the measurement object is set to `is_done`  = true.

Now as in the test summary screen we show measurements that are is_done = true, rerun = false that measurement will never show up, not even as failed.

The only callback we always get is `status.end` so maybe whenever we get that callback we should `is_done` to true (and maybe initializing a test with `is_failed` to true could be something worth exploring.

**Comment by lorenzoPrimi** [comment]
@bassosimone is `failure.startup` called in this case?

**Comment by bassosimone** [comment]
@lorenzoPrimi no

**Comment by lorenzoPrimi** [comment]
either we call `failure.startup` or I initialize `is_failed` to true and only change it when the test is not failed. 
Maybe the first solution is more elegant

**Comment by lorenzoPrimi** [comment]
@bassosimone do you think this should be addressed in `2.2.0` ?

**Comment by bassosimone** [comment]
Yes; see https://github.com/measurement-kit/measurement-kit/issues/1870

**Comment by hellais** [comment]
Has this been addressed in 2.2.0?

**Comment by bassosimone** [comment]
We have not tested whether we addressed it. (We need more tests.)

**Comment by lorenzoPrimi** [comment]
This has been addressed in mk.

**Comment by lorenzoPrimi** [comment]
@bassosimone what is left to do here?

**Comment by bassosimone** [comment]
Nothing, the code now emits `failure.startup` if the bouncer fails.

**Comment by lorenzoPrimi** [comment]
In the app this event is handled by going to run the following test. 
Do we need to emit some error to the user?

**Comment by bassosimone** [comment]
Good question. I think we and our users want to know that this happened. Can you flag the nettest as failed and provide more information to the user?

**Comment by lorenzoPrimi** [comment]
I can set `is_failed` to true and `failure_msg` to something we decide here

**Comment by bassosimone** [comment]
Something like `bouncer_error`?

**Comment by lorenzoPrimi** [comment]
Do we ever reach `status.measurement_start` or  not?

**Comment by bassosimone** [comment]
No we don't

**Comment by lorenzoPrimi** [comment]
The db object is created  in `status.measurement_start` at the moment.

**Comment by bassosimone** [comment]
So, it seems it's created too late? The `status.measurement_start` is per-measurement while the `failure.startup` is a per-experiment event.

**Comment by lorenzoPrimi** [comment]
It's exactly what we want, the `Measurement` object is created when the  measurement starts, not before. The `Result` object is created when the experiment starts, but Result doesn't have `is_failed` or any other of these per-measurement value.
So  basically when a `failure.startup` happens now  we get a Result with 0 Measurements inside.

**Comment by bassosimone** [comment]
Yet, we need a way to tell the user why there are 0 Measurements inside.

**Comment by lorenzoPrimi** [comment]
Is there a way to get `failure.startup` on purpose? I want to reproduce this scenario

**Comment by bassosimone** [comment]
You can write your own wrapper around MK code. Such wrapper should allow you to inject specific messages and receive them. Something like that, for example:

```Java
public class OONIAsyncTask {
  private MKASyncTask task;
  private java.util.Deque<String> queue;

  public OONIASyncTask start(String settings) {
    task = OONIAsyncTask.start(settings);
  }

  public String waitForNextEvent() {
    String rv = getNextSavedEvent();
    if (rv == null) {
      rv = taskWaitForNextEvent();
    }
    return rv;
  }

  public synchronized String getNextSavedEvent() {
    return queue.pollFirst();
  }

  public synchronized appendSavedEvent(String event) {
    queue.offerLast(event);
  }

  public void interrupt() {
    task.interrupt();
  }  
};
```

The actual best thing would be to do this with an interface and to construct the concrete implementation (mockable or not mockable) that you need, depending on context. Likewise, with ObjectiveC you can use a protocol to represent the common traits, and two different interfaces.

In some languages, programmers expect a library to do this stuff, in other languages, this should be done by the consumer. I don't remember by hearth what is the expected thing in ObjectiveC, but IIRC in Java this should be done by the library. Sadly, I don't think I can work on this right now(TM), hence my suggestion to place this abstraction in to the apps. (This is also the sanest pattern to me, but I am deeply influenced by golang conventions, for which it's the app that should write mocks.)

**Comment by lorenzoPrimi** [comment]
Thanks for the answer, probably I will first handle the failure startup scenario and then test it properly.
But I believe to tell the user there are 0 Measurements inside "and" and error message we need to edit the db and the UX so I'll look for an easier and less invasive way with what we have now.

**Comment by lorenzoPrimi** [comment]
After a call with @bassosimone we agreed to show the totally failed tests (`failure.startup`) in a visual way, preventing the user to opening them as they don't have any measurement inside.
@elioqoshi can you draw a very easy layout removing "Unknown" and 0 tested and show that this test is failed. (With failed we mean totally failed to start, not to measure)
This is how it looks now:
<img width="411" alt="Screenshot 2020-01-03 at 15 58 57" src="https://user-images.githubusercontent.com/1616097/71765583-4b32b380-2f29-11ea-86e0-2b1f6669b0ab.png">

**Comment by hellais** [comment]
Let me understand if I get the UX question properly. You are asking, how do we visually handle the situation in which you started an experiment, but got zero results due to an error.

This is:

a. How do we visually convey there is an error in this particular result set
b. How do we expose the details of the error to the end user

Is this correct @lorenzoPrimi ?

Based on the above assumptions I will make a mockup and share it in this thread.

**Comment by hellais** [comment]
We discussed with @lorenzoPrimi that for the time being we should not allow retry, because we can't do that in the case of OONI Run links. For the time being we implement it without the retry button and defer retry support to future work.

**Comment by lorenzoPrimi** [comment]
@bassosimone in this case the error string will be fixed right? Can we add it into the main copy?

**Comment by lorenzoPrimi** [comment]
Why this was moved back to Backlog?
