### ISSUE TITLE
It's not possible to view logs when a test fails

### ISSUE THREAD

**Issue by hellais** [ooni/probe#857]
## Expected Behavior

If a test fails it should be possible to inspect the logs for the failing test in order to better troubleshoot the problem.

## Actual Behavior

When you tap on a row of a failed test you are prompted to re-run the test, but it's not possible to see the logs

**Comment by hellais** [comment]
I guess we should probably also come up with some UI pattern for support this.

cc @holantonela @elioqoshi

**Comment by lorenzoPrimi** [comment]
Duplicate of https://github.com/ooni/probe/issues/850

**Comment by hellais** [comment]
In which version of the app is this shipped in?

**Comment by lorenzoPrimi** [comment]
Will be shipped as part of 2.1 in the next days
