### ISSUE TITLE
Add a What's New section

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#859]
It will be useful to have a ` What's New` section that will briefly describe the features of a new OONI release.

This section may be used also to provide users with important information such as incident reports.

**Comment by bassosimone** [comment]
Wouldn’t this be redundant with f-droid, Google Play, and App Store change logs?

I think we may want to have a section of the desktop app with this information, maybe, but for all other platforms I have a sense this would be redundant and more work for us. Or maybe I just do not see/understand how this could be beneficial to users.

**Comment by anadahz** [comment]
I don't have a screenshot to describe it visually,  but I can point you to some code on how Osmand provides a `Latest Changes` view upon a new version -- https://github.com/osmandapp/Osmand/commit/13d1d5004f970430270d1ee4df335f81a43fe567

Also there is no mention in changelog of the Android [incident report blog post](https://ooni.io/post/ooni-probe-android-200-incident/).

**Comment by hellais** [comment]
> Also there is no mention in changelog of the Android incident report blog post.

There is no mention of it because the blog post came out **after** we made the release fixing the issue.

I agree with @bassosimone that this is redundant as we already have whats new inside of each respective store and we also have a changelog.

**Comment by hellais** [comment]
Closing this as invalid and wontfix
