### ISSUE TITLE
Testing full URL list

### ISSUE THREAD

**Issue by semi0naut** [ooni/probe#860]
I set the web connectivity test max runtime to 999999

## Expected Behavior
OONI Probe runs the entire testing list

## Actual Behavior
OONI Probe stops after testing 100 sites

## Steps to Reproduce the Problem
  1. Go to websites > settings
  2. Set Test Duration to 999999
  3. Press Run

## Specifications

  - Version: 2.0.6
  - Platform: iOS
  - Subsystem: n/a

**Comment by bassosimone** [comment]
What happens if you set it to `-1`?

**Comment by hellais** [comment]
@bassosimone it will likely behave in the same way because orchestra will return by default a list of 100.
I think we should address this in orchestra directly via: https://github.com/ooni/orchestra/pull/66.

This should not even require client side changes, I think.

**Comment by bassosimone** [comment]
> it will likely behave in the same way because orchestra will limit by default the list of URLs to 100.

Gotcha, that's right!

**Comment by hellais** [comment]
An update to orchestrate has been deployed which should fix this. @semi0naut it should now be possible for you to test the full lists on mobile too by bumping up the max_runtime.
