### ISSUE TITLE
Write markdown mobile QA check list

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#862]
We have an internal document. Yet, a template to be pasted in GitHub issues is much more traceable and actionable, so I think we should do that.

The list in https://github.com/ooni/probe-ios/issues/283 could be a starting point, even though now I realise it is missing some bits that were present in the shared document.

I'll try to write a markdown document that we can use as template.

**Comment by bassosimone** [comment]
@hellais where it would be best to put this template? Will this repository be the right place?

**Comment by hellais** [comment]
I would put it as a PR template inside of the `.github` directory of probe-android and probe-ios repos so when you open a PR with the right parameters it prefills it.

> To create multiple pull request templates and use the template query parameter to specify a template to fill the pull request body, type .github/PULL_REQUEST_TEMPLATE/, then the name of your pull request template

See: https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

**Comment by bassosimone** [comment]
Thanks for the suggestion, this seems to me very proper. One small thing, I'm going to create an issue template, rather than a PR template, because this kind of checks are actually done in issues.

**Comment by bassosimone** [comment]
@hellais @lorenzoPrimi I've implemented this for both mobile repos. Please, take a look!

**Comment by bassosimone** [comment]
Done and merged in both repos. I took the liberty of committing on master minimal changes to make sure that pre-existing issue templates work again. Apparently, they were using the old style of issue templates and I am instead now using the new style.
