### ISSUE TITLE
Grey out background during re-uploading

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#864]
We should grey out background during re-uploading such that we clearly convey the info that the UI is locked and it's not possible to perform other actions.

Posting on behalf of @hellais.

**Comment by bassosimone** [comment]
For Android, that's probably what users expect to see.

Ping @holantonela to have input on this issue.

**Comment by lorenzoPrimi** [comment]
Let's take a decision soon, we can't block the release long for a change can always be done in 2.1.1

**Comment by bassosimone** [comment]
I’d say let not block this release.

**Comment by lorenzoPrimi** [comment]
We still need UX feedbacks here

**Comment by holantonela** [comment]
[Tested in 2.1.0](https://user-images.githubusercontent.com/7602174/59765478-8a8f0080-9274-11e9-803a-1e2871f2c86c.png)
1. Could we have a regular opacity layer so we [focus the loader](https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/)? 

2. We need confirmation [feedback](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/feedback/). Once the upload is done, we should replace the loading icon with a check icon? It will allow users to learn when the action is done.

**Comment by lorenzoPrimi** [comment]
1. Sure, I will have to manually modify the component. I was just not sure why the most used component doesn't gray down the screen!
2. We show a toast with a positive message at the moment

**Comment by holantonela** [comment]
> 2. We show a toast with a positive message at the moment
Could you show me a screenshot of it? I don't get that experience when I'm uploading results.

**Comment by lorenzoPrimi** [comment]
iOS or Android?

**Comment by lorenzoPrimi** [comment]
Actually reading the iOS code there is no Toast, I guess it was not implemented.
Should I proceed?

**Comment by holantonela** [comment]
> Should I proceed?

Yes, please. Do we already have a string for it in our translation memory?

**Comment by lorenzoPrimi** [comment]
No, we only have `"Modal.UploadFailed.Title" = "Upload failed";`
