### ISSUE TITLE
eimitimes.in website inside of OONI Run link fails upload

### ISSUE THREAD

**Issue by hellais** [ooni/probe#866]
## Expected Behavior

When tapping on the following OONI Run link I would expect all sites to be tested:
[Run link](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fifp.co.in%22%2C%22http%3A%2F%2Fsangaiexpress.com%22%2C%22http%3A%2F%2Fpoknapham.in%22%2C%22http%3A%2F%2Fsanaleibak.in%22%2C%22http%3A%2F%2Fhueiyenlanpao.com%22%2C%22http%3A%2F%2Fnaharolgithoudang.in%22%2C%22http%3A%2F%2Fichelexpress.org%22%2C%22http%3A%2F%2Fireibak.tripod.com%22%2C%22http%3A%2F%2Fimphaltimes.com%22%2C%22http%3A%2F%2Fmanipuronline.com%22%2C%22http%3A%2F%2Fkanglaonline.com%22%2C%22https%3A%2F%2Fnenow.in%22%2C%22http%3A%2F%2Ftheshillongtimes.com%22%2C%22http%3A%2F%2Fnagajournal.com%22%2C%22http%3A%2F%2Finsidene.com%22%2C%22http%3A%2F%2Fsaisat.com%22%2C%22http%3A%2F%2Fnortheastlivetv.com%22%2C%22http%3A%2F%2Fnitinthusoh.com%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Fraiot.in%22%2C%22http%3A%2F%2Feastermirrornagaland.com%22%2C%22http%3A%2F%2Fnagalimvoice.com%22%2C%22https%3A%2F%2Fphualvatimes.com%22%2C%22http%3A%2F%2Fthohepou.wordpres.com%22%2C%22https%3A%2F%2Fssumanipur.wordpress.com%22%2C%22http%3A%2F%2Fksogeneralheadquarters.weebly.com%22%2C%22http%3A%2F%2Fksog.faithweb.com%22%2C%22http%3A%2F%2Fzomiradio.org%22%2C%22http%3A%2F%2Fprja.in%22%2C%22http%3A%2F%2Fneidp.in%22%2C%22http%3A%2F%2Fnagapeoplesfront.org%22%2C%22http%3A%2F%2Fmanipur.gov.in%22%2C%22http%3A%2F%2Fmsrrda.org%22%2C%22https%3A%2F%2Fukhrul.nic.in%22%2C%22https%3A%2F%2Fwww.myfoodwifi.com%2F%22%2C%22http%3A%2F%2Fhrimanipur.org%2F%22%2C%22https%3A%2F%2Fhumanrightsmanipur.wordpress.com%2F%22%2C%22https%3A%2F%2Fcramanipur.wordpress.com%2F%22%2C%22https%3A%2F%2Fmanipurallianceforchildrights.blogspot.com%2F%22%2C%22https%3A%2F%2Fsandrp.in%2F2016%2F12%2F02%2Fcitizens-concern-for-dams-and-development-the-voice-of-vulnerable-honored-with-bhagirath-prayas-samman-at-india-rivers-week-2016%2F%22%2C%22https%3A%2F%2Fwww.hindustantimes.com%2Findia%2Fmanipur-s-horror-when-operation-bluebird-struck-terror%2Fstory-0FTWgabR6PJesb9dd9xMUL.html%22%2C%22http%3A%2F%2Fonaeme.org%2F%22%2C%22http%3A%2F%2Fcohrmanipur.org%2F%22%2C%22https%3A%2F%2Findianexpress.com%2Farticle%2Fnorth-east-india%2Fmanipur%2Fhuman-rights-activist-threatened-by-manipur-police-5129099%2F%22%2C%22https%3A%2F%2Fjustpeacefoundation.blogspot.com%2F%22%2C%22https%3A%2F%2Fcorenortheast.wordpress.com%2F%22%2C%22https%3A%2F%2Fkukiblackday.com%22%2C%22http%3A%2F%2Fwww.womensurvivorsnetwork.org%2F%22%5D%7D&mv=1.2.0)

## Actual Behavior

When I run the tests all sites are measured except for `http://eimitimes.in`.

This appears to be happening fairly often in an OONI Run with the site repeated 8 times I got 3 failures the first time and 8 the second.

[Repeated link](https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%2C%22http%3A%2F%2Feimitimes.in%22%5D%7D&mv=1.2.0)

## Specifications

  - Version: 2.1.0
  - Platform: iOS & Android

**Comment by hellais** [comment]
It seems like the root cause of this issue is the control request failing, most likely due to there being a higher timeout value set for the request in the backend than in the client.

**Comment by bassosimone** [comment]
> Also the backend waits for it to receive results for all the experiments which means the timeout should be the sum of all the individual test timeouts which can add up to quite some number I think.

Seems a reasonable explanation, and I like especially the multiplication of timeouts. I've created an issue in MK to bump the default timeout when talking to the collector.t

**Comment by hellais** [comment]
@bassosimone do you think this is now resolved? Should we close this issue?

**Comment by bassosimone** [comment]
Yes because this fix https://github.com/measurement-kit/measurement-kit/commit/b55fbecb205be62c736249b689df0c45ae342804 has landed in v0.10.5 and v0.10.6.
