### ISSUE TITLE
Implementation of app with OONI Run link via push notification using countly

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#874]
We want to send a OONI Run link via push notification.
The action triggered in this case will be not opening the OONI Browser but parsing the link and opening the OONI run screen.

**Comment by lorenzoPrimi** [comment]
Current situation: at the moment we send two types of push notifications:
type `open_href` or no type.
In the first case tapping on a notification will open the OONI Browser, in the second it's just an alert.
`open_href` type comes with a `payload` that contains `href` and `alt_hrefs`
respectively the link to open and the mirrors.

**Comment by lorenzoPrimi** [comment]
To send a OONI Run Link I see two solutions:
1) Send a notification with `ooni_run` type and a `payload` with that `ooni_run_link`
2) Send a notification with `ooni_run` type and a `payload` with a dictionary that contains: 
- Test type/name
- Test Arguments: an array of urls
- min Version (but I guess we can avoid this if we know the probe version backend side)

@hellais

**Comment by hellais** [comment]
Do we have a limit on the size of the payload we send via push notifications? Is there additional complexity if we have to implement two different code paths for OONI Run Link handling vs passing the arguments in the payload of the push notification?

Another thing that would be very useful to have support for, is displaying a message contextually to the push notification, such as: "Hey this event is happening in your country and this is why we need to run these OONI tests".

**Comment by hellais** [comment]
We should also consider that we may want to upgrade the OONI Run link format in the near future and we should be ready to handle clients that don't support that particular OONI Run link format.

I think having the app be aware of what is the supported version, rather than having to keep track of state in the backend, is going to be much more robust, so I would suggest we go for that option.

**Comment by lorenzoPrimi** [comment]
> Do we have a limit on the size of the payload we send via push notifications? Is there additional complexity if we have to implement two different code paths for OONI Run Link handling vs passing the arguments in the payload of the push notification?

I need to check how big the payload can be. But it's gonna almost be the same size in both approach I suggested

> Another thing that would be very useful to have support for, is displaying a message contextually to the push notification, such as: "Hey this event is happening in your country and this is why we need to run these OONI tests".

`alert` so the text is a field always present in every push notification

**Comment by lorenzoPrimi** [comment]
> We should also consider that we may want to upgrade the OONI Run link format in the near future and we should be ready to handle clients that don't support that particular OONI Run link format.
> 
> I think having the app be aware of what is the supported version, rather than having to keep track of state in the backend, is going to be much more robust, so I would suggest we go for that option.

You are more for option 2? I also think is more robust and we don't need to send mv as we know it from backend side

**Comment by hellais** [comment]
>  I also think is more robust and we don't need to send mv as we know it from backend side

I am actually suggesting the opposite. I am saying that the OONI Probe application should know what version it is and what version a given OONI Run link is to know if it should run it or not.
Having to keep track of the state of running probes means having to deal with keeping everything in synch which is much more tricky.

**Comment by lorenzoPrimi** [comment]
We already send the current probe version to the backend with the token so the check can be done in both sides:
- The backend will not send notification to old probes
- The probe checks the mv before running a test

**Comment by lorenzoPrimi** [comment]
@hellais this is the payload i propose to send
```{
"tn" = "websites",
"mv" = "2.4.0",
"ta" = [
http://www.google.com", "http://www.bla", "http://www.bla"
]
}```

together with the standard parameters alert, token etc

**Comment by hellais** [comment]
What is the maximum size of payload we can send?

**Comment by lorenzoPrimi** [comment]
iOS 4kb https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html
Android 4kb https://firebase.google.com/docs/cloud-messaging/concept-options?hl=it

**Comment by lorenzoPrimi** [comment]
Using the countly handling code:
- You get the "What app you want to use for this url: chrome ooni" message when tapping on notification

- If the app is open you get this modal (instead of the notification) that does nothing:
![Screenshot (Apr 1, 2020 10_20_40).png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/b5a09e20-ddc4-49a6-8e39-d4e2ff7c50ec)

Opened a ticket
https://support.count.ly/hc/en-us/community/posts/900000864366-On-click-URL-not-handled-when-app-is-in-foreground

**Comment by lorenzoPrimi** [comment]
At the moment sending a JSON
```
{"type":"ooni_run","mv":"2.2.0","tn":"web_connectivity"}
```

is working with both countly auto handling code and with my own `onMessageReceived` code.

**Comment by lorenzoPrimi** [comment]
INSTRUCTIONS:
From the countly panel:
Message -> Create Message
1) Select Test Users
2) Select Send now
3) Add
- Message title
- Message text
- Either add “On click URL”
- Or Select “Buttons 1" and add the url there
4) Tick the box and press send
Try both scenarios with app in background and app open. (4 tests in total)

[OONIProbe-2.3.2-countly.apk.zip](https://github.com/ooni/probe/files/4426015/OONIProbe-2.3.2-countly.apk.zip)
