### ISSUE TITLE
Intermittent NDT issues for OONI mobile

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#877]
# Intro

M-Lab provides the backend for the NDT and DASH OONI tests. As part of the incremental rollout of the new M-Lab platform, the NDT server has changed and we have discovered some unexpected interactions between that and MK's implementation of NDT. Because the new server has been deployed on roughly 1/3 of the M-Lab platform, not all users will experience that for all the tests that they run. I am tempted to say that one test out of three will fail, but that would be a lie :-).

The main tracking issue for the MK side of this bug is https://github.com/measurement-kit/measurement-kit/issues/1880. You can check out that ticket to see what progress we're making.

# Symptoms

With this issue I wanted to focus more on the UX impact of these issues. More specifically, I wanted to share a screen of what a user would see when a test fails. This screen has been collected and shared with by @hellais:

![A](https://user-images.githubusercontent.com/337298/62399153-22258580-b57b-11e9-8b03-1eafbec0168f.png)

Running the performance test shows that NDT failed with "N/A".

![B](https://user-images.githubusercontent.com/337298/62399186-3ec1bd80-b57b-11e9-8b1e-b30e35541a16.png)

Tapping into the results should also show "N/A".

![C](https://user-images.githubusercontent.com/337298/62399219-54cf7e00-b57b-11e9-9a95-631a8e55f93b.png)

Tapping on the test will show it as failed.

# Mitigation and resolution plan

We will mitigate the issue starting with deploying improvements to the new NDT server, most likely next week. This should make it possible for users to complete tests. At that point, users will notice that some statistics that used to be collected before the technology for collecting low level kernel statistics has changed. A subsequent update of MK and OONI will bring with it some extra reliability fixes in the MK implementations and updates such that obsolete statistics that we don't collected anymore are not shown to the user.

**Comment by bassosimone** [comment]
So, this issue has been fully mitigated. I'll open a follow-up issue pertaining to the stats.

**Comment by hellais** [comment]
I believe there are still some problems related to this.

When I was in Taiwan I wasn't able to run any speed tests here are some screenshots:
![Image from iOS (15)](https://user-images.githubusercontent.com/424620/68651293-5f5cc480-0527-11ea-9617-09234ab872b7.png)
![Image from iOS (14)](https://user-images.githubusercontent.com/424620/68651294-5f5cc480-0527-11ea-9b52-c7092c1aae8a.png)

Tapping on the "view log" or "view data" show me a modal saying "log file not found" and an empty page respectively.

**Comment by hellais** [comment]
So actually I can reproduce this problem on my home network in Italy as well, so this may be more serious in fact.

It stays stuck on the last step saying "ending download (12)" which makes me think that perhaps or https://github.com/m-lab/ndt-server/pull/162 https://github.com/m-lab/ndt-server/issues/160 may have been reverted or un-deployed?

@stephen-soltesz do you know anything about this?

**Comment by stephen-soltesz** [comment]
The changes referenced above are deployed. Can you provide more information about what values the app is using (or trying to use)?

**Comment by bassosimone** [comment]
As mentioned in https://github.com/m-lab/ndt-server/issues/160#issuecomment-553434680, we did some work to @robertodauria to prepare a fix for this issue. A PR will land soon.

**Comment by bassosimone** [comment]
This has been fixed by @m-lab now!
