### ISSUE TITLE
Move the test specific settings from the test card into the settings pane

### ISSUE THREAD

**Issue by hellais** [ooni/probe#881]
Currently each test card has settings specific to that test, for example the websites card has settings related to which categories of sites we should be testing.

It has been suggested in https://github.com/ooni/probe-android/issues/245#issuecomment-527508342 that we move these into the global settings menu.

We should consider if this is a reasonable thing to do from a UX perspective and maybe come up with some way of measuring how much of a good solution it is.

**Comment by holantonela** [comment]
I think specific per-test settings and global settings serve for different purposes. Although I see how problematic it could be having duplicated settings. Seems like will be a way easier to centralize the Settings panel. Following this path, my recommendations:

- Keep the gear icon per test screen. When the user tap to the gear icon, goes to Settings
- List all tests settings in the same /Settings/Tests screen, [grouping settings per tests using Section titles and divider lines.](https://material.io/design/platform-guidance/android-settings.html#grouping-settings)

We will need some mockups to see how it will look. I'm happy to work on those. @hellais could you point me to the editable files?

**Comment by agrabeli** [comment]
@holantonela I love your suggestion! I absolutely agree that it's best not to have duplicate settings, but to rather consolidate all settings in one place that is easily reachable. I think your suggestion about keeping the gear icons which re-direct users to the main Settings is a great idea. I also really like your suggestion about categorizing the Settings based on different groups, using Section titles and divider lines. I would love to see mockups!

@hellais @lorenzoPrimi thoughts?

**Comment by lorenzoPrimi** [comment]
I totally agree, in this case is not a duplication but making a screen accessible from two different points in the app.

**Comment by holantonela** [comment]
Cool. @lorenzoPrimi do you want to approach the first version and then we run a design review? what is the best way for you to move forward?

**Comment by lorenzoPrimi** [comment]
@holantonela sure! Should I add a setting called Test specific setting in the settings page?

**Comment by hellais** [comment]
We should probably redirect the user to the new settings location when they tap on the settings icon in the test card and display a toast saying that the settings have moved.

**Comment by lorenzoPrimi** [comment]
So  to be clear, we will have a new test settings item in the general setting page like this 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-06 at 13 44 10](https://user-images.githubusercontent.com/1616097/73909236-18dcf300-48e7-11ea-8e00-fcac52054ec1.png)

**Comment by lorenzoPrimi** [comment]
And when clicking there *every* setting for every test will be there grouped by test 
![IMG_1581](https://user-images.githubusercontent.com/1616097/73909394-88eb7900-48e7-11ea-8ecf-f60342c9a95d.jpg)
(screenshot proudly made with paint, to properly implement this some logic in the app has to change)

**Comment by lorenzoPrimi** [comment]
Or you want to have a further division like website setting, performance setting and then every setting screen separate?

**Comment by hellais** [comment]
I think we should have a top level test specific settings page and then nested inside of that we should have one page for each of the test groups.

Here is a quick mockup:

![Screenshot 2020-02-06 at 12 28 27](https://user-images.githubusercontent.com/424620/73933202-39ec1680-48dc-11ea-85f7-bd5132102d1d.png)

**Comment by lorenzoPrimi** [comment]
Thanks for the mockup, more clear now. In  fact having all the settings of every test in a single page looked a bit to odd to me

**Comment by lorenzoPrimi** [comment]
@agrabeli can you confirm the "Test Options" string or should I change it?
