### ISSUE TITLE
Write UI for the Psiphon test result for mobile

### ISSUE THREAD

**Issue by hellais** [ooni/probe#884]
The probe-mobile equivalent of: https://github.com/ooni/probe-desktop/issues/46
This depends on: ooni/probe-engine#89

**Comment by hellais** [comment]
This is dependant on: https://github.com/ooni/probe-engine/issues/10

**Comment by lorenzoPrimi** [comment]
Implemented in Android in https://github.com/ooni/probe-android/pull/326
Will do iOS iin #1180
