### ISSUE TITLE
Write UI for the Tor circumvention test results for mobile

### ISSUE THREAD

**Issue by hellais** [ooni/probe#885]
Depends on: https://github.com/ooni/probe-engine/issues/2 & https://github.com/ooni/probe-engine/issues/90 & https://github.com/ooni/probe-engine/issues/81

**Comment by lorenzoPrimi** [comment]
https://github.com/ooni/probe/issues/804

**Comment by lorenzoPrimi** [comment]
Implemented in Android in https://github.com/ooni/probe-android/pull/326
Will do iOS iin #1180
