### ISSUE TITLE
Show results of the websites tests while it's running

### ISSUE THREAD

**Issue by hellais** [ooni/probe#896]
@FedericoCeratto suggested it would be cool to have results from the websites tests appear in realtime while it's running.

**Comment by hellais** [comment]
I would say this is a very good idea as it would also entertain the user more and they are more likely to keep the window open as the results go by.

It does require a fair amount of UX work though to design and implement this.

**Comment by bassosimone** [comment]
@hellais aren't we already doing this?

**Comment by hellais** [comment]
i guess this is about showing the result of it as a first class citizen instead of the animation

**Comment by hellais** [comment]
This is related to: https://github.com/ooni/probe/issues/869 (and potentially a duplicate of it)

**Comment by bassosimone** [comment]
Thanks for looking into this! I don't think it's a duplicate, but rather a much more interactive variation of https://github.com/ooni/probe/issues/869

**Comment by lorenzoPrimi** [comment]
#869 can stay open, this can be closed as we already have the possibility to see test results while running tests (by minimising it)
