### ISSUE TITLE
Failures in gmail.com and accounts.google.com measurements

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#899]
maybe related to #865, but I guess it's something more/else.

## Actual Behavior

![image](https://user-images.githubusercontent.com/12384263/71663902-01e73600-2d68-11ea-8dc9-e783255c2f2a.png)

Retrying does not work correctly because there is no data:
![image](https://user-images.githubusercontent.com/12384263/71663911-0b709e00-2d68-11ea-8024-2c08166a2144.png)

View Log:
![image](https://user-images.githubusercontent.com/12384263/71663924-1aefe700-2d68-11ea-9ac4-3c8f91282976.png)

View Data:
![image](https://user-images.githubusercontent.com/12384263/71663934-23e0b880-2d68-11ea-9522-a8772c39574b.png)

## Steps to Reproduce the Problem

  1. run gmail.com and accounts.google.com test in the webconnectivity

## Specifications

  - Version: 2.2.0
  - Platform: Android
  - Subsystem: MK 0.10.6

**Comment by lorenzoPrimi** [comment]
I can see both data and log without any problem, I guess that was fixed in #865 
The upload doesn't work for me either.
Here are the logs:
`
01-22 08:48:20.016 15740-15930/org.openobservatory.ooniprobe I/System.out: getLogs Using bouncer to discover a collector
01-22 08:48:19.921 15740-15930/org.openobservatory.ooniprobe I/System.out: getReason collector: HTTP response code said error
`
@hellais did we solve that bug that doesn't allow big files to  be uploaded? @FedericoCeratto

**Comment by lorenzoPrimi** [comment]
Measuring `https://gmail.com` and upload measurement always gives this error, here is the the gist
https://gist.github.com/lorenzoPrimi/826bcb28c47ad1891174b07542012585

**Comment by lorenzoPrimi** [comment]
@bassosimone would be possible to get more information about the failure?

**Comment by bassosimone** [comment]
```
[D] > POST /report/20200122T105930Z_AS137_V10EdYUHVeQBNCUyUUHZ0AhmJu1hn7w7HI1C6ATHdFl1VY9Grn HTTP/1.1
[D] > Content-Type: application/json
[D] > Host: mia-ps2.ooni.nu
[D] > Content-Length: 1451137
[D] >
...
[D] {"content":{ ...snip... }}
[D] < HTTP/1.1 413 Request Entity Too Large
[D] < Server: nginx
[D] < Date: Wed, 22 Jan 2020 10:59:35 GMT
[D] < Content-Type: text/html
[D] < Content-Length: 176
[D] < Connection: close
[D] <
[D] http: BODY
[D] http: END
[D] <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

This is the relevant part of the exchange. The body is too large.

**Comment by hellais** [comment]
Damn, it's an nginx problem. Looking into this.

**Comment by lorenzoPrimi** [comment]
Tested and working
