### ISSUE TITLE
Automate uploading metadata and description to stores

### ISSUE THREAD

**Issue by hellais** [ooni/probe#901]
As pointed out in: https://github.com/TheTorProject/ooniprobe-android/pull/124#issuecomment-337154133, following suggestion from @eighthave (https://github.com/TheTorProject/ooniprobe-android/issues/87#issuecomment-337036169), we may want to use something like fastlane to automatically update app descriptions in the various languages.

This would also make updating f-droid descriptions easier (see: https://github.com/TheTorProject/ooniprobe-android/issues/87)

**Comment by lorenzoPrimi** [comment]
The automatic upload already works
The rest is a duplicate of https://github.com/ooni/probe/issues/1287

**Comment by hellais** [comment]
This is done.

**Comment by licaon-kter** [comment]
Where exactly does this Fastlane lives? F-Droid can't seee any of it... eg. No `icon.png`
