### ISSUE TITLE
Automate taking screenshots and uploading them on Android

### ISSUE THREAD

**Issue by hellais** [ooni/probe#903]
On iOS we use fastlane to take screenshots and upload them to the store with multilingual support.

We should have a similar ability on android too. 

In order to do this we should start having UITests in Android, here are some relevant docs: https://docs.fastlane.tools/getting-started/android/screenshots/#configuring-your-ui-tests-for-screengrab.

This should become easier once we have: https://github.com/ooni/probe-android/issues/186

**Comment by lorenzoPrimi** [comment]
PROGRESS: I got the json key to work, fastlane is setup to download metadata and run tests.
What is left to do is to actual create the test to take screenshot and then to upload them in GPlay

**Comment by lorenzoPrimi** [comment]
https://stackoverflow.com/questions/46192089/could-not-launch-intent-within-45-seconds-perhaps-the-main-thread-has-not-gone

**Comment by lorenzoPrimi** [comment]
https://github.com/android/testing-samples/issues/56

**Comment by lorenzoPrimi** [comment]
Adb not working : https://stackoverflow.com/questions/53674704/adbd-cannot-run-as-root-in-production-builds-even-though-the-debug-build-var

**Comment by lorenzoPrimi** [comment]
![01_dashboard_1597690994486.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/35ffe749-d981-45b4-bcdf-9d7fdfd46b41)
![02_testResults_1597690995816.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/0a001e28-95ea-4d82-9670-20de652736e3)
![03_blockedwebsiste_1597690998608.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/2d9ef914-f821-4ed8-a31a-32e6bc237aab)
![04_dash_1597691002466.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/f00387f5-e1f0-41c5-82d8-7b8c58fe8327)
![05_customurl_1597691006045.png](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/fdd2711a-9621-46a0-8077-b74c1f96552d)
