### ISSUE TITLE
Middle align header titles and tweak size and weight

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe#905]
As Android Material Design usually has Header Titles left aligned, we ended up with some not ideal title styling in many screens of the app for technical reasons as far as I can remember ( @xanscale mentioned there).

I think now would be a good time to revisit these and explore solutions on how to middle align titles (even if it means that all titles would be middle-aligned).

Furthermore, the text size of titles is rather large and could benefit from a smaller size (maybe 2sp less?) and changing the weight from Fira Sans Regular to Fira Sans SemiBold.

To illustrate:
![proposal](https://user-images.githubusercontent.com/5436686/53487230-455b7e80-3a8b-11e9-80cc-feefe883cc23.jpg)

What would our options be for this? @xanscale @lorenzoPrimi 

cc @holantonela (would appreciate your input on this)

**Comment by hellais** [comment]
I agree with @elioqoshi on this one, I think center aligning them will look better also on Android.

However the fact that:

> another option is to use custom actionbar, in this way we have no limitation but is a long work to do for all app (3/4 full work days) and need to be tested on different screen sizes for each page

I don't think 3/4 full work days is worth to just have different alignment of the action bar.

Moreover according to the material design style guide it's recommended to have the title be left aligned on Android and center aligned on iOS:

> By default, titles are left aligned on desktop. The default position of titles on mobile and tablet depends on the platform.

and then

> Android
When multiple actions, or even no actions, appear on the right side, top app bar titles are always left-aligned.
> iOS
> When multiple action buttons are on the right side, or on the home screen of an application, titles may be left-aligned.

source: 
* https://material.io/components/app-bars-top/#anatomy
* https://material.io/design/platform-guidance/cross-platform-adaptation.html#

In light of the fact that:

1. The effort required to implement this is so high
2. It doesn't appear to be the best practice according to the official style guide

My suggestion is to close this issue as wontfix and maybe review or evaluate changes related to this if and when we switch to react-native.

**Comment by lorenzoPrimi** [comment]
I remember xan worked long on this without finding an acceptable solution due to  the fact that a custom view "would" be ok but then having one,two or zero buttons on the size would completely mess that solution. So I'm willing also to mark is a wontfix  and then re-evaluate in a future.
