### ISSUE TITLE
Stat pattern has wrong margins

### ISSUE THREAD

**Issue by elioqoshi** [ooni/probe#906]
The pattern of a label and a number stat underneath seen in some of the details screens of OONI Probe have problematic margins, making it harder to understand the relationship of labels and stats. Example the NDT Details screen:

![image](https://user-images.githubusercontent.com/5436686/53494510-3d590a00-3a9e-11e9-88e1-70a48a0d39fa.png)

Here is a close-up of their anatomy to understand the problem better: 
![image](https://user-images.githubusercontent.com/5436686/53494796-d5ef8a00-3a9e-11e9-8de8-23aa2818e147.png)

@holantonela do you agree?

@xanscale could you address this?

**Comment by lorenzoPrimi** [comment]
Fixed by
https://github.com/ooni/probe-android/pull/285
and
https://github.com/ooni/probe-ios/pull/332

Screenshot
![IMG_1428.jpg](https://images.zenhubusercontent.com/589f552b51aa2c3057742305/6738b7c2-35c8-4364-9ba2-10939f360fe0)
