### ISSUE TITLE
Unable to identify the ASN of a network when connected to a low bandwidth network

### ISSUE THREAD

**Issue by chinmayisk** [ooni/probe#912]
## Expected Behavior
The ooni probe is able to identify the ASN of a network 

## Actual Behavior
The ooni probe on android as well as iOS is unable to identify the ASN of a network 

## Steps to Reproduce the Problem

  1. Run a website test / performance test on low bandwidth network 
  2. The test runs 
  3. Application records AS0

## Frequency 
Rare but was reproducable by me on different devices

## Specifications

  - Version: 2.0.3 
  - Platform: Android

  - Version: 2.0.6
  - Platform: iOS
]
![Screenshot_android](https://user-images.githubusercontent.com/1808797/58020774-caa07d80-7b26-11e9-9eef-b9027d0d313f.png)

![screenshot_iOS](https://user-images.githubusercontent.com/1808797/58020593-2f0f0d00-7b26-11e9-952a-5cf4b32d37ce.png)

**Comment by hellais** [comment]
@bassosimone I believe we can consider this issue closed since we are now reliant on the golang based engine which implements retries. Correct?

**Comment by bassosimone** [comment]
We don't have retries but a different strategy. Please, do not close. I intent to simulate these conditions and document here what I learned when we're in such difficult environments. I think we made progress but the issue still holds.

**Comment by hellais** [comment]
This is also related to: https://github.com/ooni/probe/issues/1992 & https://github.com/ooni/probe/issues/913

**Comment by bassosimone** [comment]
Could be closed in favor of https://github.com/ooni/probe/issues/1631, which describes the QA process we need to implement to solve this issue systematically by periodically checking our behavior inside lossy networks.
