### ISSUE TITLE
Problem running huge test lists in unreliable networks 

### ISSUE THREAD

**Issue by chinmayisk** [ooni/probe#913]
## Expected Behavior
The tests continue to run when the network is available after disconnection

## Actual Behavior
The test dont run and fail 

## Steps to Reproduce the Problem

  1. run a large test list in a location with unreliable network 
  2. test list run 
  3. Network disconnection happens for a few secs 
  4. The phone reconnects to internet network 

## Specifications

  - Version: tested on 2.0.3 ( but i guess this is on every version) 
  - Platform: Android 
  - Subsystem:

**Comment by hellais** [comment]
@bassosimone now that we have switched to the new golang based engine, do you think we can consider this issue resolved?

**Comment by bassosimone** [comment]
No: I think the situation improved, but we still have issues and there's need to simulate these environment and measure.

**Comment by bassosimone** [comment]
Could be closed in favor of https://github.com/ooni/probe/issues/1631, which describes the QA process we need to implement to solve this issue systematically by periodically checking our behavior inside lossy networks.
