### ISSUE TITLE
Mention the number of failed upload tries in the the UI

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#915]
![image](https://user-images.githubusercontent.com/12384263/58746562-39a39d80-8468-11e9-8b73-0e20e37dd73d.png)

It is not known what reports are being uploaded again, and whether re-uploading was completed successfully or not!
There are many tests. Finding failed tests is not easy. I think would be good if flag re-uploaded measurements in the UI. (And maybe in the Explorer)

  - Version: 2.1.0-beta.2

**Comment by lorenzoPrimi** [comment]
The solution would be to try every upload when the user presses "Upload all" and at the end show a toast  stating "Upload successful" like now or editing the current  "Upload failed" modal stating the number of failed uploads.
Is it correct?

**Comment by hellais** [comment]
> So at the first upload error the entire process is stopped, do I have to edit the algorithm to try to upload all measurement first and then show the retry popup with indication of number of fails?

Yes exactly.

This will also solve the current problem with a bad measurement preventing the upload of the following OK measurements.

> editing the current "Upload failed" modal stating the number of failed uploads.

Yes and also displaying an error string with the reason for the failure.

**Comment by lorenzoPrimi** [comment]
> Yes and also displaying an error string with the reason for the failure.

This is another issue and will be handled separately
