### ISSUE TITLE
Text overlap on website categories

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#918]
1. Open the App
2. Go to Websites ( ab card for more)
3. Press settings icon in upper right corner
4. Press Website categories to test 
5. Enable only `Circumvention tools`
6. Press disable `Circumvention tools`
7. Message `Please enable at least one test` is shown as expected and press ok to close message
8. Press Back on upper right corner

![Screenshot_2019-10-28-22-06-28-508_org openobservatory ooniprobe](https://user-images.githubusercontent.com/1616097/67741590-9ecde000-fa54-11e9-8946-e4caee690376.png)

**Comment by sarathms** [comment]
This issue happens in other parts of the `Test Options` screen too. To reproduce:
1. Open app
2. Go to settings > Test Options
3. Open any test group option
4. Try to deselect all options. This action shows the message about expecting at least one item selected.
5. Press back.
![Screenshot_20200304-223143_OONI_Probe](https://user-images.githubusercontent.com/700829/75947834-b3d9d600-5e6f-11ea-9123-bf1bb9c6745b.png)

**Comment by lorenzoPrimi** [comment]
Thank you @samsmith ! 
You helped me a lot, I think we found a pattern in the bugs, it's possible to reproduce it after an alert message appears.
