### ISSUE TITLE
When an upload fails it should display the reason for failure

### ISSUE THREAD

**Issue by hellais** [ooni/probe#919]
Currently when you try to upload a measurement and it fails, there is no indication as to why it failed.

The UI should provide information about which measurement uploads failed and why.

This is related to https://github.com/ooni/probe-android/issues/231.

**Comment by bassosimone** [comment]
@lorenzoPrimi now we have all we need from MK. Please use the latest version of mkall-ios and android-libs to get the reason why a specific resubmission failed.

**Comment by lorenzoPrimi** [comment]
How does we handle this with the changes of https://github.com/ooni/probe/issues/915 ?
In that ticket we decided to show a unique error message even if there are 10 failed uploads.

**Comment by bassosimone** [comment]
I don't know, I think this is more a question for @hellais than for me :woman_shrugging:

**Comment by lorenzoPrimi** [comment]
We need to decide here before finalising the title for https://github.com/ooni/probe/issues/915

This is the current modal, in 915 we show one modal for every batch of upload.
We need to edit these strings to add "number of failed uploads" and "reason"
`Modal.UploadFailed.Title` = `Upload failed`
`Modal.UploadFailed.Paragraph` = `Would you like to retry or cancel?`

Also we want a way to send these reasons to ooni, maybe via firebase (with user consent or automatically).
@hellais @bassosimone

**Comment by lorenzoPrimi** [comment]
Rephrasing it, we need to add 
1. Number of failed uploads
2. Reason for failure
3. Call to action live View/send failure log.

How do we proceed?

**Comment by hellais** [comment]
Can we do as an MVP that we:

1. Show the number of failed uploads in the set of uploads

Future iterations should also:

* Display the reason for failure
* Call to action to view and send failure log

The later maybe we can do using sentry, so we can log everything in the same place as we log other application error?

I would say that sending failure logs is basically assimilable to sending crash reports, but as part of this other effort, maybe it makes sense to add an additional setting for this.

**Comment by lorenzoPrimi** [comment]
1.  is already done in a PR, I only need to add the new string in transifex but better do this  before sending it to translators.
I guess we are already in the "future iteration" phase, so my question remain:
- What we write in the title and message?
- Do we show the error straight away or only on call to action?
- Do we send the logs straight away or only when the user press "report"?
- What is the call to action? View error or we show the error straight away?

**Comment by hellais** [comment]
I am maybe having a hard time understanding all this workflow and explaining it well.

Let me try to make some mockups for this.

Assumptions are:

* The user taps on "Upload all" for a set of 20 measurements
* Of these 20 measurements 8 failed

Here is the mock for the workflow:

![OONIUploadFailure](https://user-images.githubusercontent.com/424620/71975285-2afe3f80-321c-11ea-9684-33ae5c4edcb4.png)

**Comment by lorenzoPrimi** [comment]
This is more or less what I had in mind. Except the copy log retry upload that should go in other parts to be consistent with UX.
As https://github.com/ooni/probe/issues/915 is done, I will add the number of failed measurements in the message and not in the title and proceed to open a PR first

**Comment by lorenzoPrimi** [comment]
At the moment we say `The failure log has been shared with OONI developers` but we don't do anything about that.
Should we send something to firebase automatically? @hellais

**Comment by hellais** [comment]
> Should we send something to firebase automatically?

Can you use sentry to send the error logs, so that we use the same system for all platforms?

I sent you an invite to you @oo email address to have access to sentry.

**Comment by lorenzoPrimi** [comment]
@hellais can you link some docs on how to implement this?
 It's the first time I hear about sentry

**Comment by lorenzoPrimi** [comment]
I would handle sentry in a separate PR as this one already is big enough

**Comment by hellais** [comment]
> can you link some docs on how to implement this?
https://docs.sentry.io/
https://docs.sentry.io/platforms/android/
https://docs.sentry.io/clients/cocoa/

> It's the first time I hear about sentry

I think we had been discussing it since a while now. I found this other comment @bassosimone mentioning it: https://github.com/ooni/probe/issues/915#issuecomment-499111816.

> I would handle sentry in a separate PR as this one already is big enough

Yes that makes sense. I filed this: https://github.com/ooni/probe/issues/983
