### ISSUE TITLE
Support Dark Mode for iOS >= 13 and Android

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe#925]
Since iOS 13 Apple introduced a Dark Mode that is automatically enabled when it's night.

https://nshipster.com/dark-mode/
https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface/
https://developer.apple.com/videos/play/wwdc2019/214/
https://www.raywenderlich.com/10718147-supporting-dark-mode-adapting-your-app-to-support-dark-mode

We need to redesign the screens to support this new mode, at the moment I disabled dark mode globally in the app as it doesn't look so good.

![IMG_0214](https://user-images.githubusercontent.com/1616097/66728742-61c0f580-ee79-11e9-995c-88798f01d0c0.PNG)
![IMG_0215](https://user-images.githubusercontent.com/1616097/66728743-61c0f580-ee79-11e9-8a6f-415cb8c73547.PNG)

**Comment by lorenzoPrimi** [comment]
Duplicate of https://github.com/ooni/probe/issues/880

**Comment by lorenzoPrimi** [comment]
TODO:
- Apply default
- Share every screen
- Work on that

**Comment by hellais** [comment]
Since I don't currently have all the latest screens mocked up, the effort required for this is XL
