### ISSUE TITLE
mobile: fix nettest runtime measurement

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#931]
As discussed with @lorenzoPrimi, a private bug report caused us to look again into the way in which we account for the total runtime of a nettest. It turns out the algorithm we use is broken. Summing all the runtimes of all the measurements provided to us by MK, in fact, is inaccurate when running the websites test, because URLs run in parallel. Hence we should fix our algorithm.

**Comment by hellais** [comment]
What we probably want to do is keep a distinct counter/timer for the whole result set. 

As a hotfix, what we could do is take the first row inside of the result set and the last row inside of the result set and do: `result_runtime = last_row_start_time - first_row_start_time + last_row_runtime`.

**Comment by lorenzoPrimi** [comment]
I see some flaws with this solution:
- at the moment every `onEntry` callback updates the runtime, with this solution is only updated when the test ends, so in case of crash the runtime will be 0
- To know who is last_row and first_row I will have to query the database ordering tests for start_time

Let's see if we can come up with a better (and easier) solution because it doesn't feel like an "hotfix" but more an overcomplication of the code base.

**Comment by lorenzoPrimi** [comment]
@hellais @bassosimone I need your input.
If we want an "hotfix" I would use the easier `result_runtime =  end_time - start_time` as querying the database or adding complex logic doesn't see too much an hotfix

**Comment by hellais** [comment]
> If we want an "hotfix" I would use the easier result_runtime = end_time - start_time as querying the database or adding complex logic doesn't see too much an hotfix

Aren't you querying the database anyways to obtain the rows to display in the result list? How would you get `end_time` and `start_time` without querying the database?

**Comment by hellais** [comment]
> at the moment every onEntry callback updates the runtime, with this solution is only updated when the test ends, so in case of crash the runtime will be 0

If the test crashes, would you still not have a first row with a start_time and a last row with a start_time? In that case you would maybe miss the additional runtime from the last row, but maybe the right fix there is to update that row also in the case of a test crashing.

> To know who is last_row and first_row I will have to query the database ordering tests for start_time

Yes correct. I don't see why this is a flaw.
