### ISSUE TITLE
Stable release of ooni/probe-engine and ooni/probe-cli

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#945]
Make a stable release of OONI Probe CLI with functionality required by OONI Probe Desktop. We use this epic issue to track what needs to be done:

- [ ] placeholder

When we're done, we can close this issue.

**Comment by bassosimone** [comment]
We’re all on the same page: we’ll release the current code after one more round of auto updates in which we test for migrations. We should implement the separate file on disk as the feature for which we trigger the update.

**Comment by bassosimone** [comment]
I've put this epic in the next sprint. We should create issues for doing what I have described here https://github.com/ooni/probe/issues/945#issuecomment-578304329.

**Comment by hellais** [comment]
@bassosimone actually we already have an epic for this, which is the top level epic about releasing publicly OONI Probe Desktop: https://github.com/ooni/ooni.org/issues/327.

I had already put several items inside of that epic, but we should check if what is in there is still accurate following our discussion.

**Comment by bassosimone** [comment]
I don't have enough bandwidth in the next sprint to help with this endeavour. I am removing myself from this issue for the time being, and I can be reassigned inside my next sprint.

**Comment by hellais** [comment]
I think we have done several things related to this during this sprint. I suggest we close this issue and file more specific issues that document exactly what should be done going forward.
