### ISSUE TITLE
Update design document to most recent changes in probe-cli

### ISSUE THREAD

**Issue by hellais** [ooni/probe#947]
Some things need to be aligned with the design:

* [ ] Figure out what should be done WRT logging (should be stderr or stdout?)
* [ ] Settings differences

This is a result of merging: https://github.com/ooni/probe-cli/pull/63

**Comment by bassosimone** [comment]
Adding myself to the loop.

**Comment by bassosimone** [comment]
I have killed the design document PR https://github.com/ooni/probe-cli/pull/63. So, we can also close this issue.
