### ISSUE TITLE
Design the UI for the Tor test

### ISSUE THREAD

**Issue by hellais** [ooni/probe#967]
We should have a UI for how we display the results of the tor test.

The current implementation of the tor test includes some tricky technical information so we should be sure to communicate these results well to the end user.

TODO(Arturo) add the metadata that the test generates based on: https://github.com/ooni/spec/pull/175

**Comment by hellais** [comment]
@bassosimone  I think we should discuss this together today and come up with some way of presenting these results.

**Comment by hellais** [comment]
With @bassosimone we discussed and came up with some mockups for the measurement details screen in probe-desktop.

Here they are: https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/.

See:
<img width="1328" alt="Screenshot 2020-01-24 at 17 07 09" src="https://user-images.githubusercontent.com/424620/73083778-0ff22780-3ecc-11ea-8529-f4e87056319f.png">

Ideally the columns in the table would also be sortable.

@bassosimone will work on adding support for extracting as top_level `test_keys` the values needed for computing the total number of dir_auths and bridges blocked (see: https://github.com/ooni/probe-engine/issues/292)

@holantonela what do you think of these mockups?

**Comment by hellais** [comment]
I believe @sarathms has all he needs to move forward with the implementation from a UX perspective. I suggest @sarathms looks into using an existing sortable table component, and we evaluate how to style it and make it look nice in the implementation directly (hence I am not making a high res mockup of that).

If @holantonela has more feedback on this I suggest we address it as part of new issues.

**Comment by NullHypothesis** [comment]
* Shouldn't "Date & Time" be above the actual time? Same goes for "Network" and the actual network and AS.
* Should we rename "Tor Browser bridges" to "Tor Browser default bridges" or just "Default bridges"? We've been using the term "default bridges" consistently to refer to these bridges.
* At what point does the Tor test say "blocked"? Only when every single test fails? Or when the public network is blocked?

**Comment by hellais** [comment]
> Shouldn't "Date & Time" be above the actual time? Same goes for "Network" and the actual network and AS.

Ah yes I see what you mean. I think the inconsistency is actually with the label placement in the Tor related metrics and not in the hero unit.

Our general pattern for displaying this type of data is that of having the label under the value, see for example: https://explorer.ooni.org/measurement/20200129T082925Z_AS41330_edVm9y8MMZkT5cF8DEHbOnyGGISMIaDLGRbW7mq6Uq6HooJW5z.

I will update the mockups accordingly.

@sarathms do we have an existing component for the label/value pattern in the measurement details page? Do you need me to update the mockup to adjust the label positioning to be under the value?

Input from @holantonela on this would also be helpful.

> Should we rename "Tor Browser bridges" to "Tor Browser default bridges" or just "Default bridges"? We've been using the term "default bridges" consistently to refer to these bridges.

Great, let's go for "Default bridges" then!

> At what point does the Tor test say "blocked"? Only when every single test fails? Or when the public network is blocked?

It will consider it to be blocked if all the "Default bridges" AND "Directory authorities" appear to be inaccessible.
Do you think this is reasonable?

**Comment by holantonela** [comment]
I left comments [here](https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/2006ba2d-4f0c-4a65-bbcf-3b9b852348c9/Circumvention-test-details-2) and [here](https://xd.adobe.com/spec/be599718-37ef-4750-6054-7489fea5e093-c868/screen/2006ba2d-4f0c-4a65-bbcf-3b9b852348c9/Circumvention-test-details-2).

Once you have a build, please share it with me so I can run a UI debug.

**Comment by holantonela** [comment]
Okay, moving relevant discussions about the Measurement Result Page here:

1. The text description of the test result is now centered, but I think we should align it to the left.
2. The `Methodology` button may work better aligned to the right. Also, do we have a less intrusive button style? Something like a simple link?
3. The table UI should follow [iOS guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/tables/).
4. The two columns block before the table needs a better hierarchy. Which are the other tests that have this kind of component on their measurement page?

**Comment by hellais** [comment]
> The text description of the test result is now centered, but I think we should align it to the left.

Ok we can do that.

> The Methodology button may work better aligned to the right. Also, do we have a less intrusive button style? Something like a simple link?

Where would we put the runtime in that case? I suppose we could use a simple link, but for this button we followed the same pattern used on the mobile app.

See:
![Image from iOS (18)](https://user-images.githubusercontent.com/424620/73363185-85813d80-42a8-11ea-87a4-6b4127016853.png)

> The table UI should follow iOS guidelines.

I am not sure how the iOS TableView pattern is applicable to this use case. From their documentation:
> A table presents data as a scrolling, single-column list of rows that can be divided into sections or groups.

We have much more than a single column worth of data and we need to support sorting and filtering through them to make it most effective.
Moreover this is a desktop platform so I am bit confused by this suggestion.

> The two columns block before the table needs a better hierarchy. Which are the other tests that have this kind of component on their measurement page?

I think the test which has information closest to this is the Performance test.

Below is how it looks like:
![Screenshot 2020-01-29 at 15 01 53](https://user-images.githubusercontent.com/424620/73363097-5a96e980-42a8-11ea-9745-c2b73ef1e1c5.png)

I think, to be honest, that this doesn't look so nice either. I think we should maybe try to port the pattern used for this type of data from mobile into a desktop view. 

See the screenshot below:
![Image from iOS (19)](https://user-images.githubusercontent.com/424620/73363220-9a5dd100-42a8-11ea-865c-375bc429e135.png)

**Comment by hellais** [comment]
Regarding the text alignment. I have checked and in the other screens the text is in fact left aligned, so we should do the same here too.

See: 
![Screenshot 2020-01-29 at 18 10 04](https://user-images.githubusercontent.com/424620/73379585-cf771d00-42c2-11ea-8135-95717a71843f.png)

**Comment by holantonela** [comment]
> > The text description of the test result is now centered, but I think we should align it to the left.
> 
> Ok we can do that.
>
Cool

> > The Methodology button may work better aligned to the right. Also, do we have a less intrusive button style? Something like a simple link?
> 
> Where would we put the runtime in that case? I suppose we could use a simple link, but for this button we followed the same pattern used on the mobile app.
> 
Runtime should go aligned to the left. 

> > The table UI should follow iOS guidelines.
> 
> I am not sure how the iOS TableView pattern is applicable to this use case. From their documentation:
> 
> > A table presents data as a scrolling, single-column list of rows that can be divided into sections or groups.
> 
> We have much more than a single column worth of data and we need to support sorting and filtering through them to make it most effective.
> Moreover this is a desktop platform so I am bit confused by this suggestion.

Well, If i'm not wrong we are talking about the iPad app here. So iOS is the documentation you should look at.  If you want to move forward with a custom view, then we will need to discuss the details.

> > The two columns block before the table needs a better hierarchy. Which are the other tests that have this kind of component on their measurement page?
> 
> I think the test which has information closest to this is the Performance test.
> 
> Below is how it looks like:
> 
> I think, to be honest, that this doesn't look so nice either. I think we should maybe try to port the pattern used for this type of data from mobile into a desktop view.
> 
Agreed. That is what you are trying to do here, right? We need better padding (aligned to the content in the hero zone) and having the light-grey content box at the bottom.

**Comment by hellais** [comment]
> Runtime should go aligned to the left.


OK

> Well, If i'm not wrong we are talking about the iPad app here. So iOS is the documentation you should look at. If you want to move forward with a custom view, then we will need to discuss the details.

No, this is for OONI Probe Desktop, windows and macOS.

> Agreed. That is what you are trying to do here, right? We need better padding (aligned to the content in the hero zone) and having the light-grey content box at the bottom.

Yes that is the idea.

**Comment by sarathms** [comment]
Showing the error message along with the red cross in the `Connect` and `Handshakes` column wasn't possible. There isn't enough room for that. Instead I have added a way to toggle the rows to expand and show more content. This also solved the problem of long names in first column. I need inputs on 2 items:
1. Styling the rows to show that the expanded section is part of the row above it.
2. Is there a better way to indicate that the rows are expandable? Right now, hovering over the entire row turns the cursor to the pointer with a default tooltip saying 'Toggle Expanded' (which I think can be overriden).

![image](https://user-images.githubusercontent.com/700829/73515454-54e1f680-43c3-11ea-8619-a1f03ae5bb0b.png)

**Comment by hellais** [comment]
I think we can get it all to fit inside of a single column without having to resort to making the row expandable/collapsable.

What I suggest we do is we truncate the name (and possibly address too) more aggressively (80px) and eventually support displaying the full length string in a tooltop with copy-paste support.

I think that in the case in which the target name is a hash (as is the case for the ones which end up truncated), they are not really that useful to display in full, beyond just copy paste. For those which are human readable, they fit well within 80px width.

Here is a sample of how it looks like with these small width changes:
```
 const NameCell = styled.div`
-  width: 200px;
+  width: 80px;
```
![Screenshot 2020-01-31 at 10 36 01](https://user-images.githubusercontent.com/424620/73528609-7ec40900-4415-11ea-8127-88be54283343.png)

**Comment by hellais** [comment]
Since we are wrapping up this sprint I am going to take note of the next steps for improvements in another issue.

**Comment by hellais** [comment]
I have opened: https://github.com/ooni/probe/issues/990. Closing this issue so we capture the work done so far in this sprint.

**Comment by sarathms** [comment]
Showing the error message along with the red cross in the `Connect` and `Handshakes` column wasn't possible. There isn't enough room for that. Instead I have added a way to toggle the rows to expand and show more content. This also solved the problem of long names in first column. I need inputs on 2 items:
1. Styling the rows to show that the expanded section is part of the row above it.
2. Is there a better way to indicate that the rows are expandable? Right now, hovering over the entire row turns the cursor to the pointer with a default tooltip saying 'Toggle Expanded' (which I think can be overriden).

![image](https://user-images.githubusercontent.com/700829/73515454-54e1f680-43c3-11ea-8619-a1f03ae5bb0b.png)

**Comment by sarathms** [comment]
Moving the rest of the discussion to https://github.com/ooni/probe-desktop/pull/95#issuecomment-581548318

**Comment by NullHypothesis** [comment]
> > At what point does the Tor test say "blocked"? Only when every single test fails? Or when the public network is blocked?
> 
> It will consider it to be blocked if all the "Default bridges" AND "Directory authorities" appear to be inaccessible.
> Do you think this is reasonable?

Yes, I think that's very sensible. If a fresh and up-to-date Tor Browser is unable to bootstrap without help (i.e., adding bridges manually) then it's fair to label the measurement as blocked.
