### ISSUE TITLE
Assess impact of measurements without input

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#971]
Xref: https://github.com/ooni/spec/pull/175#discussion_r366478244

**Comment by bassosimone** [comment]
I've run the following measurements:

1. [telegram experiment](https://explorer.ooni.org/measurement/20200119T151130Z_AS30722_wSW7sOLgLHRQspiQ8Ojgf5RITpdhtN2o1ApitOEsD7J2z9x95h)

2. [psiphon experiment](https://explorer.ooni.org/measurement/20200119T151403Z_AS30722_7BCVXsenQ55R93LSBnSIR38YJxIvzS9shIUDEm91FtvS7uyz0q)

They're both without input and they currently look good. But they have most likely been processed by the pipeline fast path. Now the question is whether the slow path handles them correctly.

**Comment by bassosimone** [comment]
As @hellais pointed out: `temp-id-${id}` is the slow path `temp-fid-${id}` is fast path. Just look into the download JSON link to find out what to use.

**Comment by hellais** [comment]
cc @FedericoCeratto @hellais

**Comment by hellais** [comment]
We have looked into this with @bassosimone and we have concluded that the batch pipeline handles a missing input by re-adding it.

See: 
https://github.com/ooni/pipeline/blob/master/af/shovel/daily_workflow.py#L75
https://github.com/ooni/pipeline/blob/master/af/shovel/daily_workflow.py#L484

Here is an example measurement which was generated without an input and the autoclaving stage has added the `input: null` field:
https://api.ooni.io/api/v1/measurement/temp-id-345104222

**Comment by bassosimone** [comment]
So, let's close this issue, then!
