### ISSUE TITLE
Close button on Data section of measurement screen doesn't work

### ISSUE THREAD

**Issue by sarathms** [ooni/probe#987]
## Expected Behavior
Pressing the `x` button on the **Data** section header should close it.

## Actual Behavior
Nothing happens. Data section remains open, hiding the measurement details.

## Steps to Reproduce the Problem

  1. Open a measurement
  2. Click 'Data' button to open the data section
  3. Click the 'x' button.

## Specifications

  - Version: 3.0.0-rc.3
  - Platform: Linux (maybe all)

**Comment by hellais** [comment]
Yeah I noticed this one too.
