### ISSUE TITLE
Duplicate seconds string in progress indicator

### ISSUE THREAD

**Issue by hellais** [ooni/probe#988]
![Screenshot 2020-01-29 at 18 08 46](https://user-images.githubusercontent.com/424620/73379403-77d8b180-42c2-11ea-816f-6ba266b81ff6.png)

**Comment by sarathms** [comment]
This is because we use `moment.duration.humanize()` which adds 'seconds', 'minutes', 'days' to the output and we pass into `FormattedMessage` which adds the `seconds` suffix used in the mobile apps.

possible solutions:

**Comment by hellais** [comment]
If we drop humanize, though, we would only be able to show `seconds` instead of being able to also show `minutes` or `hours`, correct?

Does `moment` support languages other than English? Maybe we should look into that option and if that doesn't work as well, we can perhaps fallback to just displaying always seconds.

**Comment by hellais** [comment]
> Does moment support languages other than English? 

I checked and it has an extensive locale support: https://github.com/moment/moment/tree/develop/locale.

I say we go with moment as mentioned in the PR ooni/probe-desktop#1010.
