### ISSUE TITLE
Improve the UX of the Tor test results in OONI Probe Desktop

### ISSUE THREAD

**Issue by hellais** [ooni/probe#990]
This is a follow up issue for further improvement on top of https://github.com/ooni/probe/issues/967.

* [x] Reduce the width of the Name column in the target table (https://github.com/ooni/probe/issues/967#issuecomment-580658797)
* [ ] Left align runtime and right align the methodology button
* [x] Left align the test description
* [x] Rename "Tor Browser bridges" to "Default bridges"? 
* [ ] Come up with an improvement for how the stats are presented ("Default Bridges 10/14" and "Directory authorities 11/11"). @holantonela will do some mockups for this

@holantonela and @NullHypothesis, I believe I captured your feedback, but if I missed something please add it as a comment and I will add it to the checklist. Thanks!

**Comment by sarathms** [comment]
> Left align runtime and right align the methodology button

@holantonela Is this what you meant?
![Screenshot from 2020-02-06 17-08-07](https://user-images.githubusercontent.com/700829/73983213-e7265500-4903-11ea-902d-34fb09ba0011.png)
