### ISSUE TITLE
Make the OONI Probe desktop app rely entirely on the golang engine

### ISSUE THREAD

**Issue by hellais** [ooni/probe#996]
We are in the process of consolidating all the code related to running network experiments inside of a new golang based engine called probe-engine, which will replace measurement-kit. 

As part of this activity, we will make the OONI Probe desktop (Windows and macOS) app rely entirely on the golang engine.

We are not aiming to port the OONI Probe desktop apps to a new codebase. We are also not aiming to port the OONI CLI to a new codebase. The work we are proposing is rather to reduce the amount of C++ dependencies used by the OONI Probe CLI and the desktop apps. Below we explain in detail which components we are planning to modify, why we are doing that, and why we have chosen to start integrating these changes in the desktop apps, rather than in the mobile apps.

The current OONI Probe desktop apps for Windows and macOS are Electron-based apps implemented at github.com/ooni/probe-desktop. These apps use the CLI interface written in golang to run OONI experiments and perform other functions.

The codebase of the OONI Probe CLI interface is available at github.com/ooni/probe-cli. More in detail, we have specified how the Desktop app will exec out the CLI to perform specific tasks and we have also specified the data format emitted by the CLI when running tests.

The CLI, in turn, is based on a lower-level “engine” library written in golang and available at github.com/ooni/probe-engine. This library aims to include a unified desktop and mobile implementation of all experiments. However, inside this library, we are still linking to our old C++ engine, Measurement Kit, to implement most OONI network experiments. (Measurement Kit is composed of several GitHub repositories available at github.com/measurement-kit.)

The work described in this activity is about gradually phasing out Measurement Kit, so that in the end all experiments are written in Go rather than in C++. This will mostly happen inside the probe-engine and will mostly concern changes in the implementation of tests (i.e. rewriting from C++ to Go). We believe that the API exposed by probe-engine will not change, except for minor changes in the options supported by the new experiments (for example, we may drop an option that does not make sense in the Go context or we may add an option that did not make sense for a C++ implementation).

This should explain why we believe that writing more OONI experiments in Go as part of probe-engine does not overlap with our previous work on creating the OONI Probe desktop apps (supported by our last OTF contract). In our view, this proposed work is simply the natural continuation of what we have been working on over the past year.

The advantages of rewriting in Go are the following: 

* It will reduce the code size, because we can drop the C dependencies (whereas we cannot drop the dependency from Go since we want to ship a Psiphon experiment). 
* It allows us to write experiments that can easily and safely be interrupted, because Go natively support this functionality, which is instead rather tricky to get right in C++. 
* It allows us to easily wrap standard library functionality, hence allowing for easier low level measurements. 
* It allows us to quickly cross compile for the operating systems we care about (Windows, macOS, Linux, Android, iOS); full builds will complete in minutes rather than hours, thus enabling faster development cycles. 
* It will make OONI Probe safer, because Go is memory safe and has built-in support for concurrency.

Regarding the choice of focusing on the OONI Probe desktop app first (and on the mobile apps next) the reason is simple. Since probe-engine is already being used by the OONI Probe desktop apps via probe-cli, we have estimated that the effort (and cost) for doing this for the desktop apps is less than doing it on mobile, where we haven’t shipped golang code in production yet. In fact, we can update the desktop apps by recompiling probe-cli to use a new version of probe-engine that reimplements all tests in Go, with none or minimal API changes.

**Comment by hellais** [comment]
The steps for this are:
- Rewrite the missing C++ functions in golang: https://github.com/ooni/probe-engine/issues/40

**Comment by bassosimone** [comment]
We should evaluate whether we can consider this Epic complete as part of Sprint 21.

**Comment by bassosimone** [comment]
I've re-read the description of this issue. We have beta release of probe-cli that does not depend on Measurement Kit anymore (https://github.com/ooni/probe-cli/releases/tag/v3.0.7-beta.1). This will be the next stable release pending further testing by @hellais and @sarathms. Even if we find defects during this testing, those are new issues that are not related to this big area of work, which we can now consider closed.

**Comment by hellais** [comment]
YAYAYAYAYYAYAY!!! This is EPIC!!!

Congratulations @bassosimone for all of the great work on this, this is such a major achievment!

Kudos!

👏 🥳
