### ISSUE TITLE
Make the OONI Probe mobile app rely entirely on the golang engine

### ISSUE THREAD

**Issue by hellais** [ooni/probe#997]
We are in the process of consolidating all the code related to running network experiments inside of a new golang based engine called probe-engine, which will replace measurement-kit. 

As part of this activity, we will make the OONI Probe mobile app (Android and iOS) rely entirely on the golang engine.

**Comment by hellais** [comment]
The steps to go about doing this are:
- Managed to compile what we have now as a framework on mobile
- Manage to have an API which replaces entirely the existing API on mobile
- All things that are currently written in C++ need to be rewritten in golang

**Comment by bassosimone** [comment]
This is done now!
