### ISSUE TITLE
Release a new version of OONI Probe > 2.2.0

### ISSUE THREAD

**Issue by hellais** [ooni/probe#998]

**Comment by lorenzoPrimi** [comment]
iOS commits after 2.2.0: https://github.com/ooni/probe-ios/compare/v2.2.0...master
Android commits after 2.2.0: https://github.com/ooni/probe-android/compare/v2.2.0...master

**Comment by lorenzoPrimi** [comment]
Based on the amount of work for this sprint, the remaining PRs and the necessity to properly test a release this won't happen in this Sprint.
I attach here the Changelog from 2.2.0 for a future reference, I believe the next sprint should be all about packing a proper release, maybe with analytics. No more features.

Changelog:
- Upload reason failure
- Load text smoothly in log/json view
- Show number of failed upload
- Delete logs weekly
- Bouncer failure show reason
- Possibility to retest a set of URLs
- Allow to enable/disable max_runtime
- Updated mkall to v0.7.0/android libs to 0.10.8-android.3
- Remove Toast.WillBeAvailable
- Delete Json and Log files on rerun
- UI small tweaks
- Bug fixing


In progress:
- Custom websites: sanitize input
- New algorithm to calculate runtime
- Fix progress bar
- Move the test specific settings from the test card into the settings pane
- Custom websites: sanitize input
- Send exception logs

Optional:
- Enabling analytics on matomo

**Comment by lorenzoPrimi** [comment]
I started testing every single feature in this list + the normal test list.
@hellais which version should this app be? `2.2.1` or `2.3` ?
@agrabeli can you extrapolate a human readable changelog from this?

**Comment by hellais** [comment]
> which version should this app be? 2.2.1 or 2.3 ?

I suggest we call this 2.3.0

> can you extrapolate a human readable changelog from this?

Changelog:

* Add support for retesting a set of URLs
* Add support for displaying the reason why an upload failed
* Show number of failed upload results
* Show the reason for bouncer failures
* Sanitise the URL when choosing a custom website to test
* Add support for disabling the max_runtime by setting it to 0
* Automatically delete logs weekly
* Delete raw data and log files on rerun
* Improved runtime algorithm
* Move the test specific settings from the test card into the settings pane
* Make the text load faster in the log and raw data views
* Updated measurement-kit engine to v0.7.0/android libs to 0.10.8-android.3
* Remove Toast.WillBeAvailable
* UI small tweaks
* Bug fixing

**Comment by lorenzoPrimi** [comment]
Ok this is the Changelog for github, now I need the "What's new for the app stores"
A few lines explaining what changed, not too short but not too long

**Comment by lorenzoPrimi** [comment]
Final Changelog:

* Add support for retesting a set of URLs
* Add support for disabling the Max Runtime for Websites test
* Add support for displaying the reason why an upload failed
* Show number of failed upload results
* Show the reason for bouncer failures
* Automatically delete logs weekly
* Improved runtime algorithm for tests
* Move the test specific settings from the test card into the settings pane
* Sanitise the URL when choosing a custom website to test
* UI small tweaks
* Bug fixing

**Comment by agrabeli** [comment]
Thank you @hellais .

@lorenzoPrimi please consider using the following release notes in the app store:

# What's new

Highlights:

1. **You can re-test URLs.** This new feature can be useful if you want to collect more evidence on potential blocking, or if a test fails.

2. **You can test many more websites in one go!** By setting the websites test duration to 0 (in the settings), you can test all of the URLs included in the Citizen Lab's global and country-specific test lists.

Other improvements:

* Improved runtime algorithm
* URL sanitization in custom testing
* Test-specific settings have been moved to the Settings page
* UI tweaks
* Automatic weekly deletion of logs
* Deletion of raw data and log files upon re-run
* Faster text load in the log and raw data views
* Display of upload failure reason
* Display of number of failed upload results
* Display of bouncer failure reason
* Updated measurement-kit engine to v0.7.0/android libs to 0.10.8-android.3

**Comment by lorenzoPrimi** [comment]
Limit on Android is 500 char, I rewritten everything as:

Highlights:
1) You can re-test URLs. This new feature can be useful if you want to collect more evidence on potential blocking, or if a test fails.
2) You can test many more websites in one go! By disabling the Max Runtime (of the website settings), you can test all of the URLs included in the Citizen Lab's global and country-specific test lists.

Other improvements:
- Improved runtime algorithm
- Test-specific settings have been moved to the Settings page
- UI tweaks

**Comment by lorenzoPrimi** [comment]
TODO: Update database in the app @bassosimone
